[package]
name = "id-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
sc2-core = { version = "0.1.0", path = "../../core" }
sc2-prost = { version = "0.1.0", path = "../../pb/prost", features = ["serde"] }
convert_case = "0.6"
serde = "1"
ron = "0.8"
