use std::fmt;

#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct UnitKind(pub u32);
impl UnitKind {
	pub const NONE: Self = Self(0);
	pub const SYSTEM_SNAPSHOT_DUMMY: Self = Self(1);
	pub const BALL: Self = Self(2);
	pub const STEREOSCOPIC_OPTIONS_UNIT: Self = Self(3);
	pub const COLOSSUS: Self = Self(4);
	pub const TECH_LAB: Self = Self(5);
	pub const REACTOR: Self = Self(6);
	pub const INFESTOR_TERRAN: Self = Self(7);
	pub const BANELING_COCOON: Self = Self(8);
	pub const BANELING: Self = Self(9);
	pub const MOTHERSHIP: Self = Self(10);
	pub const POINT_DEFENSE_DRONE: Self = Self(11);
	pub const CHANGELING: Self = Self(12);
	pub const CHANGELING_ZEALOT: Self = Self(13);
	pub const CHANGELING_MARINE_SHIELD: Self = Self(14);
	pub const CHANGELING_MARINE: Self = Self(15);
	pub const CHANGELING_ZERGLING_WINGS: Self = Self(16);
	pub const CHANGELING_ZERGLING: Self = Self(17);
	pub const COMMAND_CENTER: Self = Self(18);
	pub const SUPPLY_DEPOT: Self = Self(19);
	pub const REFINERY: Self = Self(20);
	pub const BARRACKS: Self = Self(21);
	pub const ENGINEERING_BAY: Self = Self(22);
	pub const MISSILE_TURRET: Self = Self(23);
	pub const BUNKER: Self = Self(24);
	pub const SENSOR_TOWER: Self = Self(25);
	pub const GHOST_ACADEMY: Self = Self(26);
	pub const FACTORY: Self = Self(27);
	pub const STARPORT: Self = Self(28);
	pub const ARMORY: Self = Self(29);
	pub const FUSION_CORE: Self = Self(30);
	pub const AUTO_TURRET: Self = Self(31);
	pub const SIEGE_TANK_SIEGED: Self = Self(32);
	pub const SIEGE_TANK: Self = Self(33);
	pub const VIKING_ASSAULT: Self = Self(34);
	pub const VIKING_FIGHTER: Self = Self(35);
	pub const COMMAND_CENTER_FLYING: Self = Self(36);
	pub const BARRACKS_TECH_LAB: Self = Self(37);
	pub const BARRACKS_REACTOR: Self = Self(38);
	pub const FACTORY_TECH_LAB: Self = Self(39);
	pub const FACTORY_REACTOR: Self = Self(40);
	pub const STARPORT_TECH_LAB: Self = Self(41);
	pub const STARPORT_REACTOR: Self = Self(42);
	pub const FACTORY_FLYING: Self = Self(43);
	pub const STARPORT_FLYING: Self = Self(44);
	pub const SCV: Self = Self(45);
	pub const BARRACKS_FLYING: Self = Self(46);
	pub const SUPPLY_DEPOT_LOWERED: Self = Self(47);
	pub const MARINE: Self = Self(48);
	pub const REAPER: Self = Self(49);
	pub const GHOST: Self = Self(50);
	pub const MARAUDER: Self = Self(51);
	pub const THOR: Self = Self(52);
	pub const HELLION: Self = Self(53);
	pub const MEDIVAC: Self = Self(54);
	pub const BANSHEE: Self = Self(55);
	pub const RAVEN: Self = Self(56);
	pub const BATTLECRUISER: Self = Self(57);
	pub const NUKE: Self = Self(58);
	pub const NEXUS: Self = Self(59);
	pub const PYLON: Self = Self(60);
	pub const ASSIMILATOR: Self = Self(61);
	pub const GATEWAY: Self = Self(62);
	pub const FORGE: Self = Self(63);
	pub const FLEET_BEACON: Self = Self(64);
	pub const TWILIGHT_COUNCIL: Self = Self(65);
	pub const PHOTON_CANNON: Self = Self(66);
	pub const STARGATE: Self = Self(67);
	pub const TEMPLAR_ARCHIVE: Self = Self(68);
	pub const DARK_SHRINE: Self = Self(69);
	pub const ROBOTICS_BAY: Self = Self(70);
	pub const ROBOTICS_FACILITY: Self = Self(71);
	pub const CYBERNETICS_CORE: Self = Self(72);
	pub const ZEALOT: Self = Self(73);
	pub const STALKER: Self = Self(74);
	pub const HIGH_TEMPLAR: Self = Self(75);
	pub const DARK_TEMPLAR: Self = Self(76);
	pub const SENTRY: Self = Self(77);
	pub const PHOENIX: Self = Self(78);
	pub const CARRIER: Self = Self(79);
	pub const VOID_RAY: Self = Self(80);
	pub const WARP_PRISM: Self = Self(81);
	pub const OBSERVER: Self = Self(82);
	pub const IMMORTAL: Self = Self(83);
	pub const PROBE: Self = Self(84);
	pub const INTERCEPTOR: Self = Self(85);
	pub const HATCHERY: Self = Self(86);
	pub const CREEP_TUMOR: Self = Self(87);
	pub const EXTRACTOR: Self = Self(88);
	pub const SPAWNING_POOL: Self = Self(89);
	pub const EVOLUTION_CHAMBER: Self = Self(90);
	pub const HYDRALISK_DEN: Self = Self(91);
	pub const SPIRE: Self = Self(92);
	pub const ULTRALISK_CAVERN: Self = Self(93);
	pub const INFESTATION_PIT: Self = Self(94);
	pub const NYDUS_NETWORK: Self = Self(95);
	pub const BANELING_NEST: Self = Self(96);
	pub const ROACH_WARREN: Self = Self(97);
	pub const SPINE_CRAWLER: Self = Self(98);
	pub const SPORE_CRAWLER: Self = Self(99);
	pub const LAIR: Self = Self(100);
	pub const HIVE: Self = Self(101);
	pub const GREATER_SPIRE: Self = Self(102);
	pub const EGG: Self = Self(103);
	pub const DRONE: Self = Self(104);
	pub const ZERGLING: Self = Self(105);
	pub const OVERLORD: Self = Self(106);
	pub const HYDRALISK: Self = Self(107);
	pub const MUTALISK: Self = Self(108);
	pub const ULTRALISK: Self = Self(109);
	pub const ROACH: Self = Self(110);
	pub const INFESTOR: Self = Self(111);
	pub const CORRUPTOR: Self = Self(112);
	pub const BROOD_LORD_COCOON: Self = Self(113);
	pub const BROOD_LORD: Self = Self(114);
	pub const BANELING_BURROWED: Self = Self(115);
	pub const DRONE_BURROWED: Self = Self(116);
	pub const HYDRALISK_BURROWED: Self = Self(117);
	pub const ROACH_BURROWED: Self = Self(118);
	pub const ZERGLING_BURROWED: Self = Self(119);
	pub const INFESTOR_TERRAN_BURROWED: Self = Self(120);
	pub const REDSTONE_LAVA_CRITTER_BURROWED: Self = Self(121);
	pub const REDSTONE_LAVA_CRITTER_INJURED_BURROWED: Self = Self(122);
	pub const REDSTONE_LAVA_CRITTER: Self = Self(123);
	pub const REDSTONE_LAVA_CRITTER_INJURED: Self = Self(124);
	pub const QUEEN_BURROWED: Self = Self(125);
	pub const QUEEN: Self = Self(126);
	pub const INFESTOR_BURROWED: Self = Self(127);
	pub const OVERLORD_COCOON: Self = Self(128);
	pub const OVERSEER: Self = Self(129);
	pub const PLANETARY_FORTRESS: Self = Self(130);
	pub const ULTRALISK_BURROWED: Self = Self(131);
	pub const ORBITAL_COMMAND: Self = Self(132);
	pub const WARP_GATE: Self = Self(133);
	pub const ORBITAL_COMMAND_FLYING: Self = Self(134);
	pub const FORCE_FIELD: Self = Self(135);
	pub const WARP_PRISM_PHASING: Self = Self(136);
	pub const CREEP_TUMOR_BURROWED: Self = Self(137);
	pub const CREEP_TUMOR_QUEEN: Self = Self(138);
	pub const SPINE_CRAWLER_UPROOTED: Self = Self(139);
	pub const SPORE_CRAWLER_UPROOTED: Self = Self(140);
	pub const ARCHON: Self = Self(141);
	pub const NYDUS_CANAL: Self = Self(142);
	pub const BROODLING_ESCORT: Self = Self(143);
	pub const GHOST_ALTERNATE: Self = Self(144);
	pub const GHOST_NOVA: Self = Self(145);
	pub const RICH_MINERAL_FIELD: Self = Self(146);
	pub const RICH_MINERAL_FIELD_750: Self = Self(147);
	pub const URSADON: Self = Self(148);
	pub const XEL_NAGA_TOWER: Self = Self(149);
	pub const INFESTED_TERRANS_EGG: Self = Self(150);
	pub const LARVA: Self = Self(151);
	pub const REAPER_PLACEHOLDER: Self = Self(152);
	pub const MARINE_AC_GLUESCREEN_DUMMY: Self = Self(153);
	pub const FIREBAT_AC_GLUESCREEN_DUMMY: Self = Self(154);
	pub const MEDIC_AC_GLUESCREEN_DUMMY: Self = Self(155);
	pub const MARAUDER_AC_GLUESCREEN_DUMMY: Self = Self(156);
	pub const VULTURE_AC_GLUESCREEN_DUMMY: Self = Self(157);
	pub const SIEGE_TANK_AC_GLUESCREEN_DUMMY: Self = Self(158);
	pub const VIKING_AC_GLUESCREEN_DUMMY: Self = Self(159);
	pub const BANSHEE_AC_GLUESCREEN_DUMMY: Self = Self(160);
	pub const BATTLECRUISER_AC_GLUESCREEN_DUMMY: Self = Self(161);
	pub const ORBITAL_COMMAND_AC_GLUESCREEN_DUMMY: Self = Self(162);
	pub const BUNKER_AC_GLUESCREEN_DUMMY: Self = Self(163);
	pub const BUNKER_UPGRADED_AC_GLUESCREEN_DUMMY: Self = Self(164);
	pub const MISSILE_TURRET_AC_GLUESCREEN_DUMMY: Self = Self(165);
	pub const HELLBAT_AC_GLUESCREEN_DUMMY: Self = Self(166);
	pub const GOLIATH_AC_GLUESCREEN_DUMMY: Self = Self(167);
	pub const CYCLONE_AC_GLUESCREEN_DUMMY: Self = Self(168);
	pub const WRAITH_AC_GLUESCREEN_DUMMY: Self = Self(169);
	pub const SCIENCE_VESSEL_AC_GLUESCREEN_DUMMY: Self = Self(170);
	pub const HERCULES_AC_GLUESCREEN_DUMMY: Self = Self(171);
	pub const THOR_AC_GLUESCREEN_DUMMY: Self = Self(172);
	pub const PERDITION_TURRET_AC_GLUESCREEN_DUMMY: Self = Self(173);
	pub const FLAMING_BETTY_AC_GLUESCREEN_DUMMY: Self = Self(174);
	pub const DEVASTATION_TURRET_AC_GLUESCREEN_DUMMY: Self = Self(175);
	pub const BLASTER_BILLY_AC_GLUESCREEN_DUMMY: Self = Self(176);
	pub const SPINNING_DIZZY_AC_GLUESCREEN_DUMMY: Self = Self(177);
	pub const ZERGLING_KERRIGAN_AC_GLUESCREEN_DUMMY: Self = Self(178);
	pub const RAPTOR_AC_GLUESCREEN_DUMMY: Self = Self(179);
	pub const QUEEN_COOP_AC_GLUESCREEN_DUMMY: Self = Self(180);
	pub const HYDRALISK_AC_GLUESCREEN_DUMMY: Self = Self(181);
	pub const HYDRALISK_LURKER_AC_GLUESCREEN_DUMMY: Self = Self(182);
	pub const MUTALISK_BROODLORD_AC_GLUESCREEN_DUMMY: Self = Self(183);
	pub const BROOD_LORD_AC_GLUESCREEN_DUMMY: Self = Self(184);
	pub const ULTRALISK_AC_GLUESCREEN_DUMMY: Self = Self(185);
	pub const TORRASQUE_AC_GLUESCREEN_DUMMY: Self = Self(186);
	pub const OVERSEER_AC_GLUESCREEN_DUMMY: Self = Self(187);
	pub const LURKER_AC_GLUESCREEN_DUMMY: Self = Self(188);
	pub const SPINE_CRAWLER_AC_GLUESCREEN_DUMMY: Self = Self(189);
	pub const SPORE_CRAWLER_AC_GLUESCREEN_DUMMY: Self = Self(190);
	pub const NYDUS_NETWORK_AC_GLUESCREEN_DUMMY: Self = Self(191);
	pub const OMEGA_NETWORK_AC_GLUESCREEN_DUMMY: Self = Self(192);
	pub const ZERGLING_ZAGARA_AC_GLUESCREEN_DUMMY: Self = Self(193);
	pub const SWARMLING_AC_GLUESCREEN_DUMMY: Self = Self(194);
	pub const BANELING_AC_GLUESCREEN_DUMMY: Self = Self(195);
	pub const SPLITTERLING_AC_GLUESCREEN_DUMMY: Self = Self(196);
	pub const ABERRATION_AC_GLUESCREEN_DUMMY: Self = Self(197);
	pub const SCOURGE_AC_GLUESCREEN_DUMMY: Self = Self(198);
	pub const CORRUPTOR_AC_GLUESCREEN_DUMMY: Self = Self(199);
	pub const BILE_LAUNCHER_AC_GLUESCREEN_DUMMY: Self = Self(200);
	pub const SWARM_QUEEN_AC_GLUESCREEN_DUMMY: Self = Self(201);
	pub const ROACH_AC_GLUESCREEN_DUMMY: Self = Self(202);
	pub const ROACH_VILE_AC_GLUESCREEN_DUMMY: Self = Self(203);
	pub const RAVAGER_AC_GLUESCREEN_DUMMY: Self = Self(204);
	pub const SWARM_HOST_AC_GLUESCREEN_DUMMY: Self = Self(205);
	pub const MUTALISK_AC_GLUESCREEN_DUMMY: Self = Self(206);
	pub const GUARDIAN_AC_GLUESCREEN_DUMMY: Self = Self(207);
	pub const DEVOURER_AC_GLUESCREEN_DUMMY: Self = Self(208);
	pub const VIPER_AC_GLUESCREEN_DUMMY: Self = Self(209);
	pub const BRUTALISK_AC_GLUESCREEN_DUMMY: Self = Self(210);
	pub const LEVIATHAN_AC_GLUESCREEN_DUMMY: Self = Self(211);
	pub const ZEALOT_AC_GLUESCREEN_DUMMY: Self = Self(212);
	pub const ZEALOT_AIUR_AC_GLUESCREEN_DUMMY: Self = Self(213);
	pub const DRAGOON_AC_GLUESCREEN_DUMMY: Self = Self(214);
	pub const HIGH_TEMPLAR_AC_GLUESCREEN_DUMMY: Self = Self(215);
	pub const ARCHON_AC_GLUESCREEN_DUMMY: Self = Self(216);
	pub const IMMORTAL_AC_GLUESCREEN_DUMMY: Self = Self(217);
	pub const OBSERVER_AC_GLUESCREEN_DUMMY: Self = Self(218);
	pub const PHOENIX_AIUR_AC_GLUESCREEN_DUMMY: Self = Self(219);
	pub const REAVER_AC_GLUESCREEN_DUMMY: Self = Self(220);
	pub const TEMPEST_AC_GLUESCREEN_DUMMY: Self = Self(221);
	pub const PHOTON_CANNON_AC_GLUESCREEN_DUMMY: Self = Self(222);
	pub const ZEALOT_VORAZUN_AC_GLUESCREEN_DUMMY: Self = Self(223);
	pub const ZEALOT_SHAKURAS_AC_GLUESCREEN_DUMMY: Self = Self(224);
	pub const STALKER_SHAKURAS_AC_GLUESCREEN_DUMMY: Self = Self(225);
	pub const DARK_TEMPLAR_SHAKURAS_AC_GLUESCREEN_DUMMY: Self = Self(226);
	pub const CORSAIR_AC_GLUESCREEN_DUMMY: Self = Self(227);
	pub const VOID_RAY_AC_GLUESCREEN_DUMMY: Self = Self(228);
	pub const VOID_RAY_SHAKURAS_AC_GLUESCREEN_DUMMY: Self = Self(229);
	pub const ORACLE_AC_GLUESCREEN_DUMMY: Self = Self(230);
	pub const DARK_ARCHON_AC_GLUESCREEN_DUMMY: Self = Self(231);
	pub const DARK_PYLON_AC_GLUESCREEN_DUMMY: Self = Self(232);
	pub const ZEALOT_PURIFIER_AC_GLUESCREEN_DUMMY: Self = Self(233);
	pub const SENTRY_PURIFIER_AC_GLUESCREEN_DUMMY: Self = Self(234);
	pub const IMMORTAL_KARAX_AC_GLUESCREEN_DUMMY: Self = Self(235);
	pub const COLOSSUS_AC_GLUESCREEN_DUMMY: Self = Self(236);
	pub const COLOSSUS_PURIFIER_AC_GLUESCREEN_DUMMY: Self = Self(237);
	pub const PHOENIX_PURIFIER_AC_GLUESCREEN_DUMMY: Self = Self(238);
	pub const CARRIER_AC_GLUESCREEN_DUMMY: Self = Self(239);
	pub const CARRIER_AIUR_AC_GLUESCREEN_DUMMY: Self = Self(240);
	pub const KHAYDARIN_MONOLITH_AC_GLUESCREEN_DUMMY: Self = Self(241);
	pub const SHIELD_BATTERY_AC_GLUESCREEN_DUMMY: Self = Self(242);
	pub const ELITE_MARINE_AC_GLUESCREEN_DUMMY: Self = Self(243);
	pub const MARAUDER_COMMANDO_AC_GLUESCREEN_DUMMY: Self = Self(244);
	pub const SPEC_OPS_GHOST_AC_GLUESCREEN_DUMMY: Self = Self(245);
	pub const HELLBAT_RANGER_AC_GLUESCREEN_DUMMY: Self = Self(246);
	pub const STRIKE_GOLIATH_AC_GLUESCREEN_DUMMY: Self = Self(247);
	pub const HEAVY_SIEGE_TANK_AC_GLUESCREEN_DUMMY: Self = Self(248);
	pub const RAID_LIBERATOR_AC_GLUESCREEN_DUMMY: Self = Self(249);
	pub const RAVEN_TYPE_IIAC_GLUESCREEN_DUMMY: Self = Self(250);
	pub const COVERT_BANSHEE_AC_GLUESCREEN_DUMMY: Self = Self(251);
	pub const RAILGUN_TURRET_AC_GLUESCREEN_DUMMY: Self = Self(252);
	pub const BLACK_OPS_MISSILE_TURRET_AC_GLUESCREEN_DUMMY: Self = Self(253);
	pub const SUPPLICANT_AC_GLUESCREEN_DUMMY: Self = Self(254);
	pub const STALKER_TALDARIM_AC_GLUESCREEN_DUMMY: Self = Self(255);
	pub const SENTRY_TALDARIM_AC_GLUESCREEN_DUMMY: Self = Self(256);
	pub const HIGH_TEMPLAR_TALDARIM_AC_GLUESCREEN_DUMMY: Self = Self(257);
	pub const IMMORTAL_TALDARIM_AC_GLUESCREEN_DUMMY: Self = Self(258);
	pub const COLOSSUS_TALDARIM_AC_GLUESCREEN_DUMMY: Self = Self(259);
	pub const WARP_PRISM_TALDARIM_AC_GLUESCREEN_DUMMY: Self = Self(260);
	pub const PHOTON_CANNON_TALDARIM_AC_GLUESCREEN_DUMMY: Self = Self(261);
	pub const NEEDLE_SPINES_WEAPON: Self = Self(262);
	pub const CORRUPTION_WEAPON: Self = Self(263);
	pub const INFESTED_TERRANS_WEAPON: Self = Self(264);
	pub const NEURAL_PARASITE_WEAPON: Self = Self(265);
	pub const POINT_DEFENSE_DRONE_RELEASE_WEAPON: Self = Self(266);
	pub const HUNTER_SEEKER_WEAPON: Self = Self(267);
	pub const MULE: Self = Self(268);
	pub const THOR_AA_WEAPON: Self = Self(269);
	pub const PUNISHER_GRENADES_LM_WEAPON: Self = Self(270);
	pub const VIKING_FIGHTER_WEAPON: Self = Self(271);
	pub const ATA_LASER_BATTERY_LM_WEAPON: Self = Self(272);
	pub const ATS_LASER_BATTERY_LM_WEAPON: Self = Self(273);
	pub const LONGBOLT_MISSILE_WEAPON: Self = Self(274);
	pub const D_8_CHARGE_WEAPON: Self = Self(275);
	pub const YAMATO_WEAPON: Self = Self(276);
	pub const ION_CANNONS_WEAPON: Self = Self(277);
	pub const ACID_SALIVA_WEAPON: Self = Self(278);
	pub const SPINE_CRAWLER_WEAPON: Self = Self(279);
	pub const SPORE_CRAWLER_WEAPON: Self = Self(280);
	pub const GLAIVE_WURM_WEAPON: Self = Self(281);
	pub const GLAIVE_WURM_M_2_WEAPON: Self = Self(282);
	pub const GLAIVE_WURM_M_3_WEAPON: Self = Self(283);
	pub const STALKER_WEAPON: Self = Self(284);
	pub const EMP_2_WEAPON: Self = Self(285);
	pub const BACKLASH_ROCKETS_LM_WEAPON: Self = Self(286);
	pub const PHOTON_CANNON_WEAPON: Self = Self(287);
	pub const PARASITE_SPORE_WEAPON: Self = Self(288);
	pub const BROODLING: Self = Self(289);
	pub const BROOD_LORD_B_WEAPON: Self = Self(290);
	pub const AUTO_TURRET_RELEASE_WEAPON: Self = Self(291);
	pub const LARVA_RELEASE_MISSILE: Self = Self(292);
	pub const ACID_SPINES_WEAPON: Self = Self(293);
	pub const FRENZY_WEAPON: Self = Self(294);
	pub const CONTAMINATE_WEAPON: Self = Self(295);
	pub const BEACON_RALLY: Self = Self(296);
	pub const BEACON_ARMY: Self = Self(297);
	pub const BEACON_ATTACK: Self = Self(298);
	pub const BEACON_DEFEND: Self = Self(299);
	pub const BEACON_HARASS: Self = Self(300);
	pub const BEACON_IDLE: Self = Self(301);
	pub const BEACON_AUTO: Self = Self(302);
	pub const BEACON_DETECT: Self = Self(303);
	pub const BEACON_SCOUT: Self = Self(304);
	pub const BEACON_CLAIM: Self = Self(305);
	pub const BEACON_EXPAND: Self = Self(306);
	pub const BEACON_CUSTOM_1: Self = Self(307);
	pub const BEACON_CUSTOM_2: Self = Self(308);
	pub const BEACON_CUSTOM_3: Self = Self(309);
	pub const BEACON_CUSTOM_4: Self = Self(310);
	pub const ADEPT: Self = Self(311);
	pub const ROCKS_2_X_2_NON_CONJOINED: Self = Self(312);
	pub const FUNGAL_GROWTH_MISSILE: Self = Self(313);
	pub const NEURAL_PARASITE_TENTACLE_MISSILE: Self = Self(314);
	pub const BEACON_PROTOSS: Self = Self(315);
	pub const BEACON_PROTOSS_SMALL: Self = Self(316);
	pub const BEACON_TERRAN: Self = Self(317);
	pub const BEACON_TERRAN_SMALL: Self = Self(318);
	pub const BEACON_ZERG: Self = Self(319);
	pub const BEACON_ZERG_SMALL: Self = Self(320);
	pub const LYOTE: Self = Self(321);
	pub const CARRION_BIRD: Self = Self(322);
	pub const KARAK_MALE: Self = Self(323);
	pub const KARAK_FEMALE: Self = Self(324);
	pub const URSADAK_FEMALE_EXOTIC: Self = Self(325);
	pub const URSADAK_MALE: Self = Self(326);
	pub const URSADAK_FEMALE: Self = Self(327);
	pub const URSADAK_CALF: Self = Self(328);
	pub const URSADAK_MALE_EXOTIC: Self = Self(329);
	pub const UTILITY_BOT: Self = Self(330);
	pub const COMMENTATOR_BOT_1: Self = Self(331);
	pub const COMMENTATOR_BOT_2: Self = Self(332);
	pub const COMMENTATOR_BOT_3: Self = Self(333);
	pub const COMMENTATOR_BOT_4: Self = Self(334);
	pub const SCANTIPEDE: Self = Self(335);
	pub const DOG: Self = Self(336);
	pub const SHEEP: Self = Self(337);
	pub const COW: Self = Self(338);
	pub const INFESTED_TERRANS_EGG_PLACEMENT: Self = Self(339);
	pub const INFESTOR_TERRANS_WEAPON: Self = Self(340);
	pub const MINERAL_FIELD: Self = Self(341);
	pub const VESPENE_GEYSER: Self = Self(342);
	pub const SPACE_PLATFORM_GEYSER: Self = Self(343);
	pub const RICH_VESPENE_GEYSER: Self = Self(344);
	pub const DESTRUCTIBLE_SEARCHLIGHT: Self = Self(345);
	pub const DESTRUCTIBLE_BULLHORN_LIGHTS: Self = Self(346);
	pub const DESTRUCTIBLE_STREETLIGHT: Self = Self(347);
	pub const DESTRUCTIBLE_SPACE_PLATFORM_SIGN: Self = Self(348);
	pub const DESTRUCTIBLE_STORE_FRONT_CITY_PROPS: Self = Self(349);
	pub const DESTRUCTIBLE_BILLBOARD_TALL: Self = Self(350);
	pub const DESTRUCTIBLE_BILLBOARD_SCROLLING_TEXT: Self = Self(351);
	pub const DESTRUCTIBLE_SPACE_PLATFORM_BARRIER: Self = Self(352);
	pub const DESTRUCTIBLE_SIGNS_DIRECTIONAL: Self = Self(353);
	pub const DESTRUCTIBLE_SIGNS_CONSTRUCTION: Self = Self(354);
	pub const DESTRUCTIBLE_SIGNS_FUNNY: Self = Self(355);
	pub const DESTRUCTIBLE_SIGNS_ICONS: Self = Self(356);
	pub const DESTRUCTIBLE_SIGNS_WARNING: Self = Self(357);
	pub const DESTRUCTIBLE_GARAGE: Self = Self(358);
	pub const DESTRUCTIBLE_GARAGE_LARGE: Self = Self(359);
	pub const DESTRUCTIBLE_TRAFFIC_SIGNAL: Self = Self(360);
	pub const TRAFFIC_SIGNAL: Self = Self(361);
	pub const BRAXIS_ALPHA_DESTRUCTIBLE_1_X_1: Self = Self(362);
	pub const BRAXIS_ALPHA_DESTRUCTIBLE_2_X_2: Self = Self(363);
	pub const DESTRUCTIBLE_DEBRIS_4_X_4: Self = Self(364);
	pub const DESTRUCTIBLE_DEBRIS_6_X_6: Self = Self(365);
	pub const DESTRUCTIBLE_ROCK_2_X_4_VERTICAL: Self = Self(366);
	pub const DESTRUCTIBLE_ROCK_2_X_4_HORIZONTAL: Self = Self(367);
	pub const DESTRUCTIBLE_ROCK_2_X_6_VERTICAL: Self = Self(368);
	pub const DESTRUCTIBLE_ROCK_2_X_6_HORIZONTAL: Self = Self(369);
	pub const DESTRUCTIBLE_ROCK_4_X_4: Self = Self(370);
	pub const DESTRUCTIBLE_ROCK_6_X_6: Self = Self(371);
	pub const DESTRUCTIBLE_RAMP_DIAGONAL_HUGE_ULBR: Self = Self(372);
	pub const DESTRUCTIBLE_RAMP_DIAGONAL_HUGE_BLUR: Self = Self(373);
	pub const DESTRUCTIBLE_RAMP_VERTICAL_HUGE: Self = Self(374);
	pub const DESTRUCTIBLE_RAMP_HORIZONTAL_HUGE: Self = Self(375);
	pub const DESTRUCTIBLE_DEBRIS_RAMP_DIAGONAL_HUGE_ULBR: Self = Self(376);
	pub const DESTRUCTIBLE_DEBRIS_RAMP_DIAGONAL_HUGE_BLUR: Self = Self(377);
	pub const OVERLORD_GENERATE_CREEP_KEYBIND: Self = Self(378);
	pub const MENGSK_STATUE_ALONE: Self = Self(379);
	pub const MENGSK_STATUE: Self = Self(380);
	pub const WOLF_STATUE: Self = Self(381);
	pub const GLOBE_STATUE: Self = Self(382);
	pub const WEAPON: Self = Self(383);
	pub const GLAIVE_WURM_BOUNCE_WEAPON: Self = Self(384);
	pub const BROOD_LORD_WEAPON: Self = Self(385);
	pub const BROOD_LORD_A_WEAPON: Self = Self(386);
	pub const CREEP_BLOCKER_1_X_1: Self = Self(387);
	pub const PERMANENT_CREEP_BLOCKER_1_X_1: Self = Self(388);
	pub const PATHING_BLOCKER_1_X_1: Self = Self(389);
	pub const PATHING_BLOCKER_2_X_2: Self = Self(390);
	pub const AUTO_TEST_ATTACK_TARGET_GROUND: Self = Self(391);
	pub const AUTO_TEST_ATTACK_TARGET_AIR: Self = Self(392);
	pub const AUTO_TEST_ATTACKER: Self = Self(393);
	pub const HELPER_EMITTER_SELECTION_ARROW: Self = Self(394);
	pub const MULTI_KILL_OBJECT: Self = Self(395);
	pub const SHAPE_GOLFBALL: Self = Self(396);
	pub const SHAPE_CONE: Self = Self(397);
	pub const SHAPE_CUBE: Self = Self(398);
	pub const SHAPE_CYLINDER: Self = Self(399);
	pub const SHAPE_DODECAHEDRON: Self = Self(400);
	pub const SHAPE_ICOSAHEDRON: Self = Self(401);
	pub const SHAPE_OCTAHEDRON: Self = Self(402);
	pub const SHAPE_PYRAMID: Self = Self(403);
	pub const SHAPE_ROUNDED_CUBE: Self = Self(404);
	pub const SHAPE_SPHERE: Self = Self(405);
	pub const SHAPE_TETRAHEDRON: Self = Self(406);
	pub const SHAPE_THICK_TORUS: Self = Self(407);
	pub const SHAPE_THIN_TORUS: Self = Self(408);
	pub const SHAPE_TORUS: Self = Self(409);
	pub const SHAPE_4_POINT_STAR: Self = Self(410);
	pub const SHAPE_5_POINT_STAR: Self = Self(411);
	pub const SHAPE_6_POINT_STAR: Self = Self(412);
	pub const SHAPE_8_POINT_STAR: Self = Self(413);
	pub const SHAPE_ARROW_POINTER: Self = Self(414);
	pub const SHAPE_BOWL: Self = Self(415);
	pub const SHAPE_BOX: Self = Self(416);
	pub const SHAPE_CAPSULE: Self = Self(417);
	pub const SHAPE_CRESCENT_MOON: Self = Self(418);
	pub const SHAPE_DECAHEDRON: Self = Self(419);
	pub const SHAPE_DIAMOND: Self = Self(420);
	pub const SHAPE_FOOTBALL: Self = Self(421);
	pub const SHAPE_GEMSTONE: Self = Self(422);
	pub const SHAPE_HEART: Self = Self(423);
	pub const SHAPE_JACK: Self = Self(424);
	pub const SHAPE_PLUS_SIGN: Self = Self(425);
	pub const SHAPE_SHAMROCK: Self = Self(426);
	pub const SHAPE_SPADE: Self = Self(427);
	pub const SHAPE_TUBE: Self = Self(428);
	pub const SHAPE_EGG: Self = Self(429);
	pub const SHAPE_YEN_SIGN: Self = Self(430);
	pub const SHAPE_X: Self = Self(431);
	pub const SHAPE_WATERMELON: Self = Self(432);
	pub const SHAPE_WON_SIGN: Self = Self(433);
	pub const SHAPE_TENNISBALL: Self = Self(434);
	pub const SHAPE_STRAWBERRY: Self = Self(435);
	pub const SHAPE_SMILEY_FACE: Self = Self(436);
	pub const SHAPE_SOCCERBALL: Self = Self(437);
	pub const SHAPE_RAINBOW: Self = Self(438);
	pub const SHAPE_SAD_FACE: Self = Self(439);
	pub const SHAPE_POUND_SIGN: Self = Self(440);
	pub const SHAPE_PEAR: Self = Self(441);
	pub const SHAPE_PINEAPPLE: Self = Self(442);
	pub const SHAPE_ORANGE: Self = Self(443);
	pub const SHAPE_PEANUT: Self = Self(444);
	pub const SHAPE_O: Self = Self(445);
	pub const SHAPE_LEMON: Self = Self(446);
	pub const SHAPE_MONEY_BAG: Self = Self(447);
	pub const SHAPE_HORSESHOE: Self = Self(448);
	pub const SHAPE_HOCKEY_STICK: Self = Self(449);
	pub const SHAPE_HOCKEY_PUCK: Self = Self(450);
	pub const SHAPE_HAND: Self = Self(451);
	pub const SHAPE_GOLF_CLUB: Self = Self(452);
	pub const SHAPE_GRAPE: Self = Self(453);
	pub const SHAPE_EURO_SIGN: Self = Self(454);
	pub const SHAPE_DOLLAR_SIGN: Self = Self(455);
	pub const SHAPE_BASKETBALL: Self = Self(456);
	pub const SHAPE_CARROT: Self = Self(457);
	pub const SHAPE_CHERRY: Self = Self(458);
	pub const SHAPE_BASEBALL: Self = Self(459);
	pub const SHAPE_BASEBALL_BAT: Self = Self(460);
	pub const SHAPE_BANANA: Self = Self(461);
	pub const SHAPE_APPLE: Self = Self(462);
	pub const SHAPE_CASH_LARGE: Self = Self(463);
	pub const SHAPE_CASH_MEDIUM: Self = Self(464);
	pub const SHAPE_CASH_SMALL: Self = Self(465);
	pub const SHAPE_FOOTBALL_COLORED: Self = Self(466);
	pub const SHAPE_LEMON_SMALL: Self = Self(467);
	pub const SHAPE_ORANGE_SMALL: Self = Self(468);
	pub const SHAPE_TREASURE_CHEST_OPEN: Self = Self(469);
	pub const SHAPE_TREASURE_CHEST_CLOSED: Self = Self(470);
	pub const SHAPE_WATERMELON_SMALL: Self = Self(471);
	pub const UNBUILDABLE_ROCKS_DESTRUCTIBLE: Self = Self(472);
	pub const UNBUILDABLE_BRICKS_DESTRUCTIBLE: Self = Self(473);
	pub const UNBUILDABLE_PLATES_DESTRUCTIBLE: Self = Self(474);
	pub const DEBRIS_2_X_2_NON_CONJOINED: Self = Self(475);
	pub const ENEMY_PATHING_BLOCKER_1_X_1: Self = Self(476);
	pub const ENEMY_PATHING_BLOCKER_2_X_2: Self = Self(477);
	pub const ENEMY_PATHING_BLOCKER_4_X_4: Self = Self(478);
	pub const ENEMY_PATHING_BLOCKER_8_X_8: Self = Self(479);
	pub const ENEMY_PATHING_BLOCKER_16_X_16: Self = Self(480);
	pub const SCOPE_TEST: Self = Self(481);
	pub const SENTRY_AC_GLUESCREEN_DUMMY: Self = Self(482);
	pub const MINERAL_FIELD_750: Self = Self(483);
	pub const HELLION_TANK: Self = Self(484);
	pub const COLLAPSIBLE_TERRAN_TOWER_DEBRIS: Self = Self(485);
	pub const DEBRIS_RAMP_LEFT: Self = Self(486);
	pub const DEBRIS_RAMP_RIGHT: Self = Self(487);
	pub const MOTHERSHIP_CORE: Self = Self(488);
	pub const LOCUST_MP: Self = Self(489);
	pub const COLLAPSIBLE_ROCK_TOWER_DEBRIS: Self = Self(490);
	pub const NYDUS_CANAL_ATTACKER: Self = Self(491);
	pub const NYDUS_CANAL_CREEPER: Self = Self(492);
	pub const SWARM_HOST_BURROWED_MP: Self = Self(493);
	pub const SWARM_HOST_MP: Self = Self(494);
	pub const ORACLE: Self = Self(495);
	pub const TEMPEST: Self = Self(496);
	pub const WAR_HOUND: Self = Self(497);
	pub const WIDOW_MINE: Self = Self(498);
	pub const VIPER: Self = Self(499);
	pub const WIDOW_MINE_BURROWED: Self = Self(500);
	pub const LURKER_MP_EGG: Self = Self(501);
	pub const LURKER_MP: Self = Self(502);
	pub const LURKER_MP_BURROWED: Self = Self(503);
	pub const LURKER_DEN_MP: Self = Self(504);
	pub const EXTENDING_BRIDGE_NE_WIDE_8_OUT: Self = Self(505);
	pub const EXTENDING_BRIDGE_NE_WIDE_8: Self = Self(506);
	pub const EXTENDING_BRIDGE_NW_WIDE_8_OUT: Self = Self(507);
	pub const EXTENDING_BRIDGE_NW_WIDE_8: Self = Self(508);
	pub const EXTENDING_BRIDGE_NE_WIDE_10_OUT: Self = Self(509);
	pub const EXTENDING_BRIDGE_NE_WIDE_10: Self = Self(510);
	pub const EXTENDING_BRIDGE_NW_WIDE_10_OUT: Self = Self(511);
	pub const EXTENDING_BRIDGE_NW_WIDE_10: Self = Self(512);
	pub const EXTENDING_BRIDGE_NE_WIDE_12_OUT: Self = Self(513);
	pub const EXTENDING_BRIDGE_NE_WIDE_12: Self = Self(514);
	pub const EXTENDING_BRIDGE_NW_WIDE_12_OUT: Self = Self(515);
	pub const EXTENDING_BRIDGE_NW_WIDE_12: Self = Self(516);
	pub const COLLAPSIBLE_ROCK_TOWER_DEBRIS_RAMP_RIGHT: Self = Self(517);
	pub const COLLAPSIBLE_ROCK_TOWER_DEBRIS_RAMP_LEFT: Self = Self(518);
	pub const XEL_NAGA_CAVERNS_DOOR_E: Self = Self(519);
	pub const XEL_NAGA_CAVERNS_DOOR_E_OPENED: Self = Self(520);
	pub const XEL_NAGA_CAVERNS_DOOR_N: Self = Self(521);
	pub const XEL_NAGA_CAVERNS_DOOR_NE: Self = Self(522);
	pub const XEL_NAGA_CAVERNS_DOOR_NE_OPENED: Self = Self(523);
	pub const XEL_NAGA_CAVERNS_DOOR_N_OPENED: Self = Self(524);
	pub const XEL_NAGA_CAVERNS_DOOR_NW: Self = Self(525);
	pub const XEL_NAGA_CAVERNS_DOOR_NW_OPENED: Self = Self(526);
	pub const XEL_NAGA_CAVERNS_DOOR_S: Self = Self(527);
	pub const XEL_NAGA_CAVERNS_DOOR_SE: Self = Self(528);
	pub const XEL_NAGA_CAVERNS_DOOR_SE_OPENED: Self = Self(529);
	pub const XEL_NAGA_CAVERNS_DOOR_S_OPENED: Self = Self(530);
	pub const XEL_NAGA_CAVERNS_DOOR_SW: Self = Self(531);
	pub const XEL_NAGA_CAVERNS_DOOR_SW_OPENED: Self = Self(532);
	pub const XEL_NAGA_CAVERNS_DOOR_W: Self = Self(533);
	pub const XEL_NAGA_CAVERNS_DOOR_W_OPENED: Self = Self(534);
	pub const XEL_NAGA_CAVERNS_FLOATING_BRIDGE_NE_8_OUT: Self = Self(535);
	pub const XEL_NAGA_CAVERNS_FLOATING_BRIDGE_NE_8: Self = Self(536);
	pub const XEL_NAGA_CAVERNS_FLOATING_BRIDGE_NW_8_OUT: Self = Self(537);
	pub const XEL_NAGA_CAVERNS_FLOATING_BRIDGE_NW_8: Self = Self(538);
	pub const XEL_NAGA_CAVERNS_FLOATING_BRIDGE_NE_10_OUT: Self = Self(539);
	pub const XEL_NAGA_CAVERNS_FLOATING_BRIDGE_NE_10: Self = Self(540);
	pub const XEL_NAGA_CAVERNS_FLOATING_BRIDGE_NW_10_OUT: Self = Self(541);
	pub const XEL_NAGA_CAVERNS_FLOATING_BRIDGE_NW_10: Self = Self(542);
	pub const XEL_NAGA_CAVERNS_FLOATING_BRIDGE_NE_12_OUT: Self = Self(543);
	pub const XEL_NAGA_CAVERNS_FLOATING_BRIDGE_NE_12: Self = Self(544);
	pub const XEL_NAGA_CAVERNS_FLOATING_BRIDGE_NW_12_OUT: Self = Self(545);
	pub const XEL_NAGA_CAVERNS_FLOATING_BRIDGE_NW_12: Self = Self(546);
	pub const XEL_NAGA_CAVERNS_FLOATING_BRIDGE_H_8_OUT: Self = Self(547);
	pub const XEL_NAGA_CAVERNS_FLOATING_BRIDGE_H_8: Self = Self(548);
	pub const XEL_NAGA_CAVERNS_FLOATING_BRIDGE_V_8_OUT: Self = Self(549);
	pub const XEL_NAGA_CAVERNS_FLOATING_BRIDGE_V_8: Self = Self(550);
	pub const XEL_NAGA_CAVERNS_FLOATING_BRIDGE_H_10_OUT: Self = Self(551);
	pub const XEL_NAGA_CAVERNS_FLOATING_BRIDGE_H_10: Self = Self(552);
	pub const XEL_NAGA_CAVERNS_FLOATING_BRIDGE_V_10_OUT: Self = Self(553);
	pub const XEL_NAGA_CAVERNS_FLOATING_BRIDGE_V_10: Self = Self(554);
	pub const XEL_NAGA_CAVERNS_FLOATING_BRIDGE_H_12_OUT: Self = Self(555);
	pub const XEL_NAGA_CAVERNS_FLOATING_BRIDGE_H_12: Self = Self(556);
	pub const XEL_NAGA_CAVERNS_FLOATING_BRIDGE_V_12_OUT: Self = Self(557);
	pub const XEL_NAGA_CAVERNS_FLOATING_BRIDGE_V_12: Self = Self(558);
	pub const COLLAPSIBLE_TERRAN_TOWER_PUSH_UNIT_RAMP_LEFT: Self = Self(559);
	pub const COLLAPSIBLE_TERRAN_TOWER_PUSH_UNIT_RAMP_RIGHT: Self = Self(560);
	pub const COLLAPSIBLE_ROCK_TOWER_PUSH_UNIT: Self = Self(561);
	pub const COLLAPSIBLE_TERRAN_TOWER_PUSH_UNIT: Self = Self(562);
	pub const COLLAPSIBLE_ROCK_TOWER_PUSH_UNIT_RAMP_RIGHT: Self = Self(563);
	pub const COLLAPSIBLE_ROCK_TOWER_PUSH_UNIT_RAMP_LEFT: Self = Self(564);
	pub const DIGESTER_CREEP_SPRAY_TARGET_UNIT: Self = Self(565);
	pub const DIGESTER_CREEP_SPRAY_UNIT: Self = Self(566);
	pub const NYDUS_CANAL_ATTACKER_WEAPON: Self = Self(567);
	pub const VIPER_CONSUME_STRUCTURE_WEAPON: Self = Self(568);
	pub const RESOURCE_BLOCKER: Self = Self(569);
	pub const TEMPEST_WEAPON: Self = Self(570);
	pub const YOINK_MISSILE: Self = Self(571);
	pub const YOINK_VIKING_AIR_MISSILE: Self = Self(572);
	pub const YOINK_VIKING_GROUND_MISSILE: Self = Self(573);
	pub const YOINK_SIEGE_TANK_MISSILE: Self = Self(574);
	pub const WAR_HOUND_WEAPON: Self = Self(575);
	pub const EYE_STALK_WEAPON: Self = Self(576);
	pub const WIDOW_MINE_WEAPON: Self = Self(577);
	pub const WIDOW_MINE_AIR_WEAPON: Self = Self(578);
	pub const MOTHERSHIP_CORE_WEAPON_WEAPON: Self = Self(579);
	pub const TORNADO_MISSILE_WEAPON: Self = Self(580);
	pub const TORNADO_MISSILE_DUMMY_WEAPON: Self = Self(581);
	pub const TALONS_MISSILE_WEAPON: Self = Self(582);
	pub const CREEP_TUMOR_MISSILE: Self = Self(583);
	pub const LOCUST_MP_EGG_A_MISSILE_WEAPON: Self = Self(584);
	pub const LOCUST_MP_EGG_B_MISSILE_WEAPON: Self = Self(585);
	pub const LOCUST_MP_WEAPON: Self = Self(586);
	pub const REPULSOR_CANNON_WEAPON: Self = Self(587);
	pub const COLLAPSIBLE_ROCK_TOWER_DIAGONAL: Self = Self(588);
	pub const COLLAPSIBLE_TERRAN_TOWER_DIAGONAL: Self = Self(589);
	pub const COLLAPSIBLE_TERRAN_TOWER_RAMP_LEFT: Self = Self(590);
	pub const COLLAPSIBLE_TERRAN_TOWER_RAMP_RIGHT: Self = Self(591);
	pub const ICE_2_X_2_NON_CONJOINED: Self = Self(592);
	pub const ICE_PROTOSS_CRATES: Self = Self(593);
	pub const PROTOSS_CRATES: Self = Self(594);
	pub const TOWER_MINE: Self = Self(595);
	pub const PICKUP_PALLET_GAS: Self = Self(596);
	pub const PICKUP_PALLET_MINERALS: Self = Self(597);
	pub const PICKUP_SCRAP_SALVAGE_1_X_1: Self = Self(598);
	pub const PICKUP_SCRAP_SALVAGE_2_X_2: Self = Self(599);
	pub const PICKUP_SCRAP_SALVAGE_3_X_3: Self = Self(600);
	pub const ROUGH_TERRAIN: Self = Self(601);
	pub const UNBUILDABLE_BRICKS_SMALL_UNIT: Self = Self(602);
	pub const UNBUILDABLE_PLATES_SMALL_UNIT: Self = Self(603);
	pub const UNBUILDABLE_PLATES_UNIT: Self = Self(604);
	pub const UNBUILDABLE_ROCKS_SMALL_UNIT: Self = Self(605);
	pub const XEL_NAGA_HEALING_SHRINE: Self = Self(606);
	pub const INVISIBLE_TARGET_DUMMY: Self = Self(607);
	pub const PROTOSS_VESPENE_GEYSER: Self = Self(608);
	pub const COLLAPSIBLE_ROCK_TOWER: Self = Self(609);
	pub const COLLAPSIBLE_TERRAN_TOWER: Self = Self(610);
	pub const THORN_LIZARD: Self = Self(611);
	pub const CLEANING_BOT: Self = Self(612);
	pub const DESTRUCTIBLE_ROCK_6_X_6_WEAK: Self = Self(613);
	pub const PROTOSS_SNAKE_SEGMENT_DEMO: Self = Self(614);
	pub const PHYSICS_CAPSULE: Self = Self(615);
	pub const PHYSICS_CUBE: Self = Self(616);
	pub const PHYSICS_CYLINDER: Self = Self(617);
	pub const PHYSICS_KNOT: Self = Self(618);
	pub const PHYSICS_L: Self = Self(619);
	pub const PHYSICS_PRIMITIVES: Self = Self(620);
	pub const PHYSICS_SPHERE: Self = Self(621);
	pub const PHYSICS_STAR: Self = Self(622);
	pub const CREEP_BLOCKER_4_X_4: Self = Self(623);
	pub const DESTRUCTIBLE_CITY_DEBRIS_2_X_4_VERTICAL: Self = Self(624);
	pub const DESTRUCTIBLE_CITY_DEBRIS_2_X_4_HORIZONTAL: Self = Self(625);
	pub const DESTRUCTIBLE_CITY_DEBRIS_2_X_6_VERTICAL: Self = Self(626);
	pub const DESTRUCTIBLE_CITY_DEBRIS_2_X_6_HORIZONTAL: Self = Self(627);
	pub const DESTRUCTIBLE_CITY_DEBRIS_4_X_4: Self = Self(628);
	pub const DESTRUCTIBLE_CITY_DEBRIS_6_X_6: Self = Self(629);
	pub const DESTRUCTIBLE_CITY_DEBRIS_HUGE_DIAGONAL_BLUR: Self = Self(630);
	pub const DESTRUCTIBLE_CITY_DEBRIS_HUGE_DIAGONAL_ULBR: Self = Self(631);
	pub const TEST_ZERG: Self = Self(632);
	pub const PATHING_BLOCKER_RADIUS_1: Self = Self(633);
	pub const DESTRUCTIBLE_ROCK_EX_12_X_4_VERTICAL: Self = Self(634);
	pub const DESTRUCTIBLE_ROCK_EX_12_X_4_HORIZONTAL: Self = Self(635);
	pub const DESTRUCTIBLE_ROCK_EX_12_X_6_VERTICAL: Self = Self(636);
	pub const DESTRUCTIBLE_ROCK_EX_12_X_6_HORIZONTAL: Self = Self(637);
	pub const DESTRUCTIBLE_ROCK_EX_14_X_4: Self = Self(638);
	pub const DESTRUCTIBLE_ROCK_EX_16_X_6: Self = Self(639);
	pub const DESTRUCTIBLE_ROCK_EX_1_DIAGONAL_HUGE_ULBR: Self = Self(640);
	pub const DESTRUCTIBLE_ROCK_EX_1_DIAGONAL_HUGE_BLUR: Self = Self(641);
	pub const DESTRUCTIBLE_ROCK_EX_1_VERTICAL_HUGE: Self = Self(642);
	pub const DESTRUCTIBLE_ROCK_EX_1_HORIZONTAL_HUGE: Self = Self(643);
	pub const DESTRUCTIBLE_ICE_2_X_4_VERTICAL: Self = Self(644);
	pub const DESTRUCTIBLE_ICE_2_X_4_HORIZONTAL: Self = Self(645);
	pub const DESTRUCTIBLE_ICE_2_X_6_VERTICAL: Self = Self(646);
	pub const DESTRUCTIBLE_ICE_2_X_6_HORIZONTAL: Self = Self(647);
	pub const DESTRUCTIBLE_ICE_4_X_4: Self = Self(648);
	pub const DESTRUCTIBLE_ICE_6_X_6: Self = Self(649);
	pub const DESTRUCTIBLE_ICE_DIAGONAL_HUGE_ULBR: Self = Self(650);
	pub const DESTRUCTIBLE_ICE_DIAGONAL_HUGE_BLUR: Self = Self(651);
	pub const DESTRUCTIBLE_ICE_VERTICAL_HUGE: Self = Self(652);
	pub const DESTRUCTIBLE_ICE_HORIZONTAL_HUGE: Self = Self(653);
	pub const DESERT_PLANET_SEARCHLIGHT: Self = Self(654);
	pub const DESERT_PLANET_STREETLIGHT: Self = Self(655);
	pub const UNBUILDABLE_BRICKS_UNIT: Self = Self(656);
	pub const UNBUILDABLE_ROCKS_UNIT: Self = Self(657);
	pub const ZERUS_DESTRUCTIBLE_ARCH: Self = Self(658);
	pub const ARTOSILOPE: Self = Self(659);
	pub const ANTEPLOTT: Self = Self(660);
	pub const LAB_BOT: Self = Self(661);
	pub const CRABEETLE: Self = Self(662);
	pub const COLLAPSIBLE_ROCK_TOWER_RAMP_RIGHT: Self = Self(663);
	pub const COLLAPSIBLE_ROCK_TOWER_RAMP_LEFT: Self = Self(664);
	pub const LAB_MINERAL_FIELD: Self = Self(665);
	pub const LAB_MINERAL_FIELD_750: Self = Self(666);
	pub const SNOW_REFINERY_TERRAN_EXTENDING_BRIDGE_NE_SHORT_8_OUT: Self = Self(667);
	pub const SNOW_REFINERY_TERRAN_EXTENDING_BRIDGE_NE_SHORT_8: Self = Self(668);
	pub const SNOW_REFINERY_TERRAN_EXTENDING_BRIDGE_NW_SHORT_8_OUT: Self = Self(669);
	pub const SNOW_REFINERY_TERRAN_EXTENDING_BRIDGE_NW_SHORT_8: Self = Self(670);
	pub const TARSONIS_DOOR_N: Self = Self(671);
	pub const TARSONIS_DOOR_N_LOWERED: Self = Self(672);
	pub const TARSONIS_DOOR_NE: Self = Self(673);
	pub const TARSONIS_DOOR_NE_LOWERED: Self = Self(674);
	pub const TARSONIS_DOOR_E: Self = Self(675);
	pub const TARSONIS_DOOR_E_LOWERED: Self = Self(676);
	pub const TARSONIS_DOOR_NW: Self = Self(677);
	pub const TARSONIS_DOOR_NW_LOWERED: Self = Self(678);
	pub const COMPOUND_MANSION_DOOR_N: Self = Self(679);
	pub const COMPOUND_MANSION_DOOR_N_LOWERED: Self = Self(680);
	pub const COMPOUND_MANSION_DOOR_NE: Self = Self(681);
	pub const COMPOUND_MANSION_DOOR_NE_LOWERED: Self = Self(682);
	pub const COMPOUND_MANSION_DOOR_E: Self = Self(683);
	pub const COMPOUND_MANSION_DOOR_E_LOWERED: Self = Self(684);
	pub const COMPOUND_MANSION_DOOR_NW: Self = Self(685);
	pub const COMPOUND_MANSION_DOOR_NW_LOWERED: Self = Self(686);
	pub const RAVAGER_COCOON: Self = Self(687);
	pub const RAVAGER: Self = Self(688);
	pub const LIBERATOR: Self = Self(689);
	pub const RAVAGER_BURROWED: Self = Self(690);
	pub const THOR_AP: Self = Self(691);
	pub const CYCLONE: Self = Self(692);
	pub const LOCUST_MP_FLYING: Self = Self(693);
	pub const DISRUPTOR: Self = Self(694);
	pub const AIUR_LIGHT_BRIDGE_NE_8_OUT: Self = Self(695);
	pub const AIUR_LIGHT_BRIDGE_NE_8: Self = Self(696);
	pub const AIUR_LIGHT_BRIDGE_NE_10_OUT: Self = Self(697);
	pub const AIUR_LIGHT_BRIDGE_NE_10: Self = Self(698);
	pub const AIUR_LIGHT_BRIDGE_NE_12_OUT: Self = Self(699);
	pub const AIUR_LIGHT_BRIDGE_NE_12: Self = Self(700);
	pub const AIUR_LIGHT_BRIDGE_NW_8_OUT: Self = Self(701);
	pub const AIUR_LIGHT_BRIDGE_NW_8: Self = Self(702);
	pub const AIUR_LIGHT_BRIDGE_NW_10_OUT: Self = Self(703);
	pub const AIUR_LIGHT_BRIDGE_NW_10: Self = Self(704);
	pub const AIUR_LIGHT_BRIDGE_NW_12_OUT: Self = Self(705);
	pub const AIUR_LIGHT_BRIDGE_NW_12: Self = Self(706);
	pub const AIUR_TEMPLE_BRIDGE_NE_8_OUT: Self = Self(707);
	pub const AIUR_TEMPLE_BRIDGE_NE_10_OUT: Self = Self(708);
	pub const AIUR_TEMPLE_BRIDGE_NE_12_OUT: Self = Self(709);
	pub const AIUR_TEMPLE_BRIDGE_NW_8_OUT: Self = Self(710);
	pub const AIUR_TEMPLE_BRIDGE_NW_10_OUT: Self = Self(711);
	pub const AIUR_TEMPLE_BRIDGE_NW_12_OUT: Self = Self(712);
	pub const SHAKURAS_LIGHT_BRIDGE_NE_8_OUT: Self = Self(713);
	pub const SHAKURAS_LIGHT_BRIDGE_NE_8: Self = Self(714);
	pub const SHAKURAS_LIGHT_BRIDGE_NE_10_OUT: Self = Self(715);
	pub const SHAKURAS_LIGHT_BRIDGE_NE_10: Self = Self(716);
	pub const SHAKURAS_LIGHT_BRIDGE_NE_12_OUT: Self = Self(717);
	pub const SHAKURAS_LIGHT_BRIDGE_NE_12: Self = Self(718);
	pub const SHAKURAS_LIGHT_BRIDGE_NW_8_OUT: Self = Self(719);
	pub const SHAKURAS_LIGHT_BRIDGE_NW_8: Self = Self(720);
	pub const SHAKURAS_LIGHT_BRIDGE_NW_10_OUT: Self = Self(721);
	pub const SHAKURAS_LIGHT_BRIDGE_NW_10: Self = Self(722);
	pub const SHAKURAS_LIGHT_BRIDGE_NW_12_OUT: Self = Self(723);
	pub const SHAKURAS_LIGHT_BRIDGE_NW_12: Self = Self(724);
	pub const VOID_MP_IMMORTAL_REVIVE_CORPSE: Self = Self(725);
	pub const GUARDIAN_COCOON_MP: Self = Self(726);
	pub const GUARDIAN_MP: Self = Self(727);
	pub const DEVOURER_COCOON_MP: Self = Self(728);
	pub const DEVOURER_MP: Self = Self(729);
	pub const DEFILER_MP_BURROWED: Self = Self(730);
	pub const DEFILER_MP: Self = Self(731);
	pub const ORACLE_STASIS_TRAP: Self = Self(732);
	pub const DISRUPTOR_PHASED: Self = Self(733);
	pub const LIBERATOR_AG: Self = Self(734);
	pub const AIUR_LIGHT_BRIDGE_ABANDONED_NE_8_OUT: Self = Self(735);
	pub const AIUR_LIGHT_BRIDGE_ABANDONED_NE_8: Self = Self(736);
	pub const AIUR_LIGHT_BRIDGE_ABANDONED_NE_10_OUT: Self = Self(737);
	pub const AIUR_LIGHT_BRIDGE_ABANDONED_NE_10: Self = Self(738);
	pub const AIUR_LIGHT_BRIDGE_ABANDONED_NE_12_OUT: Self = Self(739);
	pub const AIUR_LIGHT_BRIDGE_ABANDONED_NE_12: Self = Self(740);
	pub const AIUR_LIGHT_BRIDGE_ABANDONED_NW_8_OUT: Self = Self(741);
	pub const AIUR_LIGHT_BRIDGE_ABANDONED_NW_8: Self = Self(742);
	pub const AIUR_LIGHT_BRIDGE_ABANDONED_NW_10_OUT: Self = Self(743);
	pub const AIUR_LIGHT_BRIDGE_ABANDONED_NW_10: Self = Self(744);
	pub const AIUR_LIGHT_BRIDGE_ABANDONED_NW_12_OUT: Self = Self(745);
	pub const AIUR_LIGHT_BRIDGE_ABANDONED_NW_12: Self = Self(746);
	pub const COLLAPSIBLE_PURIFIER_TOWER_DEBRIS: Self = Self(747);
	pub const PORT_CITY_BRIDGE_UNIT_NE_8_OUT: Self = Self(748);
	pub const PORT_CITY_BRIDGE_UNIT_NE_8: Self = Self(749);
	pub const PORT_CITY_BRIDGE_UNIT_SE_8_OUT: Self = Self(750);
	pub const PORT_CITY_BRIDGE_UNIT_SE_8: Self = Self(751);
	pub const PORT_CITY_BRIDGE_UNIT_NW_8_OUT: Self = Self(752);
	pub const PORT_CITY_BRIDGE_UNIT_NW_8: Self = Self(753);
	pub const PORT_CITY_BRIDGE_UNIT_SW_8_OUT: Self = Self(754);
	pub const PORT_CITY_BRIDGE_UNIT_SW_8: Self = Self(755);
	pub const PORT_CITY_BRIDGE_UNIT_NE_10_OUT: Self = Self(756);
	pub const PORT_CITY_BRIDGE_UNIT_NE_10: Self = Self(757);
	pub const PORT_CITY_BRIDGE_UNIT_SE_10_OUT: Self = Self(758);
	pub const PORT_CITY_BRIDGE_UNIT_SE_10: Self = Self(759);
	pub const PORT_CITY_BRIDGE_UNIT_NW_10_OUT: Self = Self(760);
	pub const PORT_CITY_BRIDGE_UNIT_NW_10: Self = Self(761);
	pub const PORT_CITY_BRIDGE_UNIT_SW_10_OUT: Self = Self(762);
	pub const PORT_CITY_BRIDGE_UNIT_SW_10: Self = Self(763);
	pub const PORT_CITY_BRIDGE_UNIT_NE_12_OUT: Self = Self(764);
	pub const PORT_CITY_BRIDGE_UNIT_NE_12: Self = Self(765);
	pub const PORT_CITY_BRIDGE_UNIT_SE_12_OUT: Self = Self(766);
	pub const PORT_CITY_BRIDGE_UNIT_SE_12: Self = Self(767);
	pub const PORT_CITY_BRIDGE_UNIT_NW_12_OUT: Self = Self(768);
	pub const PORT_CITY_BRIDGE_UNIT_NW_12: Self = Self(769);
	pub const PORT_CITY_BRIDGE_UNIT_SW_12_OUT: Self = Self(770);
	pub const PORT_CITY_BRIDGE_UNIT_SW_12: Self = Self(771);
	pub const PORT_CITY_BRIDGE_UNIT_N_8_OUT: Self = Self(772);
	pub const PORT_CITY_BRIDGE_UNIT_N_8: Self = Self(773);
	pub const PORT_CITY_BRIDGE_UNIT_S_8_OUT: Self = Self(774);
	pub const PORT_CITY_BRIDGE_UNIT_S_8: Self = Self(775);
	pub const PORT_CITY_BRIDGE_UNIT_E_8_OUT: Self = Self(776);
	pub const PORT_CITY_BRIDGE_UNIT_E_8: Self = Self(777);
	pub const PORT_CITY_BRIDGE_UNIT_W_8_OUT: Self = Self(778);
	pub const PORT_CITY_BRIDGE_UNIT_W_8: Self = Self(779);
	pub const PORT_CITY_BRIDGE_UNIT_N_10_OUT: Self = Self(780);
	pub const PORT_CITY_BRIDGE_UNIT_N_10: Self = Self(781);
	pub const PORT_CITY_BRIDGE_UNIT_S_10_OUT: Self = Self(782);
	pub const PORT_CITY_BRIDGE_UNIT_S_10: Self = Self(783);
	pub const PORT_CITY_BRIDGE_UNIT_E_10_OUT: Self = Self(784);
	pub const PORT_CITY_BRIDGE_UNIT_E_10: Self = Self(785);
	pub const PORT_CITY_BRIDGE_UNIT_W_10_OUT: Self = Self(786);
	pub const PORT_CITY_BRIDGE_UNIT_W_10: Self = Self(787);
	pub const PORT_CITY_BRIDGE_UNIT_N_12_OUT: Self = Self(788);
	pub const PORT_CITY_BRIDGE_UNIT_N_12: Self = Self(789);
	pub const PORT_CITY_BRIDGE_UNIT_S_12_OUT: Self = Self(790);
	pub const PORT_CITY_BRIDGE_UNIT_S_12: Self = Self(791);
	pub const PORT_CITY_BRIDGE_UNIT_E_12_OUT: Self = Self(792);
	pub const PORT_CITY_BRIDGE_UNIT_E_12: Self = Self(793);
	pub const PORT_CITY_BRIDGE_UNIT_W_12_OUT: Self = Self(794);
	pub const PORT_CITY_BRIDGE_UNIT_W_12: Self = Self(795);
	pub const PURIFIER_RICH_MINERAL_FIELD: Self = Self(796);
	pub const PURIFIER_RICH_MINERAL_FIELD_750: Self = Self(797);
	pub const COLLAPSIBLE_PURIFIER_TOWER_PUSH_UNIT: Self = Self(798);
	pub const LOCUST_MP_PRECURSOR: Self = Self(799);
	pub const RELEASE_INTERCEPTORS_BEACON: Self = Self(800);
	pub const ADEPT_PHASE_SHIFT: Self = Self(801);
	pub const RAVAGER_CORROSIVE_BILE_MISSILE: Self = Self(802);
	pub const HYDRALISK_IMPALE_MISSILE: Self = Self(803);
	pub const CYCLONE_MISSILE_LARGE_AIR: Self = Self(804);
	pub const CYCLONE_MISSILE: Self = Self(805);
	pub const CYCLONE_MISSILE_LARGE: Self = Self(806);
	pub const THOR_AA_LANCE: Self = Self(807);
	pub const ORACLE_WEAPON: Self = Self(808);
	pub const TEMPEST_WEAPON_GROUND: Self = Self(809);
	pub const RAVAGER_WEAPON_MISSILE: Self = Self(810);
	pub const SCOUT_MP_AIR_WEAPON_LEFT: Self = Self(811);
	pub const SCOUT_MP_AIR_WEAPON_RIGHT: Self = Self(812);
	pub const ARBITER_MP_WEAPON_MISSILE: Self = Self(813);
	pub const GUARDIAN_MP_WEAPON: Self = Self(814);
	pub const DEVOURER_MP_WEAPON_MISSILE: Self = Self(815);
	pub const DEFILER_MP_DARK_SWARM_WEAPON: Self = Self(816);
	pub const QUEEN_MP_ENSNARE_MISSILE: Self = Self(817);
	pub const QUEEN_MP_SPAWN_BROODLINGS_MISSILE: Self = Self(818);
	pub const LIGHTNING_BOMB_WEAPON: Self = Self(819);
	pub const HERC_PLACEMENT: Self = Self(820);
	pub const GRAPPLE_WEAPON: Self = Self(821);
	pub const CAUSTIC_SPRAY_MISSILE: Self = Self(822);
	pub const PARASITIC_BOMB_MISSILE: Self = Self(823);
	pub const PARASITIC_BOMB_DUMMY: Self = Self(824);
	pub const ADEPT_WEAPON: Self = Self(825);
	pub const ADEPT_UPGRADE_WEAPON: Self = Self(826);
	pub const LIBERATOR_MISSILE: Self = Self(827);
	pub const LIBERATOR_DAMAGE_MISSILE: Self = Self(828);
	pub const LIBERATOR_AG_MISSILE: Self = Self(829);
	pub const KD_8_CHARGE: Self = Self(830);
	pub const KD_8_CHARGE_WEAPON: Self = Self(831);
	pub const SLAYN_ELEMENTAL_GRAB_WEAPON: Self = Self(832);
	pub const SLAYN_ELEMENTAL_GRAB_AIR_UNIT: Self = Self(833);
	pub const SLAYN_ELEMENTAL_GRAB_GROUND_UNIT: Self = Self(834);
	pub const SLAYN_ELEMENTAL_WEAPON: Self = Self(835);
	pub const DESTRUCTIBLE_EXPEDITION_GATE_6_X_6: Self = Self(836);
	pub const DESTRUCTIBLE_ZERG_INFESTATION_3_X_3: Self = Self(837);
	pub const HERC: Self = Self(838);
	pub const MOOPY: Self = Self(839);
	pub const REPLICANT: Self = Self(840);
	pub const SEEKER_MISSILE: Self = Self(841);
	pub const AIUR_TEMPLE_BRIDGE_DESTRUCTIBLE_NE_8_OUT: Self = Self(842);
	pub const AIUR_TEMPLE_BRIDGE_DESTRUCTIBLE_NE_10_OUT: Self = Self(843);
	pub const AIUR_TEMPLE_BRIDGE_DESTRUCTIBLE_NE_12_OUT: Self = Self(844);
	pub const AIUR_TEMPLE_BRIDGE_DESTRUCTIBLE_NW_8_OUT: Self = Self(845);
	pub const AIUR_TEMPLE_BRIDGE_DESTRUCTIBLE_NW_10_OUT: Self = Self(846);
	pub const AIUR_TEMPLE_BRIDGE_DESTRUCTIBLE_NW_12_OUT: Self = Self(847);
	pub const AIUR_TEMPLE_BRIDGE_DESTRUCTIBLE_SW_8_OUT: Self = Self(848);
	pub const AIUR_TEMPLE_BRIDGE_DESTRUCTIBLE_SW_10_OUT: Self = Self(849);
	pub const AIUR_TEMPLE_BRIDGE_DESTRUCTIBLE_SW_12_OUT: Self = Self(850);
	pub const AIUR_TEMPLE_BRIDGE_DESTRUCTIBLE_SE_8_OUT: Self = Self(851);
	pub const AIUR_TEMPLE_BRIDGE_DESTRUCTIBLE_SE_10_OUT: Self = Self(852);
	pub const AIUR_TEMPLE_BRIDGE_DESTRUCTIBLE_SE_12_OUT: Self = Self(853);
	pub const FLYOVER_UNIT: Self = Self(854);
	pub const CORSAIR_MP: Self = Self(855);
	pub const SCOUT_MP: Self = Self(856);
	pub const ARBITER_MP: Self = Self(857);
	pub const SCOURGE_MP: Self = Self(858);
	pub const DEFILER_MP_PLAGUE_WEAPON: Self = Self(859);
	pub const QUEEN_MP: Self = Self(860);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_6_S: Self = Self(861);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_6_SE: Self = Self(862);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_6_E: Self = Self(863);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_6_NE: Self = Self(864);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_6_N: Self = Self(865);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_6_NW: Self = Self(866);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_6_W: Self = Self(867);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_6_SW: Self = Self(868);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_8_S: Self = Self(869);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_8_SE: Self = Self(870);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_8_E: Self = Self(871);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_8_NE: Self = Self(872);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_8_N: Self = Self(873);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_8_NW: Self = Self(874);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_8_W: Self = Self(875);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_8_SW: Self = Self(876);
	pub const REPTILE_CRATE: Self = Self(877);
	pub const SLAYN_SWARM_HOST_SPAWN_FLYER: Self = Self(878);
	pub const SLAYN_ELEMENTAL: Self = Self(879);
	pub const PURIFIER_VESPENE_GEYSER: Self = Self(880);
	pub const SHAKURAS_VESPENE_GEYSER: Self = Self(881);
	pub const COLLAPSIBLE_PURIFIER_TOWER_DIAGONAL: Self = Self(882);
	pub const CREEP_ONLY_BLOCKER_4_X_4: Self = Self(883);
	pub const PURIFIER_MINERAL_FIELD: Self = Self(884);
	pub const PURIFIER_MINERAL_FIELD_750: Self = Self(885);
	pub const BATTLE_STATION_MINERAL_FIELD: Self = Self(886);
	pub const BATTLE_STATION_MINERAL_FIELD_750: Self = Self(887);
	pub const BEACON_NOVA: Self = Self(888);
	pub const BEACON_NOVA_SMALL: Self = Self(889);
	pub const URSULA: Self = Self(890);
	pub const ELSECARO_COLONIST_HUT: Self = Self(891);
	pub const TRANSPORT_OVERLORD_COCOON: Self = Self(892);
	pub const OVERLORD_TRANSPORT: Self = Self(893);
	pub const PYLON_OVERCHARGED: Self = Self(894);
	pub const BYPASS_ARMOR_DRONE: Self = Self(895);
	pub const ADEPT_PIERCING_WEAPON: Self = Self(896);
	pub const CORROSIVE_PARASITE_WEAPON: Self = Self(897);
	pub const QUEEN_ZAGARA_AC_GLUESCREEN_DUMMY: Self = Self(1843);
	pub const OVERSEER_ZAGARA_AC_GLUESCREEN_DUMMY: Self = Self(1844);
	pub const STUKOV_INFESTED_CIVILIAN_AC_GLUESCREEN_DUMMY: Self = Self(1845);
	pub const STUKOV_INFESTED_MARINE_AC_GLUESCREEN_DUMMY: Self = Self(1846);
	pub const STUKOV_INFESTED_SIEGE_TANK_AC_GLUESCREEN_DUMMY: Self = Self(1847);
	pub const STUKOV_INFESTED_DIAMONDBACK_AC_GLUESCREEN_DUMMY: Self = Self(1848);
	pub const STUKOV_INFESTED_BANSHEE_AC_GLUESCREEN_DUMMY: Self = Self(1849);
	pub const SI_LIBERATOR_AC_GLUESCREEN_DUMMY: Self = Self(1850);
	pub const STUKOV_INFESTED_BUNKER_AC_GLUESCREEN_DUMMY: Self = Self(1851);
	pub const STUKOV_INFESTED_MISSILE_TURRET_AC_GLUESCREEN_DUMMY: Self = Self(1852);
	pub const STUKOV_BROOD_QUEEN_AC_GLUESCREEN_DUMMY: Self = Self(1853);
	pub const ZEALOT_FENIX_AC_GLUESCREEN_DUMMY: Self = Self(1854);
	pub const SENTRY_FENIX_AC_GLUESCREEN_DUMMY: Self = Self(1855);
	pub const ADEPT_FENIX_AC_GLUESCREEN_DUMMY: Self = Self(1856);
	pub const IMMORTAL_FENIX_AC_GLUESCREEN_DUMMY: Self = Self(1857);
	pub const COLOSSUS_FENIX_AC_GLUESCREEN_DUMMY: Self = Self(1858);
	pub const DISRUPTOR_AC_GLUESCREEN_DUMMY: Self = Self(1859);
	pub const OBSERVER_FENIX_AC_GLUESCREEN_DUMMY: Self = Self(1860);
	pub const SCOUT_AC_GLUESCREEN_DUMMY: Self = Self(1861);
	pub const CARRIER_FENIX_AC_GLUESCREEN_DUMMY: Self = Self(1862);
	pub const PHOTON_CANNON_FENIX_AC_GLUESCREEN_DUMMY: Self = Self(1863);
	pub const PRIMAL_ZERGLING_AC_GLUESCREEN_DUMMY: Self = Self(1864);
	pub const RAVASAUR_AC_GLUESCREEN_DUMMY: Self = Self(1865);
	pub const PRIMAL_ROACH_AC_GLUESCREEN_DUMMY: Self = Self(1866);
	pub const FIRE_ROACH_AC_GLUESCREEN_DUMMY: Self = Self(1867);
	pub const PRIMAL_GUARDIAN_AC_GLUESCREEN_DUMMY: Self = Self(1868);
	pub const PRIMAL_HYDRALISK_AC_GLUESCREEN_DUMMY: Self = Self(1869);
	pub const PRIMAL_MUTALISK_AC_GLUESCREEN_DUMMY: Self = Self(1870);
	pub const PRIMAL_IMPALER_AC_GLUESCREEN_DUMMY: Self = Self(1871);
	pub const PRIMAL_SWARM_HOST_AC_GLUESCREEN_DUMMY: Self = Self(1872);
	pub const CREEPER_HOST_AC_GLUESCREEN_DUMMY: Self = Self(1873);
	pub const PRIMAL_ULTRALISK_AC_GLUESCREEN_DUMMY: Self = Self(1874);
	pub const TYRANNOZOR_AC_GLUESCREEN_DUMMY: Self = Self(1875);
	pub const PRIMAL_WURM_AC_GLUESCREEN_DUMMY: Self = Self(1876);
	pub const HH_REAPER_AC_GLUESCREEN_DUMMY: Self = Self(1877);
	pub const HH_WIDOW_MINE_AC_GLUESCREEN_DUMMY: Self = Self(1878);
	pub const HH_HELLION_TANK_AC_GLUESCREEN_DUMMY: Self = Self(1879);
	pub const HH_WRAITH_AC_GLUESCREEN_DUMMY: Self = Self(1880);
	pub const HH_VIKING_AC_GLUESCREEN_DUMMY: Self = Self(1881);
	pub const HH_BATTLECRUISER_AC_GLUESCREEN_DUMMY: Self = Self(1882);
	pub const HH_RAVEN_AC_GLUESCREEN_DUMMY: Self = Self(1883);
	pub const HH_BOMBER_PLATFORM_AC_GLUESCREEN_DUMMY: Self = Self(1884);
	pub const HH_MERC_STARPORT_AC_GLUESCREEN_DUMMY: Self = Self(1885);
	pub const HH_MISSILE_TURRET_AC_GLUESCREEN_DUMMY: Self = Self(1886);
	pub const HIGH_TEMPLAR_SKIN_PREVIEW: Self = Self(1887);
	pub const WARP_PRISM_SKIN_PREVIEW: Self = Self(1888);
	pub const SIEGE_TANK_SKIN_PREVIEW: Self = Self(1889);
	pub const LIBERATOR_SKIN_PREVIEW: Self = Self(1890);
	pub const STUKOV_INFESTED_TROOPER_AC_GLUESCREEN_DUMMY: Self = Self(1892);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_6_S: Self = Self(1893);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_6_SE: Self = Self(1894);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_6_E: Self = Self(1895);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_6_NE: Self = Self(1896);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_6_N: Self = Self(1897);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_6_NW: Self = Self(1898);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_6_W: Self = Self(1899);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_6_SW: Self = Self(1900);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_8_S: Self = Self(1901);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_8_SE: Self = Self(1902);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_8_E: Self = Self(1903);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_8_NE: Self = Self(1904);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_8_N: Self = Self(1905);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_8_NW: Self = Self(1906);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_8_W: Self = Self(1907);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_8_SW: Self = Self(1908);
	pub const SNOW_GLAZE_STARTER_MP: Self = Self(1909);
	pub const SHIELD_BATTERY: Self = Self(1910);
	pub const OBSERVER_SIEGE_MODE: Self = Self(1911);
	pub const OVERSEER_SIEGE_MODE: Self = Self(1912);
	pub const RAVEN_REPAIR_DRONE: Self = Self(1913);
	pub const HIGH_TEMPLAR_WEAPON_MISSILE: Self = Self(1914);
	pub const CYCLONE_MISSILE_LARGE_AIR_ALTERNATIVE: Self = Self(1915);
	pub const RAVEN_SCRAMBLER_MISSILE: Self = Self(1916);
	pub const RAVEN_REPAIR_DRONE_RELEASE_WEAPON: Self = Self(1917);
	pub const RAVEN_SHREDDER_MISSILE_WEAPON: Self = Self(1918);
	pub const INFESTED_ACID_SPINES_WEAPON: Self = Self(1919);
	pub const INFESTOR_ENSNARE_ATTACK_MISSILE: Self = Self(1920);
	pub const SNARE_PLACEHOLDER: Self = Self(1921);
	pub const TYCHUS_REAPER_AC_GLUESCREEN_DUMMY: Self = Self(1922);
	pub const TYCHUS_FIREBAT_AC_GLUESCREEN_DUMMY: Self = Self(1923);
	pub const TYCHUS_SPECTRE_AC_GLUESCREEN_DUMMY: Self = Self(1924);
	pub const TYCHUS_MEDIC_AC_GLUESCREEN_DUMMY: Self = Self(1925);
	pub const TYCHUS_MARAUDER_AC_GLUESCREEN_DUMMY: Self = Self(1926);
	pub const TYCHUS_WARHOUND_AC_GLUESCREEN_DUMMY: Self = Self(1927);
	pub const TYCHUS_HERCAC_GLUESCREEN_DUMMY: Self = Self(1928);
	pub const TYCHUS_GHOST_AC_GLUESCREEN_DUMMY: Self = Self(1929);
	pub const TYCHUS_SCV_AUTO_TURRET_AC_GLUESCREEN_DUMMY: Self = Self(1930);
	pub const ZERATUL_STALKER_AC_GLUESCREEN_DUMMY: Self = Self(1931);
	pub const ZERATUL_SENTRY_AC_GLUESCREEN_DUMMY: Self = Self(1932);
	pub const ZERATUL_DARK_TEMPLAR_AC_GLUESCREEN_DUMMY: Self = Self(1933);
	pub const ZERATUL_IMMORTAL_AC_GLUESCREEN_DUMMY: Self = Self(1934);
	pub const ZERATUL_OBSERVER_AC_GLUESCREEN_DUMMY: Self = Self(1935);
	pub const ZERATUL_DISRUPTOR_AC_GLUESCREEN_DUMMY: Self = Self(1936);
	pub const ZERATUL_WARP_PRISM_AC_GLUESCREEN_DUMMY: Self = Self(1937);
	pub const ZERATUL_PHOTON_CANNON_AC_GLUESCREEN_DUMMY: Self = Self(1938);
	pub const RENEGADE_LONGBOLT_MISSILE_WEAPON: Self = Self(1939);
	pub const VIKING: Self = Self(1940);
	pub const RENEGADE_MISSILE_TURRET: Self = Self(1941);
	pub const PARASITIC_BOMB_RELAY_DUMMY: Self = Self(1942);
	pub const REFINERY_RICH: Self = Self(1943);
	pub const PREVIEW_BUNKER_UPGRADED: Self = Self(1981);
	pub const INHIBITOR_ZONE_SMALL: Self = Self(1982);
	pub const INHIBITOR_ZONE_MEDIUM: Self = Self(1983);
	pub const INHIBITOR_ZONE_LARGE: Self = Self(1984);
	pub const ACCELERATION_ZONE_SMALL: Self = Self(1985);
	pub const ACCELERATION_ZONE_MEDIUM: Self = Self(1986);
	pub const ACCELERATION_ZONE_LARGE: Self = Self(1987);
	pub const ACCELERATION_ZONE_FLYING_SMALL: Self = Self(1988);
	pub const ACCELERATION_ZONE_FLYING_MEDIUM: Self = Self(1989);
	pub const ACCELERATION_ZONE_FLYING_LARGE: Self = Self(1990);
	pub const INHIBITOR_ZONE_FLYING_SMALL: Self = Self(1991);
	pub const INHIBITOR_ZONE_FLYING_MEDIUM: Self = Self(1992);
	pub const INHIBITOR_ZONE_FLYING_LARGE: Self = Self(1993);
	pub const ASSIMILATOR_RICH: Self = Self(1994);
	pub const EXTRACTOR_RICH: Self = Self(1995);
	pub const MINERAL_FIELD_450: Self = Self(1996);
	pub const MINERAL_FIELD_OPAQUE: Self = Self(1997);
	pub const MINERAL_FIELD_OPAQUE_900: Self = Self(1998);
	pub const MECHA_ZERGLING_AC_GLUESCREEN_DUMMY: Self = Self(1999);
	pub const MECHA_BANELING_AC_GLUESCREEN_DUMMY: Self = Self(2000);
	pub const MECHA_HYDRALISK_AC_GLUESCREEN_DUMMY: Self = Self(2001);
	pub const MECHA_INFESTOR_AC_GLUESCREEN_DUMMY: Self = Self(2002);
	pub const MECHA_CORRUPTOR_AC_GLUESCREEN_DUMMY: Self = Self(2003);
	pub const MECHA_ULTRALISK_AC_GLUESCREEN_DUMMY: Self = Self(2004);
	pub const MECHA_OVERSEER_AC_GLUESCREEN_DUMMY: Self = Self(2005);
	pub const MECHA_LURKER_AC_GLUESCREEN_DUMMY: Self = Self(2006);
	pub const MECHA_BATTLECARRIER_LORD_AC_GLUESCREEN_DUMMY: Self = Self(2007);
	pub const MECHA_SPINE_CRAWLER_AC_GLUESCREEN_DUMMY: Self = Self(2008);
	pub const MECHA_SPORE_CRAWLER_AC_GLUESCREEN_DUMMY: Self = Self(2009);
	pub const TROOPER_MENGSK_AC_GLUESCREEN_DUMMY: Self = Self(2010);
	pub const MEDIVAC_MENGSK_AC_GLUESCREEN_DUMMY: Self = Self(2011);
	pub const BLIMP_MENGSK_AC_GLUESCREEN_DUMMY: Self = Self(2012);
	pub const MARAUDER_MENGSK_AC_GLUESCREEN_DUMMY: Self = Self(2013);
	pub const GHOST_MENGSK_AC_GLUESCREEN_DUMMY: Self = Self(2014);
	pub const SIEGE_TANK_MENGSK_AC_GLUESCREEN_DUMMY: Self = Self(2015);
	pub const THOR_MENGSK_AC_GLUESCREEN_DUMMY: Self = Self(2016);
	pub const VIKING_MENGSK_AC_GLUESCREEN_DUMMY: Self = Self(2017);
	pub const BATTLECRUISER_MENGSK_AC_GLUESCREEN_DUMMY: Self = Self(2018);
	pub const BUNKER_DEPOT_MENGSK_AC_GLUESCREEN_DUMMY: Self = Self(2019);
	pub const MISSILE_TURRET_MENGSK_AC_GLUESCREEN_DUMMY: Self = Self(2020);
	pub const ARTILLERY_MENGSK_AC_GLUESCREEN_DUMMY: Self = Self(2021);
	pub const LOAD_OUT_SPRAY_1: Self = Self(2022);
	pub const LOAD_OUT_SPRAY_2: Self = Self(2023);
	pub const LOAD_OUT_SPRAY_3: Self = Self(2024);
	pub const LOAD_OUT_SPRAY_4: Self = Self(2025);
	pub const LOAD_OUT_SPRAY_5: Self = Self(2026);
	pub const LOAD_OUT_SPRAY_6: Self = Self(2027);
	pub const LOAD_OUT_SPRAY_7: Self = Self(2028);
	pub const LOAD_OUT_SPRAY_8: Self = Self(2029);
	pub const LOAD_OUT_SPRAY_9: Self = Self(2030);
	pub const LOAD_OUT_SPRAY_10: Self = Self(2031);
	pub const LOAD_OUT_SPRAY_11: Self = Self(2032);
	pub const LOAD_OUT_SPRAY_12: Self = Self(2033);
	pub const LOAD_OUT_SPRAY_13: Self = Self(2034);
	pub const LOAD_OUT_SPRAY_14: Self = Self(2035);
	pub const COLLAPSIBLE_ROCK_TOWER_DEBRIS_RAMP_LEFT_GREEN: Self = Self(2036);
	pub const COLLAPSIBLE_ROCK_TOWER_DEBRIS_RAMP_RIGHT_GREEN: Self = Self(2037);
	pub const COLLAPSIBLE_ROCK_TOWER_PUSH_UNIT_RAMP_LEFT_GREEN: Self = Self(2038);
	pub const COLLAPSIBLE_ROCK_TOWER_PUSH_UNIT_RAMP_RIGHT_GREEN: Self = Self(2039);
	pub const COLLAPSIBLE_ROCK_TOWER_RAMP_LEFT_GREEN: Self = Self(2040);
	pub const COLLAPSIBLE_ROCK_TOWER_RAMP_RIGHT_GREEN: Self = Self(2041);
}
impl fmt::Display for UnitKind {
	fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
		let s = match self.0 {
			0 => "None",
			1 => "System Snapshot Dummy",
			2 => "Ball",
			3 => "Stereoscopic Options Unit",
			4 => "Colossus",
			5 => "Tech Lab",
			6 => "Reactor",
			7 => "Infestor Terran",
			8 => "Baneling Cocoon",
			9 => "Baneling",
			10 => "Mothership",
			11 => "Point Defense Drone",
			12 => "Changeling",
			13 => "Changeling Zealot",
			14 => "Changeling Marine Shield",
			15 => "Changeling Marine",
			16 => "Changeling Zergling Wings",
			17 => "Changeling Zergling",
			18 => "Command Center",
			19 => "Supply Depot",
			20 => "Refinery",
			21 => "Barracks",
			22 => "Engineering Bay",
			23 => "Missile Turret",
			24 => "Bunker",
			25 => "Sensor Tower",
			26 => "Ghost Academy",
			27 => "Factory",
			28 => "Starport",
			29 => "Armory",
			30 => "Fusion Core",
			31 => "Auto Turret",
			32 => "Siege Tank Sieged",
			33 => "Siege Tank",
			34 => "Viking Assault",
			35 => "Viking Fighter",
			36 => "Command Center Flying",
			37 => "Barracks Tech Lab",
			38 => "Barracks Reactor",
			39 => "Factory Tech Lab",
			40 => "Factory Reactor",
			41 => "Starport Tech Lab",
			42 => "Starport Reactor",
			43 => "Factory Flying",
			44 => "Starport Flying",
			45 => "Scv",
			46 => "Barracks Flying",
			47 => "Supply Depot Lowered",
			48 => "Marine",
			49 => "Reaper",
			50 => "Ghost",
			51 => "Marauder",
			52 => "Thor",
			53 => "Hellion",
			54 => "Medivac",
			55 => "Banshee",
			56 => "Raven",
			57 => "Battlecruiser",
			58 => "Nuke",
			59 => "Nexus",
			60 => "Pylon",
			61 => "Assimilator",
			62 => "Gateway",
			63 => "Forge",
			64 => "Fleet Beacon",
			65 => "Twilight Council",
			66 => "Photon Cannon",
			67 => "Stargate",
			68 => "Templar Archive",
			69 => "Dark Shrine",
			70 => "Robotics Bay",
			71 => "Robotics Facility",
			72 => "Cybernetics Core",
			73 => "Zealot",
			74 => "Stalker",
			75 => "High Templar",
			76 => "Dark Templar",
			77 => "Sentry",
			78 => "Phoenix",
			79 => "Carrier",
			80 => "Void Ray",
			81 => "Warp Prism",
			82 => "Observer",
			83 => "Immortal",
			84 => "Probe",
			85 => "Interceptor",
			86 => "Hatchery",
			87 => "Creep Tumor",
			88 => "Extractor",
			89 => "Spawning Pool",
			90 => "Evolution Chamber",
			91 => "Hydralisk Den",
			92 => "Spire",
			93 => "Ultralisk Cavern",
			94 => "Infestation Pit",
			95 => "Nydus Network",
			96 => "Baneling Nest",
			97 => "Roach Warren",
			98 => "Spine Crawler",
			99 => "Spore Crawler",
			100 => "Lair",
			101 => "Hive",
			102 => "Greater Spire",
			103 => "Egg",
			104 => "Drone",
			105 => "Zergling",
			106 => "Overlord",
			107 => "Hydralisk",
			108 => "Mutalisk",
			109 => "Ultralisk",
			110 => "Roach",
			111 => "Infestor",
			112 => "Corruptor",
			113 => "Brood Lord Cocoon",
			114 => "Brood Lord",
			115 => "Baneling Burrowed",
			116 => "Drone Burrowed",
			117 => "Hydralisk Burrowed",
			118 => "Roach Burrowed",
			119 => "Zergling Burrowed",
			120 => "Infestor Terran Burrowed",
			121 => "Redstone Lava Critter Burrowed",
			122 => "Redstone Lava Critter Injured Burrowed",
			123 => "Redstone Lava Critter",
			124 => "Redstone Lava Critter Injured",
			125 => "Queen Burrowed",
			126 => "Queen",
			127 => "Infestor Burrowed",
			128 => "Overlord Cocoon",
			129 => "Overseer",
			130 => "Planetary Fortress",
			131 => "Ultralisk Burrowed",
			132 => "Orbital Command",
			133 => "Warp Gate",
			134 => "Orbital Command Flying",
			135 => "Force Field",
			136 => "Warp Prism Phasing",
			137 => "Creep Tumor Burrowed",
			138 => "Creep Tumor Queen",
			139 => "Spine Crawler Uprooted",
			140 => "Spore Crawler Uprooted",
			141 => "Archon",
			142 => "Nydus Canal",
			143 => "Broodling Escort",
			144 => "Ghost Alternate",
			145 => "Ghost Nova",
			146 => "Rich Mineral Field",
			147 => "Rich Mineral Field 750",
			148 => "Ursadon",
			149 => "Xel Naga Tower",
			150 => "Infested Terrans Egg",
			151 => "Larva",
			152 => "Reaper Placeholder",
			153 => "Marine Ac Gluescreen Dummy",
			154 => "Firebat Ac Gluescreen Dummy",
			155 => "Medic Ac Gluescreen Dummy",
			156 => "Marauder Ac Gluescreen Dummy",
			157 => "Vulture Ac Gluescreen Dummy",
			158 => "Siege Tank Ac Gluescreen Dummy",
			159 => "Viking Ac Gluescreen Dummy",
			160 => "Banshee Ac Gluescreen Dummy",
			161 => "Battlecruiser Ac Gluescreen Dummy",
			162 => "Orbital Command Ac Gluescreen Dummy",
			163 => "Bunker Ac Gluescreen Dummy",
			164 => "Bunker Upgraded Ac Gluescreen Dummy",
			165 => "Missile Turret Ac Gluescreen Dummy",
			166 => "Hellbat Ac Gluescreen Dummy",
			167 => "Goliath Ac Gluescreen Dummy",
			168 => "Cyclone Ac Gluescreen Dummy",
			169 => "Wraith Ac Gluescreen Dummy",
			170 => "Science Vessel Ac Gluescreen Dummy",
			171 => "Hercules Ac Gluescreen Dummy",
			172 => "Thor Ac Gluescreen Dummy",
			173 => "Perdition Turret Ac Gluescreen Dummy",
			174 => "Flaming Betty Ac Gluescreen Dummy",
			175 => "Devastation Turret Ac Gluescreen Dummy",
			176 => "Blaster Billy Ac Gluescreen Dummy",
			177 => "Spinning Dizzy Ac Gluescreen Dummy",
			178 => "Zergling Kerrigan Ac Gluescreen Dummy",
			179 => "Raptor Ac Gluescreen Dummy",
			180 => "Queen Coop Ac Gluescreen Dummy",
			181 => "Hydralisk Ac Gluescreen Dummy",
			182 => "Hydralisk Lurker Ac Gluescreen Dummy",
			183 => "Mutalisk Broodlord Ac Gluescreen Dummy",
			184 => "Brood Lord Ac Gluescreen Dummy",
			185 => "Ultralisk Ac Gluescreen Dummy",
			186 => "Torrasque Ac Gluescreen Dummy",
			187 => "Overseer Ac Gluescreen Dummy",
			188 => "Lurker Ac Gluescreen Dummy",
			189 => "Spine Crawler Ac Gluescreen Dummy",
			190 => "Spore Crawler Ac Gluescreen Dummy",
			191 => "Nydus Network Ac Gluescreen Dummy",
			192 => "Omega Network Ac Gluescreen Dummy",
			193 => "Zergling Zagara Ac Gluescreen Dummy",
			194 => "Swarmling Ac Gluescreen Dummy",
			195 => "Baneling Ac Gluescreen Dummy",
			196 => "Splitterling Ac Gluescreen Dummy",
			197 => "Aberration Ac Gluescreen Dummy",
			198 => "Scourge Ac Gluescreen Dummy",
			199 => "Corruptor Ac Gluescreen Dummy",
			200 => "Bile Launcher Ac Gluescreen Dummy",
			201 => "Swarm Queen Ac Gluescreen Dummy",
			202 => "Roach Ac Gluescreen Dummy",
			203 => "Roach Vile Ac Gluescreen Dummy",
			204 => "Ravager Ac Gluescreen Dummy",
			205 => "Swarm Host Ac Gluescreen Dummy",
			206 => "Mutalisk Ac Gluescreen Dummy",
			207 => "Guardian Ac Gluescreen Dummy",
			208 => "Devourer Ac Gluescreen Dummy",
			209 => "Viper Ac Gluescreen Dummy",
			210 => "Brutalisk Ac Gluescreen Dummy",
			211 => "Leviathan Ac Gluescreen Dummy",
			212 => "Zealot Ac Gluescreen Dummy",
			213 => "Zealot Aiur Ac Gluescreen Dummy",
			214 => "Dragoon Ac Gluescreen Dummy",
			215 => "High Templar Ac Gluescreen Dummy",
			216 => "Archon Ac Gluescreen Dummy",
			217 => "Immortal Ac Gluescreen Dummy",
			218 => "Observer Ac Gluescreen Dummy",
			219 => "Phoenix Aiur Ac Gluescreen Dummy",
			220 => "Reaver Ac Gluescreen Dummy",
			221 => "Tempest Ac Gluescreen Dummy",
			222 => "Photon Cannon Ac Gluescreen Dummy",
			223 => "Zealot Vorazun Ac Gluescreen Dummy",
			224 => "Zealot Shakuras Ac Gluescreen Dummy",
			225 => "Stalker Shakuras Ac Gluescreen Dummy",
			226 => "Dark Templar Shakuras Ac Gluescreen Dummy",
			227 => "Corsair Ac Gluescreen Dummy",
			228 => "Void Ray Ac Gluescreen Dummy",
			229 => "Void Ray Shakuras Ac Gluescreen Dummy",
			230 => "Oracle Ac Gluescreen Dummy",
			231 => "Dark Archon Ac Gluescreen Dummy",
			232 => "Dark Pylon Ac Gluescreen Dummy",
			233 => "Zealot Purifier Ac Gluescreen Dummy",
			234 => "Sentry Purifier Ac Gluescreen Dummy",
			235 => "Immortal Karax Ac Gluescreen Dummy",
			236 => "Colossus Ac Gluescreen Dummy",
			237 => "Colossus Purifier Ac Gluescreen Dummy",
			238 => "Phoenix Purifier Ac Gluescreen Dummy",
			239 => "Carrier Ac Gluescreen Dummy",
			240 => "Carrier Aiur Ac Gluescreen Dummy",
			241 => "Khaydarin Monolith Ac Gluescreen Dummy",
			242 => "Shield Battery Ac Gluescreen Dummy",
			243 => "Elite Marine Ac Gluescreen Dummy",
			244 => "Marauder Commando Ac Gluescreen Dummy",
			245 => "Spec Ops Ghost Ac Gluescreen Dummy",
			246 => "Hellbat Ranger Ac Gluescreen Dummy",
			247 => "Strike Goliath Ac Gluescreen Dummy",
			248 => "Heavy Siege Tank Ac Gluescreen Dummy",
			249 => "Raid Liberator Ac Gluescreen Dummy",
			250 => "Raven Type Iiac Gluescreen Dummy",
			251 => "Covert Banshee Ac Gluescreen Dummy",
			252 => "Railgun Turret Ac Gluescreen Dummy",
			253 => "Black Ops Missile Turret Ac Gluescreen Dummy",
			254 => "Supplicant Ac Gluescreen Dummy",
			255 => "Stalker Taldarim Ac Gluescreen Dummy",
			256 => "Sentry Taldarim Ac Gluescreen Dummy",
			257 => "High Templar Taldarim Ac Gluescreen Dummy",
			258 => "Immortal Taldarim Ac Gluescreen Dummy",
			259 => "Colossus Taldarim Ac Gluescreen Dummy",
			260 => "Warp Prism Taldarim Ac Gluescreen Dummy",
			261 => "Photon Cannon Taldarim Ac Gluescreen Dummy",
			262 => "Needle Spines Weapon",
			263 => "Corruption Weapon",
			264 => "Infested Terrans Weapon",
			265 => "Neural Parasite Weapon",
			266 => "Point Defense Drone Release Weapon",
			267 => "Hunter Seeker Weapon",
			268 => "Mule",
			269 => "Thor Aa Weapon",
			270 => "Punisher Grenades Lm Weapon",
			271 => "Viking Fighter Weapon",
			272 => "Ata Laser Battery Lm Weapon",
			273 => "Ats Laser Battery Lm Weapon",
			274 => "Longbolt Missile Weapon",
			275 => "D 8 Charge Weapon",
			276 => "Yamato Weapon",
			277 => "Ion Cannons Weapon",
			278 => "Acid Saliva Weapon",
			279 => "Spine Crawler Weapon",
			280 => "Spore Crawler Weapon",
			281 => "Glaive Wurm Weapon",
			282 => "Glaive Wurm M 2 Weapon",
			283 => "Glaive Wurm M 3 Weapon",
			284 => "Stalker Weapon",
			285 => "Emp 2 Weapon",
			286 => "Backlash Rockets Lm Weapon",
			287 => "Photon Cannon Weapon",
			288 => "Parasite Spore Weapon",
			289 => "Broodling",
			290 => "Brood Lord B Weapon",
			291 => "Auto Turret Release Weapon",
			292 => "Larva Release Missile",
			293 => "Acid Spines Weapon",
			294 => "Frenzy Weapon",
			295 => "Contaminate Weapon",
			296 => "Beacon Rally",
			297 => "Beacon Army",
			298 => "Beacon Attack",
			299 => "Beacon Defend",
			300 => "Beacon Harass",
			301 => "Beacon Idle",
			302 => "Beacon Auto",
			303 => "Beacon Detect",
			304 => "Beacon Scout",
			305 => "Beacon Claim",
			306 => "Beacon Expand",
			307 => "Beacon Custom 1",
			308 => "Beacon Custom 2",
			309 => "Beacon Custom 3",
			310 => "Beacon Custom 4",
			311 => "Adept",
			312 => "Rocks 2 X 2 Non Conjoined",
			313 => "Fungal Growth Missile",
			314 => "Neural Parasite Tentacle Missile",
			315 => "Beacon Protoss",
			316 => "Beacon Protoss Small",
			317 => "Beacon Terran",
			318 => "Beacon Terran Small",
			319 => "Beacon Zerg",
			320 => "Beacon Zerg Small",
			321 => "Lyote",
			322 => "Carrion Bird",
			323 => "Karak Male",
			324 => "Karak Female",
			325 => "Ursadak Female Exotic",
			326 => "Ursadak Male",
			327 => "Ursadak Female",
			328 => "Ursadak Calf",
			329 => "Ursadak Male Exotic",
			330 => "Utility Bot",
			331 => "Commentator Bot 1",
			332 => "Commentator Bot 2",
			333 => "Commentator Bot 3",
			334 => "Commentator Bot 4",
			335 => "Scantipede",
			336 => "Dog",
			337 => "Sheep",
			338 => "Cow",
			339 => "Infested Terrans Egg Placement",
			340 => "Infestor Terrans Weapon",
			341 => "Mineral Field",
			342 => "Vespene Geyser",
			343 => "Space Platform Geyser",
			344 => "Rich Vespene Geyser",
			345 => "Destructible Searchlight",
			346 => "Destructible Bullhorn Lights",
			347 => "Destructible Streetlight",
			348 => "Destructible Space Platform Sign",
			349 => "Destructible Store Front City Props",
			350 => "Destructible Billboard Tall",
			351 => "Destructible Billboard Scrolling Text",
			352 => "Destructible Space Platform Barrier",
			353 => "Destructible Signs Directional",
			354 => "Destructible Signs Construction",
			355 => "Destructible Signs Funny",
			356 => "Destructible Signs Icons",
			357 => "Destructible Signs Warning",
			358 => "Destructible Garage",
			359 => "Destructible Garage Large",
			360 => "Destructible Traffic Signal",
			361 => "Traffic Signal",
			362 => "Braxis Alpha Destructible 1 X 1",
			363 => "Braxis Alpha Destructible 2 X 2",
			364 => "Destructible Debris 4 X 4",
			365 => "Destructible Debris 6 X 6",
			366 => "Destructible Rock 2 X 4 Vertical",
			367 => "Destructible Rock 2 X 4 Horizontal",
			368 => "Destructible Rock 2 X 6 Vertical",
			369 => "Destructible Rock 2 X 6 Horizontal",
			370 => "Destructible Rock 4 X 4",
			371 => "Destructible Rock 6 X 6",
			372 => "Destructible Ramp Diagonal Huge Ulbr",
			373 => "Destructible Ramp Diagonal Huge Blur",
			374 => "Destructible Ramp Vertical Huge",
			375 => "Destructible Ramp Horizontal Huge",
			376 => "Destructible Debris Ramp Diagonal Huge Ulbr",
			377 => "Destructible Debris Ramp Diagonal Huge Blur",
			378 => "Overlord Generate Creep Keybind",
			379 => "Mengsk Statue Alone",
			380 => "Mengsk Statue",
			381 => "Wolf Statue",
			382 => "Globe Statue",
			383 => "Weapon",
			384 => "Glaive Wurm Bounce Weapon",
			385 => "Brood Lord Weapon",
			386 => "Brood Lord A Weapon",
			387 => "Creep Blocker 1 X 1",
			388 => "Permanent Creep Blocker 1 X 1",
			389 => "Pathing Blocker 1 X 1",
			390 => "Pathing Blocker 2 X 2",
			391 => "Auto Test Attack Target Ground",
			392 => "Auto Test Attack Target Air",
			393 => "Auto Test Attacker",
			394 => "Helper Emitter Selection Arrow",
			395 => "Multi Kill Object",
			396 => "Shape Golfball",
			397 => "Shape Cone",
			398 => "Shape Cube",
			399 => "Shape Cylinder",
			400 => "Shape Dodecahedron",
			401 => "Shape Icosahedron",
			402 => "Shape Octahedron",
			403 => "Shape Pyramid",
			404 => "Shape Rounded Cube",
			405 => "Shape Sphere",
			406 => "Shape Tetrahedron",
			407 => "Shape Thick Torus",
			408 => "Shape Thin Torus",
			409 => "Shape Torus",
			410 => "Shape 4 Point Star",
			411 => "Shape 5 Point Star",
			412 => "Shape 6 Point Star",
			413 => "Shape 8 Point Star",
			414 => "Shape Arrow Pointer",
			415 => "Shape Bowl",
			416 => "Shape Box",
			417 => "Shape Capsule",
			418 => "Shape Crescent Moon",
			419 => "Shape Decahedron",
			420 => "Shape Diamond",
			421 => "Shape Football",
			422 => "Shape Gemstone",
			423 => "Shape Heart",
			424 => "Shape Jack",
			425 => "Shape Plus Sign",
			426 => "Shape Shamrock",
			427 => "Shape Spade",
			428 => "Shape Tube",
			429 => "Shape Egg",
			430 => "Shape Yen Sign",
			431 => "Shape X",
			432 => "Shape Watermelon",
			433 => "Shape Won Sign",
			434 => "Shape Tennisball",
			435 => "Shape Strawberry",
			436 => "Shape Smiley Face",
			437 => "Shape Soccerball",
			438 => "Shape Rainbow",
			439 => "Shape Sad Face",
			440 => "Shape Pound Sign",
			441 => "Shape Pear",
			442 => "Shape Pineapple",
			443 => "Shape Orange",
			444 => "Shape Peanut",
			445 => "Shape O",
			446 => "Shape Lemon",
			447 => "Shape Money Bag",
			448 => "Shape Horseshoe",
			449 => "Shape Hockey Stick",
			450 => "Shape Hockey Puck",
			451 => "Shape Hand",
			452 => "Shape Golf Club",
			453 => "Shape Grape",
			454 => "Shape Euro Sign",
			455 => "Shape Dollar Sign",
			456 => "Shape Basketball",
			457 => "Shape Carrot",
			458 => "Shape Cherry",
			459 => "Shape Baseball",
			460 => "Shape Baseball Bat",
			461 => "Shape Banana",
			462 => "Shape Apple",
			463 => "Shape Cash Large",
			464 => "Shape Cash Medium",
			465 => "Shape Cash Small",
			466 => "Shape Football Colored",
			467 => "Shape Lemon Small",
			468 => "Shape Orange Small",
			469 => "Shape Treasure Chest Open",
			470 => "Shape Treasure Chest Closed",
			471 => "Shape Watermelon Small",
			472 => "Unbuildable Rocks Destructible",
			473 => "Unbuildable Bricks Destructible",
			474 => "Unbuildable Plates Destructible",
			475 => "Debris 2 X 2 Non Conjoined",
			476 => "Enemy Pathing Blocker 1 X 1",
			477 => "Enemy Pathing Blocker 2 X 2",
			478 => "Enemy Pathing Blocker 4 X 4",
			479 => "Enemy Pathing Blocker 8 X 8",
			480 => "Enemy Pathing Blocker 16 X 16",
			481 => "Scope Test",
			482 => "Sentry Ac Gluescreen Dummy",
			483 => "Mineral Field 750",
			484 => "Hellion Tank",
			485 => "Collapsible Terran Tower Debris",
			486 => "Debris Ramp Left",
			487 => "Debris Ramp Right",
			488 => "Mothership Core",
			489 => "Locust Mp",
			490 => "Collapsible Rock Tower Debris",
			491 => "Nydus Canal Attacker",
			492 => "Nydus Canal Creeper",
			493 => "Swarm Host Burrowed Mp",
			494 => "Swarm Host Mp",
			495 => "Oracle",
			496 => "Tempest",
			497 => "War Hound",
			498 => "Widow Mine",
			499 => "Viper",
			500 => "Widow Mine Burrowed",
			501 => "Lurker Mp Egg",
			502 => "Lurker Mp",
			503 => "Lurker Mp Burrowed",
			504 => "Lurker Den Mp",
			505 => "Extending Bridge Ne Wide 8 Out",
			506 => "Extending Bridge Ne Wide 8",
			507 => "Extending Bridge Nw Wide 8 Out",
			508 => "Extending Bridge Nw Wide 8",
			509 => "Extending Bridge Ne Wide 10 Out",
			510 => "Extending Bridge Ne Wide 10",
			511 => "Extending Bridge Nw Wide 10 Out",
			512 => "Extending Bridge Nw Wide 10",
			513 => "Extending Bridge Ne Wide 12 Out",
			514 => "Extending Bridge Ne Wide 12",
			515 => "Extending Bridge Nw Wide 12 Out",
			516 => "Extending Bridge Nw Wide 12",
			517 => "Collapsible Rock Tower Debris Ramp Right",
			518 => "Collapsible Rock Tower Debris Ramp Left",
			519 => "Xel Naga Caverns Door E",
			520 => "Xel Naga Caverns Door E Opened",
			521 => "Xel Naga Caverns Door N",
			522 => "Xel Naga Caverns Door Ne",
			523 => "Xel Naga Caverns Door Ne Opened",
			524 => "Xel Naga Caverns Door N Opened",
			525 => "Xel Naga Caverns Door Nw",
			526 => "Xel Naga Caverns Door Nw Opened",
			527 => "Xel Naga Caverns Door S",
			528 => "Xel Naga Caverns Door Se",
			529 => "Xel Naga Caverns Door Se Opened",
			530 => "Xel Naga Caverns Door S Opened",
			531 => "Xel Naga Caverns Door Sw",
			532 => "Xel Naga Caverns Door Sw Opened",
			533 => "Xel Naga Caverns Door W",
			534 => "Xel Naga Caverns Door W Opened",
			535 => "Xel Naga Caverns Floating Bridge Ne 8 Out",
			536 => "Xel Naga Caverns Floating Bridge Ne 8",
			537 => "Xel Naga Caverns Floating Bridge Nw 8 Out",
			538 => "Xel Naga Caverns Floating Bridge Nw 8",
			539 => "Xel Naga Caverns Floating Bridge Ne 10 Out",
			540 => "Xel Naga Caverns Floating Bridge Ne 10",
			541 => "Xel Naga Caverns Floating Bridge Nw 10 Out",
			542 => "Xel Naga Caverns Floating Bridge Nw 10",
			543 => "Xel Naga Caverns Floating Bridge Ne 12 Out",
			544 => "Xel Naga Caverns Floating Bridge Ne 12",
			545 => "Xel Naga Caverns Floating Bridge Nw 12 Out",
			546 => "Xel Naga Caverns Floating Bridge Nw 12",
			547 => "Xel Naga Caverns Floating Bridge H 8 Out",
			548 => "Xel Naga Caverns Floating Bridge H 8",
			549 => "Xel Naga Caverns Floating Bridge V 8 Out",
			550 => "Xel Naga Caverns Floating Bridge V 8",
			551 => "Xel Naga Caverns Floating Bridge H 10 Out",
			552 => "Xel Naga Caverns Floating Bridge H 10",
			553 => "Xel Naga Caverns Floating Bridge V 10 Out",
			554 => "Xel Naga Caverns Floating Bridge V 10",
			555 => "Xel Naga Caverns Floating Bridge H 12 Out",
			556 => "Xel Naga Caverns Floating Bridge H 12",
			557 => "Xel Naga Caverns Floating Bridge V 12 Out",
			558 => "Xel Naga Caverns Floating Bridge V 12",
			559 => "Collapsible Terran Tower Push Unit Ramp Left",
			560 => "Collapsible Terran Tower Push Unit Ramp Right",
			561 => "Collapsible Rock Tower Push Unit",
			562 => "Collapsible Terran Tower Push Unit",
			563 => "Collapsible Rock Tower Push Unit Ramp Right",
			564 => "Collapsible Rock Tower Push Unit Ramp Left",
			565 => "Digester Creep Spray Target Unit",
			566 => "Digester Creep Spray Unit",
			567 => "Nydus Canal Attacker Weapon",
			568 => "Viper Consume Structure Weapon",
			569 => "Resource Blocker",
			570 => "Tempest Weapon",
			571 => "Yoink Missile",
			572 => "Yoink Viking Air Missile",
			573 => "Yoink Viking Ground Missile",
			574 => "Yoink Siege Tank Missile",
			575 => "War Hound Weapon",
			576 => "Eye Stalk Weapon",
			577 => "Widow Mine Weapon",
			578 => "Widow Mine Air Weapon",
			579 => "Mothership Core Weapon Weapon",
			580 => "Tornado Missile Weapon",
			581 => "Tornado Missile Dummy Weapon",
			582 => "Talons Missile Weapon",
			583 => "Creep Tumor Missile",
			584 => "Locust Mp Egg A Missile Weapon",
			585 => "Locust Mp Egg B Missile Weapon",
			586 => "Locust Mp Weapon",
			587 => "Repulsor Cannon Weapon",
			588 => "Collapsible Rock Tower Diagonal",
			589 => "Collapsible Terran Tower Diagonal",
			590 => "Collapsible Terran Tower Ramp Left",
			591 => "Collapsible Terran Tower Ramp Right",
			592 => "Ice 2 X 2 Non Conjoined",
			593 => "Ice Protoss Crates",
			594 => "Protoss Crates",
			595 => "Tower Mine",
			596 => "Pickup Pallet Gas",
			597 => "Pickup Pallet Minerals",
			598 => "Pickup Scrap Salvage 1 X 1",
			599 => "Pickup Scrap Salvage 2 X 2",
			600 => "Pickup Scrap Salvage 3 X 3",
			601 => "Rough Terrain",
			602 => "Unbuildable Bricks Small Unit",
			603 => "Unbuildable Plates Small Unit",
			604 => "Unbuildable Plates Unit",
			605 => "Unbuildable Rocks Small Unit",
			606 => "Xel Naga Healing Shrine",
			607 => "Invisible Target Dummy",
			608 => "Protoss Vespene Geyser",
			609 => "Collapsible Rock Tower",
			610 => "Collapsible Terran Tower",
			611 => "Thorn Lizard",
			612 => "Cleaning Bot",
			613 => "Destructible Rock 6 X 6 Weak",
			614 => "Protoss Snake Segment Demo",
			615 => "Physics Capsule",
			616 => "Physics Cube",
			617 => "Physics Cylinder",
			618 => "Physics Knot",
			619 => "Physics L",
			620 => "Physics Primitives",
			621 => "Physics Sphere",
			622 => "Physics Star",
			623 => "Creep Blocker 4 X 4",
			624 => "Destructible City Debris 2 X 4 Vertical",
			625 => "Destructible City Debris 2 X 4 Horizontal",
			626 => "Destructible City Debris 2 X 6 Vertical",
			627 => "Destructible City Debris 2 X 6 Horizontal",
			628 => "Destructible City Debris 4 X 4",
			629 => "Destructible City Debris 6 X 6",
			630 => "Destructible City Debris Huge Diagonal Blur",
			631 => "Destructible City Debris Huge Diagonal Ulbr",
			632 => "Test Zerg",
			633 => "Pathing Blocker Radius 1",
			634 => "Destructible Rock Ex 12 X 4 Vertical",
			635 => "Destructible Rock Ex 12 X 4 Horizontal",
			636 => "Destructible Rock Ex 12 X 6 Vertical",
			637 => "Destructible Rock Ex 12 X 6 Horizontal",
			638 => "Destructible Rock Ex 14 X 4",
			639 => "Destructible Rock Ex 16 X 6",
			640 => "Destructible Rock Ex 1 Diagonal Huge Ulbr",
			641 => "Destructible Rock Ex 1 Diagonal Huge Blur",
			642 => "Destructible Rock Ex 1 Vertical Huge",
			643 => "Destructible Rock Ex 1 Horizontal Huge",
			644 => "Destructible Ice 2 X 4 Vertical",
			645 => "Destructible Ice 2 X 4 Horizontal",
			646 => "Destructible Ice 2 X 6 Vertical",
			647 => "Destructible Ice 2 X 6 Horizontal",
			648 => "Destructible Ice 4 X 4",
			649 => "Destructible Ice 6 X 6",
			650 => "Destructible Ice Diagonal Huge Ulbr",
			651 => "Destructible Ice Diagonal Huge Blur",
			652 => "Destructible Ice Vertical Huge",
			653 => "Destructible Ice Horizontal Huge",
			654 => "Desert Planet Searchlight",
			655 => "Desert Planet Streetlight",
			656 => "Unbuildable Bricks Unit",
			657 => "Unbuildable Rocks Unit",
			658 => "Zerus Destructible Arch",
			659 => "Artosilope",
			660 => "Anteplott",
			661 => "Lab Bot",
			662 => "Crabeetle",
			663 => "Collapsible Rock Tower Ramp Right",
			664 => "Collapsible Rock Tower Ramp Left",
			665 => "Lab Mineral Field",
			666 => "Lab Mineral Field 750",
			667 => "Snow Refinery Terran Extending Bridge Ne Short 8 Out",
			668 => "Snow Refinery Terran Extending Bridge Ne Short 8",
			669 => "Snow Refinery Terran Extending Bridge Nw Short 8 Out",
			670 => "Snow Refinery Terran Extending Bridge Nw Short 8",
			671 => "Tarsonis Door N",
			672 => "Tarsonis Door N Lowered",
			673 => "Tarsonis Door Ne",
			674 => "Tarsonis Door Ne Lowered",
			675 => "Tarsonis Door E",
			676 => "Tarsonis Door E Lowered",
			677 => "Tarsonis Door Nw",
			678 => "Tarsonis Door Nw Lowered",
			679 => "Compound Mansion Door N",
			680 => "Compound Mansion Door N Lowered",
			681 => "Compound Mansion Door Ne",
			682 => "Compound Mansion Door Ne Lowered",
			683 => "Compound Mansion Door E",
			684 => "Compound Mansion Door E Lowered",
			685 => "Compound Mansion Door Nw",
			686 => "Compound Mansion Door Nw Lowered",
			687 => "Ravager Cocoon",
			688 => "Ravager",
			689 => "Liberator",
			690 => "Ravager Burrowed",
			691 => "Thor Ap",
			692 => "Cyclone",
			693 => "Locust Mp Flying",
			694 => "Disruptor",
			695 => "Aiur Light Bridge Ne 8 Out",
			696 => "Aiur Light Bridge Ne 8",
			697 => "Aiur Light Bridge Ne 10 Out",
			698 => "Aiur Light Bridge Ne 10",
			699 => "Aiur Light Bridge Ne 12 Out",
			700 => "Aiur Light Bridge Ne 12",
			701 => "Aiur Light Bridge Nw 8 Out",
			702 => "Aiur Light Bridge Nw 8",
			703 => "Aiur Light Bridge Nw 10 Out",
			704 => "Aiur Light Bridge Nw 10",
			705 => "Aiur Light Bridge Nw 12 Out",
			706 => "Aiur Light Bridge Nw 12",
			707 => "Aiur Temple Bridge Ne 8 Out",
			708 => "Aiur Temple Bridge Ne 10 Out",
			709 => "Aiur Temple Bridge Ne 12 Out",
			710 => "Aiur Temple Bridge Nw 8 Out",
			711 => "Aiur Temple Bridge Nw 10 Out",
			712 => "Aiur Temple Bridge Nw 12 Out",
			713 => "Shakuras Light Bridge Ne 8 Out",
			714 => "Shakuras Light Bridge Ne 8",
			715 => "Shakuras Light Bridge Ne 10 Out",
			716 => "Shakuras Light Bridge Ne 10",
			717 => "Shakuras Light Bridge Ne 12 Out",
			718 => "Shakuras Light Bridge Ne 12",
			719 => "Shakuras Light Bridge Nw 8 Out",
			720 => "Shakuras Light Bridge Nw 8",
			721 => "Shakuras Light Bridge Nw 10 Out",
			722 => "Shakuras Light Bridge Nw 10",
			723 => "Shakuras Light Bridge Nw 12 Out",
			724 => "Shakuras Light Bridge Nw 12",
			725 => "Void Mp Immortal Revive Corpse",
			726 => "Guardian Cocoon Mp",
			727 => "Guardian Mp",
			728 => "Devourer Cocoon Mp",
			729 => "Devourer Mp",
			730 => "Defiler Mp Burrowed",
			731 => "Defiler Mp",
			732 => "Oracle Stasis Trap",
			733 => "Disruptor Phased",
			734 => "Liberator Ag",
			735 => "Aiur Light Bridge Abandoned Ne 8 Out",
			736 => "Aiur Light Bridge Abandoned Ne 8",
			737 => "Aiur Light Bridge Abandoned Ne 10 Out",
			738 => "Aiur Light Bridge Abandoned Ne 10",
			739 => "Aiur Light Bridge Abandoned Ne 12 Out",
			740 => "Aiur Light Bridge Abandoned Ne 12",
			741 => "Aiur Light Bridge Abandoned Nw 8 Out",
			742 => "Aiur Light Bridge Abandoned Nw 8",
			743 => "Aiur Light Bridge Abandoned Nw 10 Out",
			744 => "Aiur Light Bridge Abandoned Nw 10",
			745 => "Aiur Light Bridge Abandoned Nw 12 Out",
			746 => "Aiur Light Bridge Abandoned Nw 12",
			747 => "Collapsible Purifier Tower Debris",
			748 => "Port City Bridge Unit Ne 8 Out",
			749 => "Port City Bridge Unit Ne 8",
			750 => "Port City Bridge Unit Se 8 Out",
			751 => "Port City Bridge Unit Se 8",
			752 => "Port City Bridge Unit Nw 8 Out",
			753 => "Port City Bridge Unit Nw 8",
			754 => "Port City Bridge Unit Sw 8 Out",
			755 => "Port City Bridge Unit Sw 8",
			756 => "Port City Bridge Unit Ne 10 Out",
			757 => "Port City Bridge Unit Ne 10",
			758 => "Port City Bridge Unit Se 10 Out",
			759 => "Port City Bridge Unit Se 10",
			760 => "Port City Bridge Unit Nw 10 Out",
			761 => "Port City Bridge Unit Nw 10",
			762 => "Port City Bridge Unit Sw 10 Out",
			763 => "Port City Bridge Unit Sw 10",
			764 => "Port City Bridge Unit Ne 12 Out",
			765 => "Port City Bridge Unit Ne 12",
			766 => "Port City Bridge Unit Se 12 Out",
			767 => "Port City Bridge Unit Se 12",
			768 => "Port City Bridge Unit Nw 12 Out",
			769 => "Port City Bridge Unit Nw 12",
			770 => "Port City Bridge Unit Sw 12 Out",
			771 => "Port City Bridge Unit Sw 12",
			772 => "Port City Bridge Unit N 8 Out",
			773 => "Port City Bridge Unit N 8",
			774 => "Port City Bridge Unit S 8 Out",
			775 => "Port City Bridge Unit S 8",
			776 => "Port City Bridge Unit E 8 Out",
			777 => "Port City Bridge Unit E 8",
			778 => "Port City Bridge Unit W 8 Out",
			779 => "Port City Bridge Unit W 8",
			780 => "Port City Bridge Unit N 10 Out",
			781 => "Port City Bridge Unit N 10",
			782 => "Port City Bridge Unit S 10 Out",
			783 => "Port City Bridge Unit S 10",
			784 => "Port City Bridge Unit E 10 Out",
			785 => "Port City Bridge Unit E 10",
			786 => "Port City Bridge Unit W 10 Out",
			787 => "Port City Bridge Unit W 10",
			788 => "Port City Bridge Unit N 12 Out",
			789 => "Port City Bridge Unit N 12",
			790 => "Port City Bridge Unit S 12 Out",
			791 => "Port City Bridge Unit S 12",
			792 => "Port City Bridge Unit E 12 Out",
			793 => "Port City Bridge Unit E 12",
			794 => "Port City Bridge Unit W 12 Out",
			795 => "Port City Bridge Unit W 12",
			796 => "Purifier Rich Mineral Field",
			797 => "Purifier Rich Mineral Field 750",
			798 => "Collapsible Purifier Tower Push Unit",
			799 => "Locust Mp Precursor",
			800 => "Release Interceptors Beacon",
			801 => "Adept Phase Shift",
			802 => "Ravager Corrosive Bile Missile",
			803 => "Hydralisk Impale Missile",
			804 => "Cyclone Missile Large Air",
			805 => "Cyclone Missile",
			806 => "Cyclone Missile Large",
			807 => "Thor Aa Lance",
			808 => "Oracle Weapon",
			809 => "Tempest Weapon Ground",
			810 => "Ravager Weapon Missile",
			811 => "Scout Mp Air Weapon Left",
			812 => "Scout Mp Air Weapon Right",
			813 => "Arbiter Mp Weapon Missile",
			814 => "Guardian Mp Weapon",
			815 => "Devourer Mp Weapon Missile",
			816 => "Defiler Mp Dark Swarm Weapon",
			817 => "Queen Mp Ensnare Missile",
			818 => "Queen Mp Spawn Broodlings Missile",
			819 => "Lightning Bomb Weapon",
			820 => "Herc Placement",
			821 => "Grapple Weapon",
			822 => "Caustic Spray Missile",
			823 => "Parasitic Bomb Missile",
			824 => "Parasitic Bomb Dummy",
			825 => "Adept Weapon",
			826 => "Adept Upgrade Weapon",
			827 => "Liberator Missile",
			828 => "Liberator Damage Missile",
			829 => "Liberator Ag Missile",
			830 => "Kd 8 Charge",
			831 => "Kd 8 Charge Weapon",
			832 => "Slayn Elemental Grab Weapon",
			833 => "Slayn Elemental Grab Air Unit",
			834 => "Slayn Elemental Grab Ground Unit",
			835 => "Slayn Elemental Weapon",
			836 => "Destructible Expedition Gate 6 X 6",
			837 => "Destructible Zerg Infestation 3 X 3",
			838 => "Herc",
			839 => "Moopy",
			840 => "Replicant",
			841 => "Seeker Missile",
			842 => "Aiur Temple Bridge Destructible Ne 8 Out",
			843 => "Aiur Temple Bridge Destructible Ne 10 Out",
			844 => "Aiur Temple Bridge Destructible Ne 12 Out",
			845 => "Aiur Temple Bridge Destructible Nw 8 Out",
			846 => "Aiur Temple Bridge Destructible Nw 10 Out",
			847 => "Aiur Temple Bridge Destructible Nw 12 Out",
			848 => "Aiur Temple Bridge Destructible Sw 8 Out",
			849 => "Aiur Temple Bridge Destructible Sw 10 Out",
			850 => "Aiur Temple Bridge Destructible Sw 12 Out",
			851 => "Aiur Temple Bridge Destructible Se 8 Out",
			852 => "Aiur Temple Bridge Destructible Se 10 Out",
			853 => "Aiur Temple Bridge Destructible Se 12 Out",
			854 => "Flyover Unit",
			855 => "Corsair Mp",
			856 => "Scout Mp",
			857 => "Arbiter Mp",
			858 => "Scourge Mp",
			859 => "Defiler Mp Plague Weapon",
			860 => "Queen Mp",
			861 => "Xel Naga Destructible Ramp Blocker 6 S",
			862 => "Xel Naga Destructible Ramp Blocker 6 Se",
			863 => "Xel Naga Destructible Ramp Blocker 6 E",
			864 => "Xel Naga Destructible Ramp Blocker 6 Ne",
			865 => "Xel Naga Destructible Ramp Blocker 6 N",
			866 => "Xel Naga Destructible Ramp Blocker 6 Nw",
			867 => "Xel Naga Destructible Ramp Blocker 6 W",
			868 => "Xel Naga Destructible Ramp Blocker 6 Sw",
			869 => "Xel Naga Destructible Ramp Blocker 8 S",
			870 => "Xel Naga Destructible Ramp Blocker 8 Se",
			871 => "Xel Naga Destructible Ramp Blocker 8 E",
			872 => "Xel Naga Destructible Ramp Blocker 8 Ne",
			873 => "Xel Naga Destructible Ramp Blocker 8 N",
			874 => "Xel Naga Destructible Ramp Blocker 8 Nw",
			875 => "Xel Naga Destructible Ramp Blocker 8 W",
			876 => "Xel Naga Destructible Ramp Blocker 8 Sw",
			877 => "Reptile Crate",
			878 => "Slayn Swarm Host Spawn Flyer",
			879 => "Slayn Elemental",
			880 => "Purifier Vespene Geyser",
			881 => "Shakuras Vespene Geyser",
			882 => "Collapsible Purifier Tower Diagonal",
			883 => "Creep Only Blocker 4 X 4",
			884 => "Purifier Mineral Field",
			885 => "Purifier Mineral Field 750",
			886 => "Battle Station Mineral Field",
			887 => "Battle Station Mineral Field 750",
			888 => "Beacon Nova",
			889 => "Beacon Nova Small",
			890 => "Ursula",
			891 => "Elsecaro Colonist Hut",
			892 => "Transport Overlord Cocoon",
			893 => "Overlord Transport",
			894 => "Pylon Overcharged",
			895 => "Bypass Armor Drone",
			896 => "Adept Piercing Weapon",
			897 => "Corrosive Parasite Weapon",
			1843 => "Queen Zagara Ac Gluescreen Dummy",
			1844 => "Overseer Zagara Ac Gluescreen Dummy",
			1845 => "Stukov Infested Civilian Ac Gluescreen Dummy",
			1846 => "Stukov Infested Marine Ac Gluescreen Dummy",
			1847 => "Stukov Infested Siege Tank Ac Gluescreen Dummy",
			1848 => "Stukov Infested Diamondback Ac Gluescreen Dummy",
			1849 => "Stukov Infested Banshee Ac Gluescreen Dummy",
			1850 => "Si Liberator Ac Gluescreen Dummy",
			1851 => "Stukov Infested Bunker Ac Gluescreen Dummy",
			1852 => "Stukov Infested Missile Turret Ac Gluescreen Dummy",
			1853 => "Stukov Brood Queen Ac Gluescreen Dummy",
			1854 => "Zealot Fenix Ac Gluescreen Dummy",
			1855 => "Sentry Fenix Ac Gluescreen Dummy",
			1856 => "Adept Fenix Ac Gluescreen Dummy",
			1857 => "Immortal Fenix Ac Gluescreen Dummy",
			1858 => "Colossus Fenix Ac Gluescreen Dummy",
			1859 => "Disruptor Ac Gluescreen Dummy",
			1860 => "Observer Fenix Ac Gluescreen Dummy",
			1861 => "Scout Ac Gluescreen Dummy",
			1862 => "Carrier Fenix Ac Gluescreen Dummy",
			1863 => "Photon Cannon Fenix Ac Gluescreen Dummy",
			1864 => "Primal Zergling Ac Gluescreen Dummy",
			1865 => "Ravasaur Ac Gluescreen Dummy",
			1866 => "Primal Roach Ac Gluescreen Dummy",
			1867 => "Fire Roach Ac Gluescreen Dummy",
			1868 => "Primal Guardian Ac Gluescreen Dummy",
			1869 => "Primal Hydralisk Ac Gluescreen Dummy",
			1870 => "Primal Mutalisk Ac Gluescreen Dummy",
			1871 => "Primal Impaler Ac Gluescreen Dummy",
			1872 => "Primal Swarm Host Ac Gluescreen Dummy",
			1873 => "Creeper Host Ac Gluescreen Dummy",
			1874 => "Primal Ultralisk Ac Gluescreen Dummy",
			1875 => "Tyrannozor Ac Gluescreen Dummy",
			1876 => "Primal Wurm Ac Gluescreen Dummy",
			1877 => "Hh Reaper Ac Gluescreen Dummy",
			1878 => "Hh Widow Mine Ac Gluescreen Dummy",
			1879 => "Hh Hellion Tank Ac Gluescreen Dummy",
			1880 => "Hh Wraith Ac Gluescreen Dummy",
			1881 => "Hh Viking Ac Gluescreen Dummy",
			1882 => "Hh Battlecruiser Ac Gluescreen Dummy",
			1883 => "Hh Raven Ac Gluescreen Dummy",
			1884 => "Hh Bomber Platform Ac Gluescreen Dummy",
			1885 => "Hh Merc Starport Ac Gluescreen Dummy",
			1886 => "Hh Missile Turret Ac Gluescreen Dummy",
			1887 => "High Templar Skin Preview",
			1888 => "Warp Prism Skin Preview",
			1889 => "Siege Tank Skin Preview",
			1890 => "Liberator Skin Preview",
			1892 => "Stukov Infested Trooper Ac Gluescreen Dummy",
			1893 => "Xel Naga Destructible Blocker 6 S",
			1894 => "Xel Naga Destructible Blocker 6 Se",
			1895 => "Xel Naga Destructible Blocker 6 E",
			1896 => "Xel Naga Destructible Blocker 6 Ne",
			1897 => "Xel Naga Destructible Blocker 6 N",
			1898 => "Xel Naga Destructible Blocker 6 Nw",
			1899 => "Xel Naga Destructible Blocker 6 W",
			1900 => "Xel Naga Destructible Blocker 6 Sw",
			1901 => "Xel Naga Destructible Blocker 8 S",
			1902 => "Xel Naga Destructible Blocker 8 Se",
			1903 => "Xel Naga Destructible Blocker 8 E",
			1904 => "Xel Naga Destructible Blocker 8 Ne",
			1905 => "Xel Naga Destructible Blocker 8 N",
			1906 => "Xel Naga Destructible Blocker 8 Nw",
			1907 => "Xel Naga Destructible Blocker 8 W",
			1908 => "Xel Naga Destructible Blocker 8 Sw",
			1909 => "Snow Glaze Starter Mp",
			1910 => "Shield Battery",
			1911 => "Observer Siege Mode",
			1912 => "Overseer Siege Mode",
			1913 => "Raven Repair Drone",
			1914 => "High Templar Weapon Missile",
			1915 => "Cyclone Missile Large Air Alternative",
			1916 => "Raven Scrambler Missile",
			1917 => "Raven Repair Drone Release Weapon",
			1918 => "Raven Shredder Missile Weapon",
			1919 => "Infested Acid Spines Weapon",
			1920 => "Infestor Ensnare Attack Missile",
			1921 => "Snare Placeholder",
			1922 => "Tychus Reaper Ac Gluescreen Dummy",
			1923 => "Tychus Firebat Ac Gluescreen Dummy",
			1924 => "Tychus Spectre Ac Gluescreen Dummy",
			1925 => "Tychus Medic Ac Gluescreen Dummy",
			1926 => "Tychus Marauder Ac Gluescreen Dummy",
			1927 => "Tychus Warhound Ac Gluescreen Dummy",
			1928 => "Tychus Hercac Gluescreen Dummy",
			1929 => "Tychus Ghost Ac Gluescreen Dummy",
			1930 => "Tychus Scv Auto Turret Ac Gluescreen Dummy",
			1931 => "Zeratul Stalker Ac Gluescreen Dummy",
			1932 => "Zeratul Sentry Ac Gluescreen Dummy",
			1933 => "Zeratul Dark Templar Ac Gluescreen Dummy",
			1934 => "Zeratul Immortal Ac Gluescreen Dummy",
			1935 => "Zeratul Observer Ac Gluescreen Dummy",
			1936 => "Zeratul Disruptor Ac Gluescreen Dummy",
			1937 => "Zeratul Warp Prism Ac Gluescreen Dummy",
			1938 => "Zeratul Photon Cannon Ac Gluescreen Dummy",
			1939 => "Renegade Longbolt Missile Weapon",
			1940 => "Viking",
			1941 => "Renegade Missile Turret",
			1942 => "Parasitic Bomb Relay Dummy",
			1943 => "Refinery Rich",
			1981 => "Preview Bunker Upgraded",
			1982 => "Inhibitor Zone Small",
			1983 => "Inhibitor Zone Medium",
			1984 => "Inhibitor Zone Large",
			1985 => "Acceleration Zone Small",
			1986 => "Acceleration Zone Medium",
			1987 => "Acceleration Zone Large",
			1988 => "Acceleration Zone Flying Small",
			1989 => "Acceleration Zone Flying Medium",
			1990 => "Acceleration Zone Flying Large",
			1991 => "Inhibitor Zone Flying Small",
			1992 => "Inhibitor Zone Flying Medium",
			1993 => "Inhibitor Zone Flying Large",
			1994 => "Assimilator Rich",
			1995 => "Extractor Rich",
			1996 => "Mineral Field 450",
			1997 => "Mineral Field Opaque",
			1998 => "Mineral Field Opaque 900",
			1999 => "Mecha Zergling Ac Gluescreen Dummy",
			2000 => "Mecha Baneling Ac Gluescreen Dummy",
			2001 => "Mecha Hydralisk Ac Gluescreen Dummy",
			2002 => "Mecha Infestor Ac Gluescreen Dummy",
			2003 => "Mecha Corruptor Ac Gluescreen Dummy",
			2004 => "Mecha Ultralisk Ac Gluescreen Dummy",
			2005 => "Mecha Overseer Ac Gluescreen Dummy",
			2006 => "Mecha Lurker Ac Gluescreen Dummy",
			2007 => "Mecha Battlecarrier Lord Ac Gluescreen Dummy",
			2008 => "Mecha Spine Crawler Ac Gluescreen Dummy",
			2009 => "Mecha Spore Crawler Ac Gluescreen Dummy",
			2010 => "Trooper Mengsk Ac Gluescreen Dummy",
			2011 => "Medivac Mengsk Ac Gluescreen Dummy",
			2012 => "Blimp Mengsk Ac Gluescreen Dummy",
			2013 => "Marauder Mengsk Ac Gluescreen Dummy",
			2014 => "Ghost Mengsk Ac Gluescreen Dummy",
			2015 => "Siege Tank Mengsk Ac Gluescreen Dummy",
			2016 => "Thor Mengsk Ac Gluescreen Dummy",
			2017 => "Viking Mengsk Ac Gluescreen Dummy",
			2018 => "Battlecruiser Mengsk Ac Gluescreen Dummy",
			2019 => "Bunker Depot Mengsk Ac Gluescreen Dummy",
			2020 => "Missile Turret Mengsk Ac Gluescreen Dummy",
			2021 => "Artillery Mengsk Ac Gluescreen Dummy",
			2022 => "Load Out Spray 1",
			2023 => "Load Out Spray 2",
			2024 => "Load Out Spray 3",
			2025 => "Load Out Spray 4",
			2026 => "Load Out Spray 5",
			2027 => "Load Out Spray 6",
			2028 => "Load Out Spray 7",
			2029 => "Load Out Spray 8",
			2030 => "Load Out Spray 9",
			2031 => "Load Out Spray 10",
			2032 => "Load Out Spray 11",
			2033 => "Load Out Spray 12",
			2034 => "Load Out Spray 13",
			2035 => "Load Out Spray 14",
			2036 => "Collapsible Rock Tower Debris Ramp Left Green",
			2037 => "Collapsible Rock Tower Debris Ramp Right Green",
			2038 => "Collapsible Rock Tower Push Unit Ramp Left Green",
			2039 => "Collapsible Rock Tower Push Unit Ramp Right Green",
			2040 => "Collapsible Rock Tower Ramp Left Green",
			2041 => "Collapsible Rock Tower Ramp Right Green",
			_ => return write!(f, "{self:?}"),
		};
		write!(f, "{s}")
	}
}
impl From<u32> for UnitKind {
	fn from(n: u32) -> Self {
		Self(n)
	}
}
impl From<UnitKind> for u32 {
	fn from(id: UnitKind) -> Self {
		id.0
	}
}
