use std::fmt;

#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct UnitKind(pub u32);
impl UnitKind {
	pub const NONE: Self = Self(0);
	pub const BALL: Self = Self(2);
	pub const STEREOSCOPIC_OPTIONS_UNIT: Self = Self(3);
	pub const COLOSSUS: Self = Self(4);
	pub const TECH_LAB: Self = Self(5);
	pub const REACTOR: Self = Self(6);
	pub const INFESTOR_TERRAN: Self = Self(7);
	pub const BANELING_COCOON: Self = Self(8);
	pub const BANELING: Self = Self(9);
	pub const MOTHERSHIP: Self = Self(10);
	pub const POINT_DEFENSE_DRONE: Self = Self(11);
	pub const CHANGELING: Self = Self(12);
	pub const CHANGELING_ZEALOT: Self = Self(13);
	pub const CHANGELING_MARINE_SHIELD: Self = Self(14);
	pub const CHANGELING_MARINE: Self = Self(15);
	pub const CHANGELING_ZERGLING_WINGS: Self = Self(16);
	pub const CHANGELING_ZERGLING: Self = Self(17);
	pub const COMMAND_CENTER: Self = Self(18);
	pub const SUPPLY_DEPOT: Self = Self(19);
	pub const REFINERY: Self = Self(20);
	pub const BARRACKS: Self = Self(21);
	pub const ENGINEERING_BAY: Self = Self(22);
	pub const MISSILE_TURRET: Self = Self(23);
	pub const BUNKER: Self = Self(24);
	pub const SENSOR_TOWER: Self = Self(25);
	pub const GHOST_ACADEMY: Self = Self(26);
	pub const FACTORY: Self = Self(27);
	pub const STARPORT: Self = Self(28);
	pub const ARMORY: Self = Self(29);
	pub const FUSION_CORE: Self = Self(30);
	pub const AUTO_TURRET: Self = Self(31);
	pub const SIEGE_TANK_SIEGED: Self = Self(32);
	pub const SIEGE_TANK: Self = Self(33);
	pub const VIKING_ASSAULT: Self = Self(34);
	pub const VIKING_FIGHTER: Self = Self(35);
	pub const COMMAND_CENTER_FLYING: Self = Self(36);
	pub const BARRACKS_TECH_LAB: Self = Self(37);
	pub const BARRACKS_REACTOR: Self = Self(38);
	pub const FACTORY_TECH_LAB: Self = Self(39);
	pub const FACTORY_REACTOR: Self = Self(40);
	pub const STARPORT_TECH_LAB: Self = Self(41);
	pub const STARPORT_REACTOR: Self = Self(42);
	pub const FACTORY_FLYING: Self = Self(43);
	pub const STARPORT_FLYING: Self = Self(44);
	pub const SCV: Self = Self(45);
	pub const BARRACKS_FLYING: Self = Self(46);
	pub const SUPPLY_DEPOT_LOWERED: Self = Self(47);
	pub const MARINE: Self = Self(48);
	pub const REAPER: Self = Self(49);
	pub const GHOST: Self = Self(50);
	pub const MARAUDER: Self = Self(51);
	pub const THOR: Self = Self(52);
	pub const HELLION: Self = Self(53);
	pub const MEDIVAC: Self = Self(54);
	pub const BANSHEE: Self = Self(55);
	pub const RAVEN: Self = Self(56);
	pub const BATTLECRUISER: Self = Self(57);
	pub const NUKE: Self = Self(58);
	pub const NEXUS: Self = Self(59);
	pub const PYLON: Self = Self(60);
	pub const ASSIMILATOR: Self = Self(61);
	pub const GATEWAY: Self = Self(62);
	pub const FORGE: Self = Self(63);
	pub const FLEET_BEACON: Self = Self(64);
	pub const TWILIGHT_COUNCIL: Self = Self(65);
	pub const PHOTON_CANNON: Self = Self(66);
	pub const STARGATE: Self = Self(67);
	pub const TEMPLAR_ARCHIVE: Self = Self(68);
	pub const DARK_SHRINE: Self = Self(69);
	pub const ROBOTICS_BAY: Self = Self(70);
	pub const ROBOTICS_FACILITY: Self = Self(71);
	pub const CYBERNETICS_CORE: Self = Self(72);
	pub const ZEALOT: Self = Self(73);
	pub const STALKER: Self = Self(74);
	pub const HIGH_TEMPLAR: Self = Self(75);
	pub const DARK_TEMPLAR: Self = Self(76);
	pub const SENTRY: Self = Self(77);
	pub const PHOENIX: Self = Self(78);
	pub const CARRIER: Self = Self(79);
	pub const VOID_RAY: Self = Self(80);
	pub const WARP_PRISM: Self = Self(81);
	pub const OBSERVER: Self = Self(82);
	pub const IMMORTAL: Self = Self(83);
	pub const PROBE: Self = Self(84);
	pub const INTERCEPTOR: Self = Self(85);
	pub const HATCHERY: Self = Self(86);
	pub const CREEP_TUMOR: Self = Self(87);
	pub const EXTRACTOR: Self = Self(88);
	pub const SPAWNING_POOL: Self = Self(89);
	pub const EVOLUTION_CHAMBER: Self = Self(90);
	pub const HYDRALISK_DEN: Self = Self(91);
	pub const SPIRE: Self = Self(92);
	pub const ULTRALISK_CAVERN: Self = Self(93);
	pub const INFESTATION_PIT: Self = Self(94);
	pub const NYDUS_NETWORK: Self = Self(95);
	pub const BANELING_NEST: Self = Self(96);
	pub const ROACH_WARREN: Self = Self(97);
	pub const SPINE_CRAWLER: Self = Self(98);
	pub const SPORE_CRAWLER: Self = Self(99);
	pub const LAIR: Self = Self(100);
	pub const HIVE: Self = Self(101);
	pub const GREATER_SPIRE: Self = Self(102);
	pub const EGG: Self = Self(103);
	pub const DRONE: Self = Self(104);
	pub const ZERGLING: Self = Self(105);
	pub const OVERLORD: Self = Self(106);
	pub const HYDRALISK: Self = Self(107);
	pub const MUTALISK: Self = Self(108);
	pub const ULTRALISK: Self = Self(109);
	pub const ROACH: Self = Self(110);
	pub const INFESTOR: Self = Self(111);
	pub const CORRUPTOR: Self = Self(112);
	pub const BROOD_LORD_COCOON: Self = Self(113);
	pub const BROOD_LORD: Self = Self(114);
	pub const BANELING_BURROWED: Self = Self(115);
	pub const DRONE_BURROWED: Self = Self(116);
	pub const HYDRALISK_BURROWED: Self = Self(117);
	pub const ROACH_BURROWED: Self = Self(118);
	pub const ZERGLING_BURROWED: Self = Self(119);
	pub const INFESTOR_TERRAN_BURROWED: Self = Self(120);
	pub const REDSTONE_LAVA_CRITTER_BURROWED: Self = Self(121);
	pub const REDSTONE_LAVA_CRITTER_INJURED_BURROWED: Self = Self(122);
	pub const REDSTONE_LAVA_CRITTER: Self = Self(123);
	pub const REDSTONE_LAVA_CRITTER_INJURED: Self = Self(124);
	pub const QUEEN_BURROWED: Self = Self(125);
	pub const QUEEN: Self = Self(126);
	pub const INFESTOR_BURROWED: Self = Self(127);
	pub const OVERLORD_COCOON: Self = Self(128);
	pub const OVERSEER: Self = Self(129);
	pub const PLANETARY_FORTRESS: Self = Self(130);
	pub const ULTRALISK_BURROWED: Self = Self(131);
	pub const ORBITAL_COMMAND: Self = Self(132);
	pub const WARP_GATE: Self = Self(133);
	pub const ORBITAL_COMMAND_FLYING: Self = Self(134);
	pub const FORCE_FIELD: Self = Self(135);
	pub const WARP_PRISM_PHASING: Self = Self(136);
	pub const CREEP_TUMOR_BURROWED: Self = Self(137);
	pub const CREEP_TUMOR_QUEEN: Self = Self(138);
	pub const SPINE_CRAWLER_UPROOTED: Self = Self(139);
	pub const SPORE_CRAWLER_UPROOTED: Self = Self(140);
	pub const ARCHON: Self = Self(141);
	pub const NYDUS_CANAL: Self = Self(142);
	pub const BROODLING_ESCORT: Self = Self(143);
	pub const GHOST_ALTERNATE: Self = Self(144);
	pub const GHOST_NOVA: Self = Self(145);
	pub const RICH_MINERAL_FIELD: Self = Self(146);
	pub const RICH_MINERAL_FIELD_750: Self = Self(147);
	pub const URSADON: Self = Self(148);
	pub const XEL_NAGA_TOWER: Self = Self(149);
	pub const INFESTED_TERRANS_EGG: Self = Self(150);
	pub const LARVA: Self = Self(151);
	pub const REAPER_PLACEHOLDER: Self = Self(152);
	pub const MULE: Self = Self(268);
	pub const BROODLING: Self = Self(289);
	pub const BEACON_RALLY: Self = Self(296);
	pub const BEACON_ARMY: Self = Self(297);
	pub const BEACON_ATTACK: Self = Self(298);
	pub const BEACON_DEFEND: Self = Self(299);
	pub const BEACON_HARASS: Self = Self(300);
	pub const BEACON_IDLE: Self = Self(301);
	pub const BEACON_AUTO: Self = Self(302);
	pub const BEACON_DETECT: Self = Self(303);
	pub const BEACON_SCOUT: Self = Self(304);
	pub const BEACON_CLAIM: Self = Self(305);
	pub const BEACON_EXPAND: Self = Self(306);
	pub const BEACON_CUSTOM_1: Self = Self(307);
	pub const BEACON_CUSTOM_2: Self = Self(308);
	pub const BEACON_CUSTOM_3: Self = Self(309);
	pub const BEACON_CUSTOM_4: Self = Self(310);
	pub const ADEPT: Self = Self(311);
	pub const ROCKS_2_X_2_NON_CONJOINED: Self = Self(312);
	pub const BEACON_PROTOSS: Self = Self(315);
	pub const BEACON_PROTOSS_SMALL: Self = Self(316);
	pub const BEACON_TERRAN: Self = Self(317);
	pub const BEACON_TERRAN_SMALL: Self = Self(318);
	pub const BEACON_ZERG: Self = Self(319);
	pub const BEACON_ZERG_SMALL: Self = Self(320);
	pub const LYOTE: Self = Self(321);
	pub const CARRION_BIRD: Self = Self(322);
	pub const KARAK_MALE: Self = Self(323);
	pub const KARAK_FEMALE: Self = Self(324);
	pub const URSADAK_FEMALE_EXOTIC: Self = Self(325);
	pub const URSADAK_MALE: Self = Self(326);
	pub const URSADAK_FEMALE: Self = Self(327);
	pub const URSADAK_CALF: Self = Self(328);
	pub const URSADAK_MALE_EXOTIC: Self = Self(329);
	pub const UTILITY_BOT: Self = Self(330);
	pub const COMMENTATOR_BOT_1: Self = Self(331);
	pub const COMMENTATOR_BOT_2: Self = Self(332);
	pub const COMMENTATOR_BOT_3: Self = Self(333);
	pub const COMMENTATOR_BOT_4: Self = Self(334);
	pub const SCANTIPEDE: Self = Self(335);
	pub const DOG: Self = Self(336);
	pub const SHEEP: Self = Self(337);
	pub const COW: Self = Self(338);
	pub const INFESTED_TERRANS_EGG_PLACEMENT: Self = Self(339);
	pub const MINERAL_FIELD: Self = Self(341);
	pub const VESPENE_GEYSER: Self = Self(342);
	pub const SPACE_PLATFORM_GEYSER: Self = Self(343);
	pub const RICH_VESPENE_GEYSER: Self = Self(344);
	pub const DESTRUCTIBLE_SEARCHLIGHT: Self = Self(345);
	pub const DESTRUCTIBLE_BULLHORN_LIGHTS: Self = Self(346);
	pub const DESTRUCTIBLE_STREETLIGHT: Self = Self(347);
	pub const DESTRUCTIBLE_SPACE_PLATFORM_SIGN: Self = Self(348);
	pub const DESTRUCTIBLE_STORE_FRONT_CITY_PROPS: Self = Self(349);
	pub const DESTRUCTIBLE_BILLBOARD_TALL: Self = Self(350);
	pub const DESTRUCTIBLE_BILLBOARD_SCROLLING_TEXT: Self = Self(351);
	pub const DESTRUCTIBLE_SPACE_PLATFORM_BARRIER: Self = Self(352);
	pub const DESTRUCTIBLE_SIGNS_DIRECTIONAL: Self = Self(353);
	pub const DESTRUCTIBLE_SIGNS_CONSTRUCTION: Self = Self(354);
	pub const DESTRUCTIBLE_SIGNS_FUNNY: Self = Self(355);
	pub const DESTRUCTIBLE_SIGNS_ICONS: Self = Self(356);
	pub const DESTRUCTIBLE_SIGNS_WARNING: Self = Self(357);
	pub const DESTRUCTIBLE_GARAGE: Self = Self(358);
	pub const DESTRUCTIBLE_GARAGE_LARGE: Self = Self(359);
	pub const DESTRUCTIBLE_TRAFFIC_SIGNAL: Self = Self(360);
	pub const TRAFFIC_SIGNAL: Self = Self(361);
	pub const BRAXIS_ALPHA_DESTRUCTIBLE_1_X_1: Self = Self(362);
	pub const BRAXIS_ALPHA_DESTRUCTIBLE_2_X_2: Self = Self(363);
	pub const DESTRUCTIBLE_DEBRIS_4_X_4: Self = Self(364);
	pub const DESTRUCTIBLE_DEBRIS_6_X_6: Self = Self(365);
	pub const DESTRUCTIBLE_ROCK_2_X_4_VERTICAL: Self = Self(366);
	pub const DESTRUCTIBLE_ROCK_2_X_4_HORIZONTAL: Self = Self(367);
	pub const DESTRUCTIBLE_ROCK_2_X_6_VERTICAL: Self = Self(368);
	pub const DESTRUCTIBLE_ROCK_2_X_6_HORIZONTAL: Self = Self(369);
	pub const DESTRUCTIBLE_ROCK_4_X_4: Self = Self(370);
	pub const DESTRUCTIBLE_ROCK_6_X_6: Self = Self(371);
	pub const DESTRUCTIBLE_RAMP_DIAGONAL_HUGE_ULBR: Self = Self(372);
	pub const DESTRUCTIBLE_RAMP_DIAGONAL_HUGE_BLUR: Self = Self(373);
	pub const DESTRUCTIBLE_RAMP_VERTICAL_HUGE: Self = Self(374);
	pub const DESTRUCTIBLE_RAMP_HORIZONTAL_HUGE: Self = Self(375);
	pub const DESTRUCTIBLE_DEBRIS_RAMP_DIAGONAL_HUGE_ULBR: Self = Self(376);
	pub const DESTRUCTIBLE_DEBRIS_RAMP_DIAGONAL_HUGE_BLUR: Self = Self(377);
	pub const OVERLORD_GENERATE_CREEP_KEYBIND: Self = Self(378);
	pub const MENGSK_STATUE_ALONE: Self = Self(379);
	pub const MENGSK_STATUE: Self = Self(380);
	pub const WOLF_STATUE: Self = Self(381);
	pub const GLOBE_STATUE: Self = Self(382);
	pub const CREEP_BLOCKER_1_X_1: Self = Self(387);
	pub const PERMANENT_CREEP_BLOCKER_1_X_1: Self = Self(388);
	pub const PATHING_BLOCKER_1_X_1: Self = Self(389);
	pub const PATHING_BLOCKER_2_X_2: Self = Self(390);
	pub const AUTO_TEST_ATTACK_TARGET_GROUND: Self = Self(391);
	pub const AUTO_TEST_ATTACK_TARGET_AIR: Self = Self(392);
	pub const AUTO_TEST_ATTACKER: Self = Self(393);
	pub const HELPER_EMITTER_SELECTION_ARROW: Self = Self(394);
	pub const MULTI_KILL_OBJECT: Self = Self(395);
	pub const UNBUILDABLE_ROCKS_DESTRUCTIBLE: Self = Self(472);
	pub const UNBUILDABLE_BRICKS_DESTRUCTIBLE: Self = Self(473);
	pub const UNBUILDABLE_PLATES_DESTRUCTIBLE: Self = Self(474);
	pub const DEBRIS_2_X_2_NON_CONJOINED: Self = Self(475);
	pub const ENEMY_PATHING_BLOCKER_1_X_1: Self = Self(476);
	pub const ENEMY_PATHING_BLOCKER_2_X_2: Self = Self(477);
	pub const ENEMY_PATHING_BLOCKER_4_X_4: Self = Self(478);
	pub const ENEMY_PATHING_BLOCKER_8_X_8: Self = Self(479);
	pub const ENEMY_PATHING_BLOCKER_16_X_16: Self = Self(480);
	pub const SCOPE_TEST: Self = Self(481);
	pub const MINERAL_FIELD_750: Self = Self(483);
	pub const HELLION_TANK: Self = Self(484);
	pub const COLLAPSIBLE_TERRAN_TOWER_DEBRIS: Self = Self(485);
	pub const DEBRIS_RAMP_LEFT: Self = Self(486);
	pub const DEBRIS_RAMP_RIGHT: Self = Self(487);
	pub const MOTHERSHIP_CORE: Self = Self(488);
	pub const LOCUST_MP: Self = Self(489);
	pub const COLLAPSIBLE_ROCK_TOWER_DEBRIS: Self = Self(490);
	pub const NYDUS_CANAL_ATTACKER: Self = Self(491);
	pub const NYDUS_CANAL_CREEPER: Self = Self(492);
	pub const SWARM_HOST_BURROWED_MP: Self = Self(493);
	pub const SWARM_HOST_MP: Self = Self(494);
	pub const ORACLE: Self = Self(495);
	pub const TEMPEST: Self = Self(496);
	pub const WAR_HOUND: Self = Self(497);
	pub const WIDOW_MINE: Self = Self(498);
	pub const VIPER: Self = Self(499);
	pub const WIDOW_MINE_BURROWED: Self = Self(500);
	pub const LURKER_MP_EGG: Self = Self(501);
	pub const LURKER_MP: Self = Self(502);
	pub const LURKER_MP_BURROWED: Self = Self(503);
	pub const LURKER_DEN_MP: Self = Self(504);
	pub const COLLAPSIBLE_ROCK_TOWER_DEBRIS_RAMP_RIGHT: Self = Self(517);
	pub const COLLAPSIBLE_ROCK_TOWER_DEBRIS_RAMP_LEFT: Self = Self(518);
	pub const COLLAPSIBLE_TERRAN_TOWER_PUSH_UNIT_RAMP_LEFT: Self = Self(559);
	pub const COLLAPSIBLE_TERRAN_TOWER_PUSH_UNIT_RAMP_RIGHT: Self = Self(560);
	pub const COLLAPSIBLE_ROCK_TOWER_PUSH_UNIT: Self = Self(561);
	pub const COLLAPSIBLE_TERRAN_TOWER_PUSH_UNIT: Self = Self(562);
	pub const COLLAPSIBLE_ROCK_TOWER_PUSH_UNIT_RAMP_RIGHT: Self = Self(563);
	pub const COLLAPSIBLE_ROCK_TOWER_PUSH_UNIT_RAMP_LEFT: Self = Self(564);
	pub const DIGESTER_CREEP_SPRAY_TARGET_UNIT: Self = Self(565);
	pub const DIGESTER_CREEP_SPRAY_UNIT: Self = Self(566);
	pub const RESOURCE_BLOCKER: Self = Self(569);
	pub const COLLAPSIBLE_ROCK_TOWER_DIAGONAL: Self = Self(588);
	pub const COLLAPSIBLE_TERRAN_TOWER_DIAGONAL: Self = Self(589);
	pub const COLLAPSIBLE_TERRAN_TOWER_RAMP_LEFT: Self = Self(590);
	pub const COLLAPSIBLE_TERRAN_TOWER_RAMP_RIGHT: Self = Self(591);
	pub const ICE_2_X_2_NON_CONJOINED: Self = Self(592);
	pub const ICE_PROTOSS_CRATES: Self = Self(593);
	pub const PROTOSS_CRATES: Self = Self(594);
	pub const TOWER_MINE: Self = Self(595);
	pub const PICKUP_PALLET_GAS: Self = Self(596);
	pub const PICKUP_PALLET_MINERALS: Self = Self(597);
	pub const PICKUP_SCRAP_SALVAGE_1_X_1: Self = Self(598);
	pub const PICKUP_SCRAP_SALVAGE_2_X_2: Self = Self(599);
	pub const PICKUP_SCRAP_SALVAGE_3_X_3: Self = Self(600);
	pub const ROUGH_TERRAIN: Self = Self(601);
	pub const UNBUILDABLE_BRICKS_SMALL_UNIT: Self = Self(602);
	pub const UNBUILDABLE_PLATES_SMALL_UNIT: Self = Self(603);
	pub const UNBUILDABLE_PLATES_UNIT: Self = Self(604);
	pub const UNBUILDABLE_ROCKS_SMALL_UNIT: Self = Self(605);
	pub const XEL_NAGA_HEALING_SHRINE: Self = Self(606);
	pub const PROTOSS_VESPENE_GEYSER: Self = Self(608);
	pub const COLLAPSIBLE_ROCK_TOWER: Self = Self(609);
	pub const COLLAPSIBLE_TERRAN_TOWER: Self = Self(610);
	pub const THORN_LIZARD: Self = Self(611);
	pub const CLEANING_BOT: Self = Self(612);
	pub const DESTRUCTIBLE_ROCK_6_X_6_WEAK: Self = Self(613);
	pub const PROTOSS_SNAKE_SEGMENT_DEMO: Self = Self(614);
	pub const PHYSICS_CAPSULE: Self = Self(615);
	pub const PHYSICS_CUBE: Self = Self(616);
	pub const PHYSICS_CYLINDER: Self = Self(617);
	pub const PHYSICS_KNOT: Self = Self(618);
	pub const PHYSICS_L: Self = Self(619);
	pub const PHYSICS_PRIMITIVES: Self = Self(620);
	pub const PHYSICS_SPHERE: Self = Self(621);
	pub const PHYSICS_STAR: Self = Self(622);
	pub const CREEP_BLOCKER_4_X_4: Self = Self(623);
	pub const DESTRUCTIBLE_CITY_DEBRIS_2_X_4_VERTICAL: Self = Self(624);
	pub const DESTRUCTIBLE_CITY_DEBRIS_2_X_4_HORIZONTAL: Self = Self(625);
	pub const DESTRUCTIBLE_CITY_DEBRIS_2_X_6_VERTICAL: Self = Self(626);
	pub const DESTRUCTIBLE_CITY_DEBRIS_2_X_6_HORIZONTAL: Self = Self(627);
	pub const DESTRUCTIBLE_CITY_DEBRIS_4_X_4: Self = Self(628);
	pub const DESTRUCTIBLE_CITY_DEBRIS_6_X_6: Self = Self(629);
	pub const DESTRUCTIBLE_CITY_DEBRIS_HUGE_DIAGONAL_BLUR: Self = Self(630);
	pub const DESTRUCTIBLE_CITY_DEBRIS_HUGE_DIAGONAL_ULBR: Self = Self(631);
	pub const TEST_ZERG: Self = Self(632);
	pub const PATHING_BLOCKER_RADIUS_1: Self = Self(633);
	pub const DESTRUCTIBLE_ROCK_EX_12_X_4_VERTICAL: Self = Self(634);
	pub const DESTRUCTIBLE_ROCK_EX_12_X_4_HORIZONTAL: Self = Self(635);
	pub const DESTRUCTIBLE_ROCK_EX_12_X_6_VERTICAL: Self = Self(636);
	pub const DESTRUCTIBLE_ROCK_EX_12_X_6_HORIZONTAL: Self = Self(637);
	pub const DESTRUCTIBLE_ROCK_EX_14_X_4: Self = Self(638);
	pub const DESTRUCTIBLE_ROCK_EX_16_X_6: Self = Self(639);
	pub const DESTRUCTIBLE_ROCK_EX_1_DIAGONAL_HUGE_ULBR: Self = Self(640);
	pub const DESTRUCTIBLE_ROCK_EX_1_DIAGONAL_HUGE_BLUR: Self = Self(641);
	pub const DESTRUCTIBLE_ROCK_EX_1_VERTICAL_HUGE: Self = Self(642);
	pub const DESTRUCTIBLE_ROCK_EX_1_HORIZONTAL_HUGE: Self = Self(643);
	pub const DESTRUCTIBLE_ICE_2_X_4_VERTICAL: Self = Self(644);
	pub const DESTRUCTIBLE_ICE_2_X_4_HORIZONTAL: Self = Self(645);
	pub const DESTRUCTIBLE_ICE_2_X_6_VERTICAL: Self = Self(646);
	pub const DESTRUCTIBLE_ICE_2_X_6_HORIZONTAL: Self = Self(647);
	pub const DESTRUCTIBLE_ICE_4_X_4: Self = Self(648);
	pub const DESTRUCTIBLE_ICE_6_X_6: Self = Self(649);
	pub const DESTRUCTIBLE_ICE_DIAGONAL_HUGE_ULBR: Self = Self(650);
	pub const DESTRUCTIBLE_ICE_DIAGONAL_HUGE_BLUR: Self = Self(651);
	pub const DESTRUCTIBLE_ICE_VERTICAL_HUGE: Self = Self(652);
	pub const DESTRUCTIBLE_ICE_HORIZONTAL_HUGE: Self = Self(653);
	pub const DESERT_PLANET_SEARCHLIGHT: Self = Self(654);
	pub const DESERT_PLANET_STREETLIGHT: Self = Self(655);
	pub const UNBUILDABLE_BRICKS_UNIT: Self = Self(656);
	pub const UNBUILDABLE_ROCKS_UNIT: Self = Self(657);
	pub const ZERUS_DESTRUCTIBLE_ARCH: Self = Self(658);
	pub const ARTOSILOPE: Self = Self(659);
	pub const ANTEPLOTT: Self = Self(660);
	pub const LAB_BOT: Self = Self(661);
	pub const CRABEETLE: Self = Self(662);
	pub const COLLAPSIBLE_ROCK_TOWER_RAMP_RIGHT: Self = Self(663);
	pub const COLLAPSIBLE_ROCK_TOWER_RAMP_LEFT: Self = Self(664);
	pub const LAB_MINERAL_FIELD: Self = Self(665);
	pub const LAB_MINERAL_FIELD_750: Self = Self(666);
	pub const RAVAGER_COCOON: Self = Self(687);
	pub const RAVAGER: Self = Self(688);
	pub const LIBERATOR: Self = Self(689);
	pub const RAVAGER_BURROWED: Self = Self(690);
	pub const THOR_AP: Self = Self(691);
	pub const CYCLONE: Self = Self(692);
	pub const LOCUST_MP_FLYING: Self = Self(693);
	pub const DISRUPTOR: Self = Self(694);
	pub const VOID_MP_IMMORTAL_REVIVE_CORPSE: Self = Self(725);
	pub const GUARDIAN_COCOON_MP: Self = Self(726);
	pub const GUARDIAN_MP: Self = Self(727);
	pub const DEVOURER_COCOON_MP: Self = Self(728);
	pub const DEVOURER_MP: Self = Self(729);
	pub const DEFILER_MP_BURROWED: Self = Self(730);
	pub const DEFILER_MP: Self = Self(731);
	pub const ORACLE_STASIS_TRAP: Self = Self(732);
	pub const DISRUPTOR_PHASED: Self = Self(733);
	pub const LIBERATOR_AG: Self = Self(734);
	pub const COLLAPSIBLE_PURIFIER_TOWER_DEBRIS: Self = Self(747);
	pub const PURIFIER_RICH_MINERAL_FIELD: Self = Self(796);
	pub const PURIFIER_RICH_MINERAL_FIELD_750: Self = Self(797);
	pub const COLLAPSIBLE_PURIFIER_TOWER_PUSH_UNIT: Self = Self(798);
	pub const LOCUST_MP_PRECURSOR: Self = Self(799);
	pub const RELEASE_INTERCEPTORS_BEACON: Self = Self(800);
	pub const ADEPT_PHASE_SHIFT: Self = Self(801);
	pub const CYCLONE_MISSILE_LARGE_AIR: Self = Self(804);
	pub const CYCLONE_MISSILE_LARGE: Self = Self(806);
	pub const THOR_AA_LANCE: Self = Self(807);
	pub const HERC_PLACEMENT: Self = Self(820);
	pub const KD_8_CHARGE: Self = Self(830);
	pub const SLAYN_ELEMENTAL_GRAB_AIR_UNIT: Self = Self(833);
	pub const SLAYN_ELEMENTAL_GRAB_GROUND_UNIT: Self = Self(834);
	pub const DESTRUCTIBLE_EXPEDITION_GATE_6_X_6: Self = Self(836);
	pub const DESTRUCTIBLE_ZERG_INFESTATION_3_X_3: Self = Self(837);
	pub const HERC: Self = Self(838);
	pub const MOOPY: Self = Self(839);
	pub const REPLICANT: Self = Self(840);
	pub const FLYOVER_UNIT: Self = Self(854);
	pub const CORSAIR_MP: Self = Self(855);
	pub const SCOUT_MP: Self = Self(856);
	pub const ARBITER_MP: Self = Self(857);
	pub const SCOURGE_MP: Self = Self(858);
	pub const QUEEN_MP: Self = Self(860);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_6_S: Self = Self(861);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_6_SE: Self = Self(862);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_6_E: Self = Self(863);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_6_NE: Self = Self(864);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_6_N: Self = Self(865);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_6_NW: Self = Self(866);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_6_W: Self = Self(867);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_6_SW: Self = Self(868);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_8_S: Self = Self(869);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_8_SE: Self = Self(870);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_8_E: Self = Self(871);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_8_NE: Self = Self(872);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_8_N: Self = Self(873);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_8_NW: Self = Self(874);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_8_W: Self = Self(875);
	pub const XEL_NAGA_DESTRUCTIBLE_RAMP_BLOCKER_8_SW: Self = Self(876);
	pub const REPTILE_CRATE: Self = Self(877);
	pub const SLAYN_SWARM_HOST_SPAWN_FLYER: Self = Self(878);
	pub const SLAYN_ELEMENTAL: Self = Self(879);
	pub const PURIFIER_VESPENE_GEYSER: Self = Self(880);
	pub const SHAKURAS_VESPENE_GEYSER: Self = Self(881);
	pub const COLLAPSIBLE_PURIFIER_TOWER_DIAGONAL: Self = Self(882);
	pub const CREEP_ONLY_BLOCKER_4_X_4: Self = Self(883);
	pub const PURIFIER_MINERAL_FIELD: Self = Self(884);
	pub const PURIFIER_MINERAL_FIELD_750: Self = Self(885);
	pub const BATTLE_STATION_MINERAL_FIELD: Self = Self(886);
	pub const BATTLE_STATION_MINERAL_FIELD_750: Self = Self(887);
	pub const BEACON_NOVA: Self = Self(888);
	pub const BEACON_NOVA_SMALL: Self = Self(889);
	pub const URSULA: Self = Self(890);
	pub const ELSECARO_COLONIST_HUT: Self = Self(891);
	pub const TRANSPORT_OVERLORD_COCOON: Self = Self(892);
	pub const OVERLORD_TRANSPORT: Self = Self(893);
	pub const PYLON_OVERCHARGED: Self = Self(894);
	pub const BYPASS_ARMOR_DRONE: Self = Self(895);
	pub const HIGH_TEMPLAR_SKIN_PREVIEW: Self = Self(1887);
	pub const WARP_PRISM_SKIN_PREVIEW: Self = Self(1888);
	pub const SIEGE_TANK_SKIN_PREVIEW: Self = Self(1889);
	pub const LIBERATOR_SKIN_PREVIEW: Self = Self(1890);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_6_S: Self = Self(1893);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_6_SE: Self = Self(1894);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_6_E: Self = Self(1895);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_6_NE: Self = Self(1896);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_6_N: Self = Self(1897);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_6_NW: Self = Self(1898);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_6_W: Self = Self(1899);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_6_SW: Self = Self(1900);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_8_S: Self = Self(1901);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_8_SE: Self = Self(1902);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_8_E: Self = Self(1903);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_8_NE: Self = Self(1904);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_8_N: Self = Self(1905);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_8_NW: Self = Self(1906);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_8_W: Self = Self(1907);
	pub const XEL_NAGA_DESTRUCTIBLE_BLOCKER_8_SW: Self = Self(1908);
	pub const SNOW_GLAZE_STARTER_MP: Self = Self(1909);
	pub const SHIELD_BATTERY: Self = Self(1910);
	pub const OBSERVER_SIEGE_MODE: Self = Self(1911);
	pub const OVERSEER_SIEGE_MODE: Self = Self(1912);
	pub const RAVEN_REPAIR_DRONE: Self = Self(1913);
	pub const CYCLONE_MISSILE_LARGE_AIR_ALTERNATIVE: Self = Self(1915);
	pub const SNARE_PLACEHOLDER: Self = Self(1921);
	pub const VIKING: Self = Self(1940);
	pub const RENEGADE_MISSILE_TURRET: Self = Self(1941);
	pub const REFINERY_RICH: Self = Self(1943);
	pub const PREVIEW_BUNKER_UPGRADED: Self = Self(1981);
	pub const INHIBITOR_ZONE_SMALL: Self = Self(1982);
	pub const INHIBITOR_ZONE_MEDIUM: Self = Self(1983);
	pub const INHIBITOR_ZONE_LARGE: Self = Self(1984);
	pub const ASSIMILATOR_RICH: Self = Self(1994);
	pub const EXTRACTOR_RICH: Self = Self(1995);
	pub const MINERAL_FIELD_450: Self = Self(1996);
	pub const MINERAL_FIELD_OPAQUE: Self = Self(1997);
	pub const MINERAL_FIELD_OPAQUE_900: Self = Self(1998);
	pub const COLLAPSIBLE_ROCK_TOWER_DEBRIS_RAMP_LEFT_GREEN: Self = Self(1999);
	pub const COLLAPSIBLE_ROCK_TOWER_DEBRIS_RAMP_RIGHT_GREEN: Self = Self(2000);
	pub const COLLAPSIBLE_ROCK_TOWER_PUSH_UNIT_RAMP_LEFT_GREEN: Self = Self(2001);
	pub const COLLAPSIBLE_ROCK_TOWER_PUSH_UNIT_RAMP_RIGHT_GREEN: Self = Self(2002);
	pub const COLLAPSIBLE_ROCK_TOWER_RAMP_LEFT_GREEN: Self = Self(2003);
	pub const COLLAPSIBLE_ROCK_TOWER_RAMP_RIGHT_GREEN: Self = Self(2004);
}
impl fmt::Display for UnitKind {
	fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
		let s = match self.0 {
			0 => "None",
			2 => "Ball",
			3 => "Stereoscopic Options Unit",
			4 => "Colossus",
			5 => "Tech Lab",
			6 => "Reactor",
			7 => "Infestor Terran",
			8 => "Baneling Cocoon",
			9 => "Baneling",
			10 => "Mothership",
			11 => "Point Defense Drone",
			12 => "Changeling",
			13 => "Changeling Zealot",
			14 => "Changeling Marine Shield",
			15 => "Changeling Marine",
			16 => "Changeling Zergling Wings",
			17 => "Changeling Zergling",
			18 => "Command Center",
			19 => "Supply Depot",
			20 => "Refinery",
			21 => "Barracks",
			22 => "Engineering Bay",
			23 => "Missile Turret",
			24 => "Bunker",
			25 => "Sensor Tower",
			26 => "Ghost Academy",
			27 => "Factory",
			28 => "Starport",
			29 => "Armory",
			30 => "Fusion Core",
			31 => "Auto Turret",
			32 => "Siege Tank Sieged",
			33 => "Siege Tank",
			34 => "Viking Assault",
			35 => "Viking Fighter",
			36 => "Command Center Flying",
			37 => "Barracks Tech Lab",
			38 => "Barracks Reactor",
			39 => "Factory Tech Lab",
			40 => "Factory Reactor",
			41 => "Starport Tech Lab",
			42 => "Starport Reactor",
			43 => "Factory Flying",
			44 => "Starport Flying",
			45 => "Scv",
			46 => "Barracks Flying",
			47 => "Supply Depot Lowered",
			48 => "Marine",
			49 => "Reaper",
			50 => "Ghost",
			51 => "Marauder",
			52 => "Thor",
			53 => "Hellion",
			54 => "Medivac",
			55 => "Banshee",
			56 => "Raven",
			57 => "Battlecruiser",
			58 => "Nuke",
			59 => "Nexus",
			60 => "Pylon",
			61 => "Assimilator",
			62 => "Gateway",
			63 => "Forge",
			64 => "Fleet Beacon",
			65 => "Twilight Council",
			66 => "Photon Cannon",
			67 => "Stargate",
			68 => "Templar Archive",
			69 => "Dark Shrine",
			70 => "Robotics Bay",
			71 => "Robotics Facility",
			72 => "Cybernetics Core",
			73 => "Zealot",
			74 => "Stalker",
			75 => "High Templar",
			76 => "Dark Templar",
			77 => "Sentry",
			78 => "Phoenix",
			79 => "Carrier",
			80 => "Void Ray",
			81 => "Warp Prism",
			82 => "Observer",
			83 => "Immortal",
			84 => "Probe",
			85 => "Interceptor",
			86 => "Hatchery",
			87 => "Creep Tumor",
			88 => "Extractor",
			89 => "Spawning Pool",
			90 => "Evolution Chamber",
			91 => "Hydralisk Den",
			92 => "Spire",
			93 => "Ultralisk Cavern",
			94 => "Infestation Pit",
			95 => "Nydus Network",
			96 => "Baneling Nest",
			97 => "Roach Warren",
			98 => "Spine Crawler",
			99 => "Spore Crawler",
			100 => "Lair",
			101 => "Hive",
			102 => "Greater Spire",
			103 => "Egg",
			104 => "Drone",
			105 => "Zergling",
			106 => "Overlord",
			107 => "Hydralisk",
			108 => "Mutalisk",
			109 => "Ultralisk",
			110 => "Roach",
			111 => "Infestor",
			112 => "Corruptor",
			113 => "Brood Lord Cocoon",
			114 => "Brood Lord",
			115 => "Baneling Burrowed",
			116 => "Drone Burrowed",
			117 => "Hydralisk Burrowed",
			118 => "Roach Burrowed",
			119 => "Zergling Burrowed",
			120 => "Infestor Terran Burrowed",
			121 => "Redstone Lava Critter Burrowed",
			122 => "Redstone Lava Critter Injured Burrowed",
			123 => "Redstone Lava Critter",
			124 => "Redstone Lava Critter Injured",
			125 => "Queen Burrowed",
			126 => "Queen",
			127 => "Infestor Burrowed",
			128 => "Overlord Cocoon",
			129 => "Overseer",
			130 => "Planetary Fortress",
			131 => "Ultralisk Burrowed",
			132 => "Orbital Command",
			133 => "Warp Gate",
			134 => "Orbital Command Flying",
			135 => "Force Field",
			136 => "Warp Prism Phasing",
			137 => "Creep Tumor Burrowed",
			138 => "Creep Tumor Queen",
			139 => "Spine Crawler Uprooted",
			140 => "Spore Crawler Uprooted",
			141 => "Archon",
			142 => "Nydus Canal",
			143 => "Broodling Escort",
			144 => "Ghost Alternate",
			145 => "Ghost Nova",
			146 => "Rich Mineral Field",
			147 => "Rich Mineral Field 750",
			148 => "Ursadon",
			149 => "Xel Naga Tower",
			150 => "Infested Terrans Egg",
			151 => "Larva",
			152 => "Reaper Placeholder",
			268 => "Mule",
			289 => "Broodling",
			296 => "Beacon Rally",
			297 => "Beacon Army",
			298 => "Beacon Attack",
			299 => "Beacon Defend",
			300 => "Beacon Harass",
			301 => "Beacon Idle",
			302 => "Beacon Auto",
			303 => "Beacon Detect",
			304 => "Beacon Scout",
			305 => "Beacon Claim",
			306 => "Beacon Expand",
			307 => "Beacon Custom 1",
			308 => "Beacon Custom 2",
			309 => "Beacon Custom 3",
			310 => "Beacon Custom 4",
			311 => "Adept",
			312 => "Rocks 2 X 2 Non Conjoined",
			315 => "Beacon Protoss",
			316 => "Beacon Protoss Small",
			317 => "Beacon Terran",
			318 => "Beacon Terran Small",
			319 => "Beacon Zerg",
			320 => "Beacon Zerg Small",
			321 => "Lyote",
			322 => "Carrion Bird",
			323 => "Karak Male",
			324 => "Karak Female",
			325 => "Ursadak Female Exotic",
			326 => "Ursadak Male",
			327 => "Ursadak Female",
			328 => "Ursadak Calf",
			329 => "Ursadak Male Exotic",
			330 => "Utility Bot",
			331 => "Commentator Bot 1",
			332 => "Commentator Bot 2",
			333 => "Commentator Bot 3",
			334 => "Commentator Bot 4",
			335 => "Scantipede",
			336 => "Dog",
			337 => "Sheep",
			338 => "Cow",
			339 => "Infested Terrans Egg Placement",
			341 => "Mineral Field",
			342 => "Vespene Geyser",
			343 => "Space Platform Geyser",
			344 => "Rich Vespene Geyser",
			345 => "Destructible Searchlight",
			346 => "Destructible Bullhorn Lights",
			347 => "Destructible Streetlight",
			348 => "Destructible Space Platform Sign",
			349 => "Destructible Store Front City Props",
			350 => "Destructible Billboard Tall",
			351 => "Destructible Billboard Scrolling Text",
			352 => "Destructible Space Platform Barrier",
			353 => "Destructible Signs Directional",
			354 => "Destructible Signs Construction",
			355 => "Destructible Signs Funny",
			356 => "Destructible Signs Icons",
			357 => "Destructible Signs Warning",
			358 => "Destructible Garage",
			359 => "Destructible Garage Large",
			360 => "Destructible Traffic Signal",
			361 => "Traffic Signal",
			362 => "Braxis Alpha Destructible 1 X 1",
			363 => "Braxis Alpha Destructible 2 X 2",
			364 => "Destructible Debris 4 X 4",
			365 => "Destructible Debris 6 X 6",
			366 => "Destructible Rock 2 X 4 Vertical",
			367 => "Destructible Rock 2 X 4 Horizontal",
			368 => "Destructible Rock 2 X 6 Vertical",
			369 => "Destructible Rock 2 X 6 Horizontal",
			370 => "Destructible Rock 4 X 4",
			371 => "Destructible Rock 6 X 6",
			372 => "Destructible Ramp Diagonal Huge Ulbr",
			373 => "Destructible Ramp Diagonal Huge Blur",
			374 => "Destructible Ramp Vertical Huge",
			375 => "Destructible Ramp Horizontal Huge",
			376 => "Destructible Debris Ramp Diagonal Huge Ulbr",
			377 => "Destructible Debris Ramp Diagonal Huge Blur",
			378 => "Overlord Generate Creep Keybind",
			379 => "Mengsk Statue Alone",
			380 => "Mengsk Statue",
			381 => "Wolf Statue",
			382 => "Globe Statue",
			387 => "Creep Blocker 1 X 1",
			388 => "Permanent Creep Blocker 1 X 1",
			389 => "Pathing Blocker 1 X 1",
			390 => "Pathing Blocker 2 X 2",
			391 => "Auto Test Attack Target Ground",
			392 => "Auto Test Attack Target Air",
			393 => "Auto Test Attacker",
			394 => "Helper Emitter Selection Arrow",
			395 => "Multi Kill Object",
			472 => "Unbuildable Rocks Destructible",
			473 => "Unbuildable Bricks Destructible",
			474 => "Unbuildable Plates Destructible",
			475 => "Debris 2 X 2 Non Conjoined",
			476 => "Enemy Pathing Blocker 1 X 1",
			477 => "Enemy Pathing Blocker 2 X 2",
			478 => "Enemy Pathing Blocker 4 X 4",
			479 => "Enemy Pathing Blocker 8 X 8",
			480 => "Enemy Pathing Blocker 16 X 16",
			481 => "Scope Test",
			483 => "Mineral Field 750",
			484 => "Hellion Tank",
			485 => "Collapsible Terran Tower Debris",
			486 => "Debris Ramp Left",
			487 => "Debris Ramp Right",
			488 => "Mothership Core",
			489 => "Locust Mp",
			490 => "Collapsible Rock Tower Debris",
			491 => "Nydus Canal Attacker",
			492 => "Nydus Canal Creeper",
			493 => "Swarm Host Burrowed Mp",
			494 => "Swarm Host Mp",
			495 => "Oracle",
			496 => "Tempest",
			497 => "War Hound",
			498 => "Widow Mine",
			499 => "Viper",
			500 => "Widow Mine Burrowed",
			501 => "Lurker Mp Egg",
			502 => "Lurker Mp",
			503 => "Lurker Mp Burrowed",
			504 => "Lurker Den Mp",
			517 => "Collapsible Rock Tower Debris Ramp Right",
			518 => "Collapsible Rock Tower Debris Ramp Left",
			559 => "Collapsible Terran Tower Push Unit Ramp Left",
			560 => "Collapsible Terran Tower Push Unit Ramp Right",
			561 => "Collapsible Rock Tower Push Unit",
			562 => "Collapsible Terran Tower Push Unit",
			563 => "Collapsible Rock Tower Push Unit Ramp Right",
			564 => "Collapsible Rock Tower Push Unit Ramp Left",
			565 => "Digester Creep Spray Target Unit",
			566 => "Digester Creep Spray Unit",
			569 => "Resource Blocker",
			588 => "Collapsible Rock Tower Diagonal",
			589 => "Collapsible Terran Tower Diagonal",
			590 => "Collapsible Terran Tower Ramp Left",
			591 => "Collapsible Terran Tower Ramp Right",
			592 => "Ice 2 X 2 Non Conjoined",
			593 => "Ice Protoss Crates",
			594 => "Protoss Crates",
			595 => "Tower Mine",
			596 => "Pickup Pallet Gas",
			597 => "Pickup Pallet Minerals",
			598 => "Pickup Scrap Salvage 1 X 1",
			599 => "Pickup Scrap Salvage 2 X 2",
			600 => "Pickup Scrap Salvage 3 X 3",
			601 => "Rough Terrain",
			602 => "Unbuildable Bricks Small Unit",
			603 => "Unbuildable Plates Small Unit",
			604 => "Unbuildable Plates Unit",
			605 => "Unbuildable Rocks Small Unit",
			606 => "Xel Naga Healing Shrine",
			608 => "Protoss Vespene Geyser",
			609 => "Collapsible Rock Tower",
			610 => "Collapsible Terran Tower",
			611 => "Thorn Lizard",
			612 => "Cleaning Bot",
			613 => "Destructible Rock 6 X 6 Weak",
			614 => "Protoss Snake Segment Demo",
			615 => "Physics Capsule",
			616 => "Physics Cube",
			617 => "Physics Cylinder",
			618 => "Physics Knot",
			619 => "Physics L",
			620 => "Physics Primitives",
			621 => "Physics Sphere",
			622 => "Physics Star",
			623 => "Creep Blocker 4 X 4",
			624 => "Destructible City Debris 2 X 4 Vertical",
			625 => "Destructible City Debris 2 X 4 Horizontal",
			626 => "Destructible City Debris 2 X 6 Vertical",
			627 => "Destructible City Debris 2 X 6 Horizontal",
			628 => "Destructible City Debris 4 X 4",
			629 => "Destructible City Debris 6 X 6",
			630 => "Destructible City Debris Huge Diagonal Blur",
			631 => "Destructible City Debris Huge Diagonal Ulbr",
			632 => "Test Zerg",
			633 => "Pathing Blocker Radius 1",
			634 => "Destructible Rock Ex 12 X 4 Vertical",
			635 => "Destructible Rock Ex 12 X 4 Horizontal",
			636 => "Destructible Rock Ex 12 X 6 Vertical",
			637 => "Destructible Rock Ex 12 X 6 Horizontal",
			638 => "Destructible Rock Ex 14 X 4",
			639 => "Destructible Rock Ex 16 X 6",
			640 => "Destructible Rock Ex 1 Diagonal Huge Ulbr",
			641 => "Destructible Rock Ex 1 Diagonal Huge Blur",
			642 => "Destructible Rock Ex 1 Vertical Huge",
			643 => "Destructible Rock Ex 1 Horizontal Huge",
			644 => "Destructible Ice 2 X 4 Vertical",
			645 => "Destructible Ice 2 X 4 Horizontal",
			646 => "Destructible Ice 2 X 6 Vertical",
			647 => "Destructible Ice 2 X 6 Horizontal",
			648 => "Destructible Ice 4 X 4",
			649 => "Destructible Ice 6 X 6",
			650 => "Destructible Ice Diagonal Huge Ulbr",
			651 => "Destructible Ice Diagonal Huge Blur",
			652 => "Destructible Ice Vertical Huge",
			653 => "Destructible Ice Horizontal Huge",
			654 => "Desert Planet Searchlight",
			655 => "Desert Planet Streetlight",
			656 => "Unbuildable Bricks Unit",
			657 => "Unbuildable Rocks Unit",
			658 => "Zerus Destructible Arch",
			659 => "Artosilope",
			660 => "Anteplott",
			661 => "Lab Bot",
			662 => "Crabeetle",
			663 => "Collapsible Rock Tower Ramp Right",
			664 => "Collapsible Rock Tower Ramp Left",
			665 => "Lab Mineral Field",
			666 => "Lab Mineral Field 750",
			687 => "Ravager Cocoon",
			688 => "Ravager",
			689 => "Liberator",
			690 => "Ravager Burrowed",
			691 => "Thor Ap",
			692 => "Cyclone",
			693 => "Locust Mp Flying",
			694 => "Disruptor",
			725 => "Void Mp Immortal Revive Corpse",
			726 => "Guardian Cocoon Mp",
			727 => "Guardian Mp",
			728 => "Devourer Cocoon Mp",
			729 => "Devourer Mp",
			730 => "Defiler Mp Burrowed",
			731 => "Defiler Mp",
			732 => "Oracle Stasis Trap",
			733 => "Disruptor Phased",
			734 => "Liberator Ag",
			747 => "Collapsible Purifier Tower Debris",
			796 => "Purifier Rich Mineral Field",
			797 => "Purifier Rich Mineral Field 750",
			798 => "Collapsible Purifier Tower Push Unit",
			799 => "Locust Mp Precursor",
			800 => "Release Interceptors Beacon",
			801 => "Adept Phase Shift",
			804 => "Cyclone Missile Large Air",
			806 => "Cyclone Missile Large",
			807 => "Thor Aa Lance",
			820 => "Herc Placement",
			830 => "Kd 8 Charge",
			833 => "Slayn Elemental Grab Air Unit",
			834 => "Slayn Elemental Grab Ground Unit",
			836 => "Destructible Expedition Gate 6 X 6",
			837 => "Destructible Zerg Infestation 3 X 3",
			838 => "Herc",
			839 => "Moopy",
			840 => "Replicant",
			854 => "Flyover Unit",
			855 => "Corsair Mp",
			856 => "Scout Mp",
			857 => "Arbiter Mp",
			858 => "Scourge Mp",
			860 => "Queen Mp",
			861 => "Xel Naga Destructible Ramp Blocker 6 S",
			862 => "Xel Naga Destructible Ramp Blocker 6 Se",
			863 => "Xel Naga Destructible Ramp Blocker 6 E",
			864 => "Xel Naga Destructible Ramp Blocker 6 Ne",
			865 => "Xel Naga Destructible Ramp Blocker 6 N",
			866 => "Xel Naga Destructible Ramp Blocker 6 Nw",
			867 => "Xel Naga Destructible Ramp Blocker 6 W",
			868 => "Xel Naga Destructible Ramp Blocker 6 Sw",
			869 => "Xel Naga Destructible Ramp Blocker 8 S",
			870 => "Xel Naga Destructible Ramp Blocker 8 Se",
			871 => "Xel Naga Destructible Ramp Blocker 8 E",
			872 => "Xel Naga Destructible Ramp Blocker 8 Ne",
			873 => "Xel Naga Destructible Ramp Blocker 8 N",
			874 => "Xel Naga Destructible Ramp Blocker 8 Nw",
			875 => "Xel Naga Destructible Ramp Blocker 8 W",
			876 => "Xel Naga Destructible Ramp Blocker 8 Sw",
			877 => "Reptile Crate",
			878 => "Slayn Swarm Host Spawn Flyer",
			879 => "Slayn Elemental",
			880 => "Purifier Vespene Geyser",
			881 => "Shakuras Vespene Geyser",
			882 => "Collapsible Purifier Tower Diagonal",
			883 => "Creep Only Blocker 4 X 4",
			884 => "Purifier Mineral Field",
			885 => "Purifier Mineral Field 750",
			886 => "Battle Station Mineral Field",
			887 => "Battle Station Mineral Field 750",
			888 => "Beacon Nova",
			889 => "Beacon Nova Small",
			890 => "Ursula",
			891 => "Elsecaro Colonist Hut",
			892 => "Transport Overlord Cocoon",
			893 => "Overlord Transport",
			894 => "Pylon Overcharged",
			895 => "Bypass Armor Drone",
			1887 => "High Templar Skin Preview",
			1888 => "Warp Prism Skin Preview",
			1889 => "Siege Tank Skin Preview",
			1890 => "Liberator Skin Preview",
			1893 => "Xel Naga Destructible Blocker 6 S",
			1894 => "Xel Naga Destructible Blocker 6 Se",
			1895 => "Xel Naga Destructible Blocker 6 E",
			1896 => "Xel Naga Destructible Blocker 6 Ne",
			1897 => "Xel Naga Destructible Blocker 6 N",
			1898 => "Xel Naga Destructible Blocker 6 Nw",
			1899 => "Xel Naga Destructible Blocker 6 W",
			1900 => "Xel Naga Destructible Blocker 6 Sw",
			1901 => "Xel Naga Destructible Blocker 8 S",
			1902 => "Xel Naga Destructible Blocker 8 Se",
			1903 => "Xel Naga Destructible Blocker 8 E",
			1904 => "Xel Naga Destructible Blocker 8 Ne",
			1905 => "Xel Naga Destructible Blocker 8 N",
			1906 => "Xel Naga Destructible Blocker 8 Nw",
			1907 => "Xel Naga Destructible Blocker 8 W",
			1908 => "Xel Naga Destructible Blocker 8 Sw",
			1909 => "Snow Glaze Starter Mp",
			1910 => "Shield Battery",
			1911 => "Observer Siege Mode",
			1912 => "Overseer Siege Mode",
			1913 => "Raven Repair Drone",
			1915 => "Cyclone Missile Large Air Alternative",
			1921 => "Snare Placeholder",
			1940 => "Viking",
			1941 => "Renegade Missile Turret",
			1943 => "Refinery Rich",
			1981 => "Preview Bunker Upgraded",
			1982 => "Inhibitor Zone Small",
			1983 => "Inhibitor Zone Medium",
			1984 => "Inhibitor Zone Large",
			1994 => "Assimilator Rich",
			1995 => "Extractor Rich",
			1996 => "Mineral Field 450",
			1997 => "Mineral Field Opaque",
			1998 => "Mineral Field Opaque 900",
			1999 => "Collapsible Rock Tower Debris Ramp Left Green",
			2000 => "Collapsible Rock Tower Debris Ramp Right Green",
			2001 => "Collapsible Rock Tower Push Unit Ramp Left Green",
			2002 => "Collapsible Rock Tower Push Unit Ramp Right Green",
			2003 => "Collapsible Rock Tower Ramp Left Green",
			2004 => "Collapsible Rock Tower Ramp Right Green",
			_ => return write!(f, "{self:?}"),
		};
		write!(f, "{s}")
	}
}
impl From<u32> for UnitKind {
	fn from(n: u32) -> Self {
		Self(n)
	}
}
impl From<UnitKind> for u32 {
	fn from(id: UnitKind) -> Self {
		id.0
	}
}
