use std::fmt;

#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct Upgrade(pub u32);
impl Upgrade {
	pub const NONE: Self = Self(0);
	pub const CARRIER_LAUNCH_SPEED_UPGRADE: Self = Self(1);
	pub const GLIAL_RECONSTITUTION: Self = Self(2);
	pub const TUNNELING_CLAWS: Self = Self(3);
	pub const CHITINOUS_PLATING: Self = Self(4);
	pub const HI_SEC_AUTO_TRACKING: Self = Self(5);
	pub const TERRAN_BUILDING_ARMOR: Self = Self(6);
	pub const TERRAN_INFANTRY_WEAPONS_LEVEL_1: Self = Self(7);
	pub const TERRAN_INFANTRY_WEAPONS_LEVEL_2: Self = Self(8);
	pub const TERRAN_INFANTRY_WEAPONS_LEVEL_3: Self = Self(9);
	pub const NEOSTEEL_FRAME: Self = Self(10);
	pub const TERRAN_INFANTRY_ARMORS_LEVEL_1: Self = Self(11);
	pub const TERRAN_INFANTRY_ARMORS_LEVEL_2: Self = Self(12);
	pub const TERRAN_INFANTRY_ARMORS_LEVEL_3: Self = Self(13);
	pub const REAPER_SPEED: Self = Self(14);
	pub const STIMPACK: Self = Self(15);
	pub const SHIELD_WALL: Self = Self(16);
	pub const PUNISHER_GRENADES: Self = Self(17);
	pub const HIGH_CAPACITY_BARRELS: Self = Self(19);
	pub const BANSHEE_CLOAK: Self = Self(20);
	pub const MEDIVAC_CADUCEUS_REACTOR: Self = Self(21);
	pub const RAVEN_CORVID_REACTOR: Self = Self(22);
	pub const HUNTER_SEEKER: Self = Self(23);
	pub const DURABLE_MATERIALS: Self = Self(24);
	pub const PERSONAL_CLOAKING: Self = Self(25);
	pub const TERRAN_VEHICLE_ARMORS_LEVEL_1: Self = Self(27);
	pub const TERRAN_VEHICLE_ARMORS_LEVEL_2: Self = Self(28);
	pub const TERRAN_VEHICLE_ARMORS_LEVEL_3: Self = Self(29);
	pub const TERRAN_VEHICLE_WEAPONS_LEVEL_1: Self = Self(30);
	pub const TERRAN_VEHICLE_WEAPONS_LEVEL_2: Self = Self(31);
	pub const TERRAN_VEHICLE_WEAPONS_LEVEL_3: Self = Self(32);
	pub const TERRAN_SHIP_ARMORS_LEVEL_1: Self = Self(33);
	pub const TERRAN_SHIP_ARMORS_LEVEL_2: Self = Self(34);
	pub const TERRAN_SHIP_ARMORS_LEVEL_3: Self = Self(35);
	pub const TERRAN_SHIP_WEAPONS_LEVEL_1: Self = Self(36);
	pub const TERRAN_SHIP_WEAPONS_LEVEL_2: Self = Self(37);
	pub const TERRAN_SHIP_WEAPONS_LEVEL_3: Self = Self(38);
	pub const PROTOSS_GROUND_WEAPONS_LEVEL_1: Self = Self(39);
	pub const PROTOSS_GROUND_WEAPONS_LEVEL_2: Self = Self(40);
	pub const PROTOSS_GROUND_WEAPONS_LEVEL_3: Self = Self(41);
	pub const PROTOSS_GROUND_ARMORS_LEVEL_1: Self = Self(42);
	pub const PROTOSS_GROUND_ARMORS_LEVEL_2: Self = Self(43);
	pub const PROTOSS_GROUND_ARMORS_LEVEL_3: Self = Self(44);
	pub const PROTOSS_SHIELDS_LEVEL_1: Self = Self(45);
	pub const PROTOSS_SHIELDS_LEVEL_2: Self = Self(46);
	pub const PROTOSS_SHIELDS_LEVEL_3: Self = Self(47);
	pub const OBSERVER_GRAVITIC_BOOSTER: Self = Self(48);
	pub const GRAVITIC_DRIVE: Self = Self(49);
	pub const EXTENDED_THERMAL_LANCE: Self = Self(50);
	pub const PSI_STORM_TECH: Self = Self(52);
	pub const ZERG_MELEE_WEAPONS_LEVEL_1: Self = Self(53);
	pub const ZERG_MELEE_WEAPONS_LEVEL_2: Self = Self(54);
	pub const ZERG_MELEE_WEAPONS_LEVEL_3: Self = Self(55);
	pub const ZERG_GROUND_ARMORS_LEVEL_1: Self = Self(56);
	pub const ZERG_GROUND_ARMORS_LEVEL_2: Self = Self(57);
	pub const ZERG_GROUND_ARMORS_LEVEL_3: Self = Self(58);
	pub const ZERG_MISSILE_WEAPONS_LEVEL_1: Self = Self(59);
	pub const ZERG_MISSILE_WEAPONS_LEVEL_2: Self = Self(60);
	pub const ZERG_MISSILE_WEAPONS_LEVEL_3: Self = Self(61);
	pub const OVERLORDSPEED: Self = Self(62);
	pub const OVERLORDTRANSPORT: Self = Self(63);
	pub const BURROW: Self = Self(64);
	pub const ZERGLINGATTACKSPEED: Self = Self(65);
	pub const ZERGLINGMOVEMENTSPEED: Self = Self(66);
	pub const ZERG_FLYER_WEAPONS_LEVEL_1: Self = Self(68);
	pub const ZERG_FLYER_WEAPONS_LEVEL_2: Self = Self(69);
	pub const ZERG_FLYER_WEAPONS_LEVEL_3: Self = Self(70);
	pub const ZERG_FLYER_ARMORS_LEVEL_1: Self = Self(71);
	pub const ZERG_FLYER_ARMORS_LEVEL_2: Self = Self(72);
	pub const ZERG_FLYER_ARMORS_LEVEL_3: Self = Self(73);
	pub const CENTRIFICAL_HOOKS: Self = Self(75);
	pub const BATTLECRUISER_ENABLE_SPECIALIZATIONS: Self = Self(76);
	pub const PROTOSS_AIR_WEAPONS_LEVEL_1: Self = Self(78);
	pub const PROTOSS_AIR_WEAPONS_LEVEL_2: Self = Self(79);
	pub const PROTOSS_AIR_WEAPONS_LEVEL_3: Self = Self(80);
	pub const PROTOSS_AIR_ARMORS_LEVEL_1: Self = Self(81);
	pub const PROTOSS_AIR_ARMORS_LEVEL_2: Self = Self(82);
	pub const PROTOSS_AIR_ARMORS_LEVEL_3: Self = Self(83);
	pub const WARP_GATE_RESEARCH: Self = Self(84);
	pub const HALTECH: Self = Self(85);
	pub const CHARGE: Self = Self(86);
	pub const BLINK_TECH: Self = Self(87);
	pub const ANABOLIC_SYNTHESIS: Self = Self(88);
	pub const TRANSFORMATION_SERVOS: Self = Self(98);
	pub const PHOENIX_RANGE_UPGRADE: Self = Self(99);
	pub const TEMPEST_RANGE_UPGRADE: Self = Self(100);
	pub const NEURAL_PARASITE: Self = Self(101);
	pub const LOCUST_LIFETIME_INCREASE: Self = Self(102);
	pub const TERRAN_VEHICLE_AND_SHIP_WEAPONS_LEVEL_1: Self = Self(113);
	pub const TERRAN_VEHICLE_AND_SHIP_WEAPONS_LEVEL_2: Self = Self(114);
	pub const TERRAN_VEHICLE_AND_SHIP_WEAPONS_LEVEL_3: Self = Self(115);
	pub const TERRAN_VEHICLE_AND_SHIP_ARMORS_LEVEL_1: Self = Self(116);
	pub const TERRAN_VEHICLE_AND_SHIP_ARMORS_LEVEL_2: Self = Self(117);
	pub const TERRAN_VEHICLE_AND_SHIP_ARMORS_LEVEL_3: Self = Self(118);
	pub const ROACH_SUPPLY: Self = Self(120);
	pub const IMMORTAL_REVIVE: Self = Self(121);
	pub const DRILL_CLAWS: Self = Self(122);
	pub const CYCLONE_LOCK_ON_RANGE_UPGRADE: Self = Self(123);
	pub const LIBERATOR_MORPH: Self = Self(125);
	pub const LURKER_RANGE: Self = Self(127);
	pub const ADEPT_PIERCING_ATTACK: Self = Self(130);
	pub const EVOLVE_GROOVED_SPINES: Self = Self(134);
	pub const EVOLVE_MUSCULAR_AUGMENTS: Self = Self(135);
	pub const BANSHEE_SPEED: Self = Self(136);
	pub const MEDIVAC_RAPID_DEPLOYMENT: Self = Self(137);
	pub const RAVEN_RECALIBRATED_EXPLOSIVES: Self = Self(138);
	pub const MEDIVAC_INCREASE_SPEED_BOOST: Self = Self(139);
	pub const LIBERATOR_AG_RANGE_UPGRADE: Self = Self(140);
	pub const DARK_TEMPLAR_BLINK_UPGRADE: Self = Self(141);
	pub const CYCLONE_LOCK_ON_DAMAGE_UPGRADE: Self = Self(144);
	pub const VOID_RAY_SPEED_UPGRADE: Self = Self(288);
	pub const SMART_SERVOS: Self = Self(289);
	pub const ARMOR_PIERCING_ROCKETS: Self = Self(290);
	pub const CYCLONE_RAPID_FIRE_LAUNCHERS: Self = Self(291);
	pub const RAVEN_ENHANCED_MUNITIONS: Self = Self(292);
	pub const DIGGING_CLAWS: Self = Self(293);
	pub const HURRICANE_THRUSTERS: Self = Self(296);
	pub const TEMPEST_GROUND_ATTACK_UPGRADE: Self = Self(297);
	pub const MICROBIAL_SHROUD: Self = Self(298);
	pub const INTERFERENCE_MATRIX: Self = Self(299);
	pub const SUNDERING_IMPACT: Self = Self(300);
	pub const AMPLIFIED_SHIELDING: Self = Self(301);
	pub const PSIONIC_AMPLIFIERS: Self = Self(302);
	pub const SECRETED_COATING: Self = Self(303);
	pub const FRENZY: Self = Self(305);
}
impl fmt::Display for Upgrade {
	fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
		let s = match self.0 {
			0 => "None",
			1 => "Carrier Launch Speed Upgrade",
			2 => "Glial Reconstitution",
			3 => "Tunneling Claws",
			4 => "Chitinous Plating",
			5 => "Hi Sec Auto Tracking",
			6 => "Terran Building Armor",
			7 => "Terran Infantry Weapons Level 1",
			8 => "Terran Infantry Weapons Level 2",
			9 => "Terran Infantry Weapons Level 3",
			10 => "Neosteel Frame",
			11 => "Terran Infantry Armors Level 1",
			12 => "Terran Infantry Armors Level 2",
			13 => "Terran Infantry Armors Level 3",
			14 => "Reaper Speed",
			15 => "Stimpack",
			16 => "Shield Wall",
			17 => "Punisher Grenades",
			19 => "High Capacity Barrels",
			20 => "Banshee Cloak",
			21 => "Medivac Caduceus Reactor",
			22 => "Raven Corvid Reactor",
			23 => "Hunter Seeker",
			24 => "Durable Materials",
			25 => "Personal Cloaking",
			27 => "Terran Vehicle Armors Level 1",
			28 => "Terran Vehicle Armors Level 2",
			29 => "Terran Vehicle Armors Level 3",
			30 => "Terran Vehicle Weapons Level 1",
			31 => "Terran Vehicle Weapons Level 2",
			32 => "Terran Vehicle Weapons Level 3",
			33 => "Terran Ship Armors Level 1",
			34 => "Terran Ship Armors Level 2",
			35 => "Terran Ship Armors Level 3",
			36 => "Terran Ship Weapons Level 1",
			37 => "Terran Ship Weapons Level 2",
			38 => "Terran Ship Weapons Level 3",
			39 => "Protoss Ground Weapons Level 1",
			40 => "Protoss Ground Weapons Level 2",
			41 => "Protoss Ground Weapons Level 3",
			42 => "Protoss Ground Armors Level 1",
			43 => "Protoss Ground Armors Level 2",
			44 => "Protoss Ground Armors Level 3",
			45 => "Protoss Shields Level 1",
			46 => "Protoss Shields Level 2",
			47 => "Protoss Shields Level 3",
			48 => "Observer Gravitic Booster",
			49 => "Gravitic Drive",
			50 => "Extended Thermal Lance",
			52 => "Psi Storm Tech",
			53 => "Zerg Melee Weapons Level 1",
			54 => "Zerg Melee Weapons Level 2",
			55 => "Zerg Melee Weapons Level 3",
			56 => "Zerg Ground Armors Level 1",
			57 => "Zerg Ground Armors Level 2",
			58 => "Zerg Ground Armors Level 3",
			59 => "Zerg Missile Weapons Level 1",
			60 => "Zerg Missile Weapons Level 2",
			61 => "Zerg Missile Weapons Level 3",
			62 => "Overlordspeed",
			63 => "Overlordtransport",
			64 => "Burrow",
			65 => "Zerglingattackspeed",
			66 => "Zerglingmovementspeed",
			68 => "Zerg Flyer Weapons Level 1",
			69 => "Zerg Flyer Weapons Level 2",
			70 => "Zerg Flyer Weapons Level 3",
			71 => "Zerg Flyer Armors Level 1",
			72 => "Zerg Flyer Armors Level 2",
			73 => "Zerg Flyer Armors Level 3",
			75 => "Centrifical Hooks",
			76 => "Battlecruiser Enable Specializations",
			78 => "Protoss Air Weapons Level 1",
			79 => "Protoss Air Weapons Level 2",
			80 => "Protoss Air Weapons Level 3",
			81 => "Protoss Air Armors Level 1",
			82 => "Protoss Air Armors Level 2",
			83 => "Protoss Air Armors Level 3",
			84 => "Warp Gate Research",
			85 => "Haltech",
			86 => "Charge",
			87 => "Blink Tech",
			88 => "Anabolic Synthesis",
			98 => "Transformation Servos",
			99 => "Phoenix Range Upgrade",
			100 => "Tempest Range Upgrade",
			101 => "Neural Parasite",
			102 => "Locust Lifetime Increase",
			113 => "Terran Vehicle And Ship Weapons Level 1",
			114 => "Terran Vehicle And Ship Weapons Level 2",
			115 => "Terran Vehicle And Ship Weapons Level 3",
			116 => "Terran Vehicle And Ship Armors Level 1",
			117 => "Terran Vehicle And Ship Armors Level 2",
			118 => "Terran Vehicle And Ship Armors Level 3",
			120 => "Roach Supply",
			121 => "Immortal Revive",
			122 => "Drill Claws",
			123 => "Cyclone Lock On Range Upgrade",
			125 => "Liberator Morph",
			127 => "Lurker Range",
			130 => "Adept Piercing Attack",
			134 => "Evolve Grooved Spines",
			135 => "Evolve Muscular Augments",
			136 => "Banshee Speed",
			137 => "Medivac Rapid Deployment",
			138 => "Raven Recalibrated Explosives",
			139 => "Medivac Increase Speed Boost",
			140 => "Liberator Ag Range Upgrade",
			141 => "Dark Templar Blink Upgrade",
			144 => "Cyclone Lock On Damage Upgrade",
			288 => "Void Ray Speed Upgrade",
			289 => "Smart Servos",
			290 => "Armor Piercing Rockets",
			291 => "Cyclone Rapid Fire Launchers",
			292 => "Raven Enhanced Munitions",
			293 => "Digging Claws",
			296 => "Hurricane Thrusters",
			297 => "Tempest Ground Attack Upgrade",
			298 => "Microbial Shroud",
			299 => "Interference Matrix",
			300 => "Sundering Impact",
			301 => "Amplified Shielding",
			302 => "Psionic Amplifiers",
			303 => "Secreted Coating",
			305 => "Frenzy",
			_ => return write!(f, "{self:?}"),
		};
		write!(f, "{s}")
	}
}
impl From<u32> for Upgrade {
	fn from(n: u32) -> Self {
		Self(n)
	}
}
impl From<Upgrade> for u32 {
	fn from(id: Upgrade) -> Self {
		id.0
	}
}
